// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v6.1.5 - BUNDLED BOOKMARKLET
// Built: 2026-03-29T20:24:44.773Z
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// ═══════════════════════════════════════════════════════════════════════════════

void function initDrunkWalker(){
  // Main entry point handles restart logic now
  
  // === VERSION ===
  const VERSION = '6.1.5';


  // === WHEEL ===
  /**
 * Wheel component for Drunk Walker
 * Manages orientation and turning (left and right)
 */

function createWheel(callbacks) {
  let orientation = 0; // 0-359

  const getOrientation = () => orientation;

  const setOrientation = (newOrientation) => {
    orientation = normalizeAngle(newOrientation);
  };

  const turnLeft = (angle, callback) => {
    // Update orientation IMMEDIATELY (intent-based)
    orientation = normalizeAngle(orientation - angle);

    // Convert angle to duration (10ms per degree as per existing code)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));

    let callbackCalled = false;
    const safeCallback = () => {
      if (callbackCalled) return;
      callbackCalled = true;
      if (callback) callback();
    };

    if (callbacks.onLongKeyPress) {
      callbacks.onLongKeyPress('ArrowLeft', clampedDuration, safeCallback);
      // Safety timeout in case onLongKeyPress doesn't call back
      setTimeout(safeCallback, clampedDuration + 500);
    } else {
      safeCallback();
    }
  };

  const turnRight = (angle, callback) => {
    // Update orientation IMMEDIATELY (intent-based)
    orientation = normalizeAngle(orientation + angle);

    // Convert angle to duration (10ms per degree)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));

    let callbackCalled = false;
    const safeCallback = () => {
      if (callbackCalled) return;
      callbackCalled = true;
      if (callback) callback();
    };

    if (callbacks.onLongKeyPress) {
      callbacks.onLongKeyPress('ArrowRight', clampedDuration, safeCallback);
      // Safety timeout
      setTimeout(safeCallback, clampedDuration + 500);
    } else {
      safeCallback();
    }
  };

  const normalizeAngle = (angle) => {
    angle = angle % 360;
    if (angle < 0) angle += 360;
    return angle;
  };

  return {
    getOrientation,
    setOrientation,
    turnLeft,
    turnRight,
    reset: () => { orientation = 0; }
  };
}


  // === TRAVERSAL ALGORITHMS ===
  /**
 * Traversal Algorithm v6.1.0 - PURE PLEDGE Wall-Following
 *
 * SIMPLE PLEDGE: FORWARD → TURN LEFT 120° → WALL-FOLLOW → BREAK WALL
 * NO breadcrumb navigation - pure wall-following only!
 *
 * Key features:
 * - Forward bearing (prev→cur) at new nodes
 * - Cul-de-sac verification at end of straight line
 * - Each node visited AT MOST TWICE
 * - Clear state when stuck >10 steps on 1-2 nodes
 */

function normalizeAngle(angle) {
  angle = angle % 360;
  if (angle < 0) angle += 360;
  return angle;
}

function yawDifference(yaw1, yaw2) {
  let diff = Math.abs(normalizeAngle(yaw1) - normalizeAngle(yaw2));
  if (diff > 180) diff = 360 - diff;
  return diff;
}

/**
 * Calculate angle to turn LEFT (counter-clockwise) to reach targetYaw from currentYaw
 * 
 * Example: Current=250°, Target=319°
 * - Left turn: 319 - 250 = 69° (counter-clockwise)
 * - Right turn: 360 - 69 = 291° (clockwise)
 * - This function returns: 69°
 */
function getLeftTurnAngle(currentYaw, targetYaw) {
  // LEFT turn (counter-clockwise) = current - target
  let angle = (normalizeAngle(currentYaw) - normalizeAngle(targetYaw) + 360) % 360;
  return angle;
}

function extractYawFromUrl(url) {
  if (!url) return null;
  const match = url.match(/yaw%3D([0-9.]+)/);
  return match ? parseFloat(match[1]) : null;
}

function extractLocationFromUrl(url) {
  if (!url) return null;
  const hashMatch = url.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
  if (hashMatch) {
    return `${hashMatch[1]},${hashMatch[2]}`;
  }
  return null;
}

/**
 * Calculate yaw from last movement (previous location → current)
 */
function calculateYawFromLastMove(previousLocation, currentLocation) {
  if (!previousLocation || !currentLocation || previousLocation === currentLocation) {
    return null;
  }

  const prev = previousLocation.split(',').map(Number);
  const curr = currentLocation.split(',').map(Number);

  const dLat = curr[0] - prev[0];
  const dLng = curr[1] - prev[1];

  let yaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
  if (yaw < 0) yaw += 360;

  return Math.round(yaw);
}

class NodeInfo {
  constructor(location, lat, lng, step) {
    this.location = location;
    this.lat = lat;
    this.lng = lng;
    this.triedYaws = new Set();
    this.successfulYaws = new Set();
    this.isFullyExplored = false;
  }

  recordAttempt(yaw, success, targetLocation = null) {
    const bucket = Math.round(normalizeAngle(yaw) / 60) * 60 % 360;
    this.triedYaws.add(bucket);
    if (success && targetLocation) {
      this.successfulYaws.add(bucket);
    }
    // Mark as fully explored when 5+ yaws tried
    if (this.triedYaws.size >= 5) {
      this.isFullyExplored = true;
    }
  }

  hasUntriedYaws() { return this.triedYaws.size < 6; }
}

class EnhancedTransitionGraph {
  constructor() {
    this.nodes = new Map();
    this.connections = new Map();
  }

  getOrCreate(location, lat, lng, step = 0) {
    if (!this.nodes.has(location)) {
      this.nodes.set(location, new NodeInfo(location, lat, lng, step));
      this.connections.set(location, new Set());
    }
    return this.nodes.get(location);
  }

  get(location) { return this.nodes.get(location); }

  recordMovement(fromLoc, toLoc, fromYaw, toYaw, step) {
    const fromNode = this.getOrCreate(fromLoc, parseFloat(fromLoc.split(',')[0]), parseFloat(fromLoc.split(',')[1]), step);
    const toNode = this.getOrCreate(toLoc, parseFloat(toLoc.split(',')[0]), parseFloat(toLoc.split(',')[1]), step);

    // Record forward direction at fromNode
    fromNode.recordAttempt(fromYaw, true, toLoc);

    // Record reverse direction at toNode (geometric direction back to where we came from)
    // Calculate from coordinates, NOT from toYaw (which is Google's camera orientation after landing)
    const fromParts = fromLoc.split(',').map(Number);
    const toParts = toLoc.split(',').map(Number);
    const dLat = fromParts[0] - toParts[0];  // FROM neighbor TO current
    const dLng = fromParts[1] - toParts[1];
    let reverseYaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
    if (reverseYaw < 0) reverseYaw += 360;
    reverseYaw = Math.round(reverseYaw);
    toNode.recordAttempt(reverseYaw, true, fromLoc);

    // Bidirectional connection tracking
    if (!this.connections.get(fromLoc).has(toLoc)) {
      this.connections.get(fromLoc).add(toLoc);
    }
    if (!this.connections.get(toLoc).has(fromLoc)) {
      this.connections.get(toLoc).add(fromLoc);
    }
  }

  recordFailedAttempt(location, yaw, step) {
    const parts = location.split(',');
    const node = this.getOrCreate(location, parseFloat(parts[0]), parseFloat(parts[1]), step);
    node.recordAttempt(yaw, false, null);
  }
}

/**
 * PURE PLEDGE ALGORITHM v6.1.0
 */
function createUnifiedAlgorithm(cfg) {
  const panicThreshold = cfg.panicThreshold || 3;

  // PLEDGE state
  let wallFollowMode = false;
  let wallFollowBearing = null;
  let forwardBearing = null;
  let deadPocketCount = 0;  // Track dead pocket detections before restart

  // Complete stuck detection - clear state when looping on same 1-2 nodes
  let locationStuckCounter = 0;
  let lastStuckLocation = null;
  let secondLastStuckLocation = null;

  // Progress tracking
  let consecutiveStraightMoves = 0;
  let lastDecisionWasTurn = false;
  let linearSegmentStart = null;

  // ═══════════════════════════════════════════════════════════
  // 🧭 COMMITTED DIRECTION: Hysteresis to prevent oscillation
  // Only change committed direction when bearing differs by >45°
  // ═══════════════════════════════════════════════════════════
  let committedDirection = null;

  const enhancedGraph = new EnhancedTransitionGraph();

  const decide = (context) => {
    const { stuckCount, currentLocation, previousLocation, visitedUrls, breadcrumbs, orientation, isNewNode, isFullyScanned, justArrived, nodeVisitCount } = context;

    console.log(`[DEBUG] decide() called: stuck=${stuckCount}, orientation=${Math.round(orientation)}°, loc=${currentLocation}`);
    console.log(`[DEBUG] breadcrumbs.length=${breadcrumbs.length}, graph.nodes=${enhancedGraph.nodes.size}`);
    console.log(`[DEBUG] isNewNode=${isNewNode}, isFullyScanned=${isFullyScanned}, justArrived=${justArrived}`);

    // ═══════════════════════════════════════════════════════════
    // 🚨 COMPLETE STUCK DETECTION: Clear state when stuck >20 steps on single node
    // DO NOT clear on 2-node loop - this is NORMAL behavior when backtracking!
    // ═══════════════════════════════════════════════════════════
    if (currentLocation === lastStuckLocation || currentLocation === secondLastStuckLocation) {
      locationStuckCounter++;

      // Detect 2-node loop (oscillating between same 2 locations)
      // This is NORMAL during wall-follow backtracking - don't clear graph!
      const isTwoNodeLoop = currentLocation === secondLastStuckLocation &&
                           previousLocation === lastStuckLocation;

      // Only clear state when stuck on SINGLE node for >20 steps (real stuck)
      if (locationStuckCounter > 20 && !isTwoNodeLoop) {
        console.log(`🚨 SINGLE-NODE STUCK DETECTED! stuckCounter=${locationStuckCounter}, location=${lastStuckLocation}`);
        console.log(`   Clearing PLEDGE state (keeping graph memory)...`);

        // Clear PLEDGE state ONLY - keep the graph (learned yaw info is valuable!)
        wallFollowMode = false;
        wallFollowBearing = null;
        forwardBearing = null;
        committedDirection = null;  // Reset committed direction
        consecutiveStraightMoves = 0;
        linearSegmentStart = null;
        locationStuckCounter = 0;
        lastStuckLocation = null;
        secondLastStuckLocation = null;

        // DO NOT clear enhancedGraph - we need to remember which yaws we tried!
        // enhancedGraph.nodes.clear();  // REMOVED - this was causing revisits!
        // enhancedGraph.connections.clear();  // REMOVED

        console.log(`   ✅ PLEDGE state cleared - graph preserved, continuing exploration`);
      }
    } else {
      // Location changed - reset stuck counter
      secondLastStuckLocation = lastStuckLocation;
      lastStuckLocation = currentLocation;
      locationStuckCounter = 1;
    }

    if (!currentLocation) {
      console.log('[DEBUG] No location, returning no turn');
      return { turn: false };
    }

    const currentParts = currentLocation.split(',').map(Number);
    const currentNode = enhancedGraph.getOrCreate(currentLocation, currentParts[0], currentParts[1]);

    console.log(`[DEBUG] currentNode.triedYaws=${[...currentNode.triedYaws].join(',')}, hasUntried=${currentNode.hasUntriedYaws()}`);

    // ═══════════════════════════════════════════════════════════
    // 🧭 SMOOTH FORWARD BEARING: Use rolling window of 3 breadcrumbs
    // This smooths yaw adjustments and reduces jittery turning
    // ═══════════════════════════════════════════════════════════
    let currentForwardBearing = orientation;
    if (previousLocation) {
      // Use rolling window: prefer 3-point average if available, else 2-point
      const windowSize = Math.min(3, breadcrumbs.length);
      if (windowSize >= 2) {
        // Get the last N locations from breadcrumbs
        const recentLocs = breadcrumbs.slice(-windowSize);
        if (recentLocs.length >= 2) {
          const first = recentLocs[0].split(',').map(Number);
          const last = recentLocs[recentLocs.length - 1].split(',').map(Number);
          const dLat = last[0] - first[0];
          const dLng = last[1] - first[1];
          // Only use smoothed bearing if we have meaningful displacement (>1m)
          if (Math.abs(dLat) > 0.0001 || Math.abs(dLng) > 0.0001) {
            currentForwardBearing = Math.atan2(dLng, dLat) * 180 / Math.PI;
            if (currentForwardBearing < 0) currentForwardBearing += 360;
          }
        }
      }
      // Fallback to prev→cur if window calculation didn't work
      if (currentForwardBearing === orientation) {
        const prevParts = previousLocation.split(',').map(Number);
        const dLat = currentParts[0] - prevParts[0];
        const dLng = currentParts[1] - prevParts[1];
        currentForwardBearing = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (currentForwardBearing < 0) currentForwardBearing += 360;
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🧭 COMMITTED DIRECTION: Apply hysteresis to prevent oscillation
    // Only update committed direction when bearing differs by >45°
    // This prevents micro-adjustments on straight roads
    // EXCEPTION: When justArrived, always update to current movement bearing
    // ═══════════════════════════════════════════════════════════
    if (committedDirection === null) {
      committedDirection = currentForwardBearing;
    } else if (justArrived && !isNewNode) {
      // Just moved successfully - update committed direction to match actual movement
      committedDirection = currentForwardBearing;
    } else {
      const committedDiff = yawDifference(committedDirection, currentForwardBearing);
      if (committedDiff > 45) {
        // Significant direction change - update committed direction
        committedDirection = currentForwardBearing;
      }
      // Otherwise, keep using committed direction (ignore minor bearing changes)
    }

    // Use committedDirection for decision making (not raw currentForwardBearing)
    const effectiveBearing = committedDirection;

    // ═══════════════════════════════════════════════════════════
    // 🆕 NEW NODE: Face forward bearing, go straight
    // ═══════════════════════════════════════════════════════════
    if (isNewNode) {
      // ═══════════════════════════════════════════════════════════
      // 🧭 CAMERA ALIGNMENT: Keep camera aligned with direction
      // Reduced threshold from 60° to 40° for better curve tracking
      // This prevents large corrective turns later (e.g., 78° at node 26)
      // ═══════════════════════════════════════════════════════════
      const bearingDiff = yawDifference(orientation, effectiveBearing);
      if (bearingDiff > 40 && bearingDiff < 150) {
        console.log(`🧭 NEW NODE: Aligning camera to effective bearing ${Math.round(effectiveBearing)}° (diff=${Math.round(bearingDiff)}°)`);
        const turnAngle = getLeftTurnAngle(orientation, effectiveBearing);
        const turnDirection = getTurnDirection(orientation, effectiveBearing);
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }

      // Note: Perpendicular scan removed - wall-follow already catches missed branches
      // Scans were causing wasted turns on straight roads (e.g., 6° micro-turns)

      // ═══════════════════════════════════════════════════════════
      // 🚫 SKIP YAW BUCKET ALIGNMENT ON STRAIGHT ROADS
      // If 3+ consecutive straight moves, don't micro-adjust to yaw buckets
      // Only turn if truly blocked or at a new junction
      // ═══════════════════════════════════════════════════════════
      if (consecutiveStraightMoves >= 3) {
        // Already committed to a direction, keep going straight
        // Only turn if this is a fresh node with no tried yaws
        if (currentNode.triedYaws.size === 0) {
          // First time here, might need to align
        } else {
          // Been going straight, don't micro-adjust
          consecutiveStraightMoves++;
          lastDecisionWasTurn = false;
          return { turn: false };
        }
      }

      console.log('[DEBUG] NEW NODE - going straight (no turn)');

      // Track consecutive straight moves
      if (!lastDecisionWasTurn) {
        consecutiveStraightMoves++;
        if (linearSegmentStart === null) {
          linearSegmentStart = previousLocation || currentLocation;
        }
      } else {
        consecutiveStraightMoves = 1;
        linearSegmentStart = previousLocation || currentLocation;
      }

      lastDecisionWasTurn = false;
      return { turn: false };
    }

    // ═══════════════════════════════════════════════════════════
    // 🧱 DEAD END DETECTION: All yaws tried → TURN LEFT 105°
    // This is the END OF STRAIGHT LINE - start wall-following
    // ═══════════════════════════════════════════════════════════
    const isExhausted = !currentNode.hasUntriedYaws();
    const isDeadEnd = isExhausted && currentNode.isFullyExplored;

    if (isDeadEnd && !wallFollowMode) {
      wallFollowMode = true;
      forwardBearing = currentForwardBearing;
      // Turn 105° LEFT from forward direction (face left wall, slightly back)
      // Reduced from 120° to 105° to better catch side entrances during backtrack
      wallFollowBearing = (forwardBearing + 105) % 360;
      console.log(`🧱 DEAD END! Forward bearing=${Math.round(forwardBearing)}°, turning to wall-follow bearing=${Math.round(wallFollowBearing)}°`);
    }

    // ═══════════════════════════════════════════════════════════
    // 🔄 WALL-FOLLOW MODE: Scan for LEFT exits ONLY (90-180° from forward)
    // Pure PLEDGE: Only check left side, never right side or forward
    // ═══════════════════════════════════════════════════════════
    if (wallFollowMode && currentNode.hasUntriedYaws()) {
      const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !currentNode.triedYaws.has(y));

      // Find leftmost untried yaw (90-180° LEFT from forward bearing)
      // ONLY consider LEFT exits - no fallback to forward/right yaws!
      let bestYaw = null;
      let bestDiff = 90;

      for (const yaw of untriedYaws) {
        const diff = yawDifference(forwardBearing, yaw);
        if (diff >= 90 && diff <= 180 && diff > bestDiff) {
          bestDiff = diff;
          bestYaw = yaw;
        }
      }

      // Found left exit! Take it and resume FORWARD mode
      if (bestYaw !== null) {
        console.log(`🧱 WALL-FOLLOW: Found LEFT exit yaw ${bestYaw}° (diff=${Math.round(bestDiff)}° from forward)`);
        const turnAngle = getLeftTurnAngle(orientation, bestYaw);
        const turnDirection = getTurnDirection(orientation, bestYaw);
        wallFollowMode = false;
        wallFollowBearing = null;
        forwardBearing = null;
        committedDirection = null;  // Reset committed direction for new forward phase
        consecutiveStraightMoves = 0;
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }
      // No LEFT exit found - continue backtracking (don't try forward/right yaws!)
    }

    // In wall-follow mode: face wall-follow bearing and move
    // During backtracking, just go back where we came from (reverse direction)
    // Don't try other yaws - just press ArrowUp to continue backtracking!
    if (wallFollowMode && wallFollowBearing !== null) {
      // Face the wall-follow bearing (backtracking direction)
      const diff = yawDifference(orientation, wallFollowBearing);
      if (diff > 10) {
        console.log(`🧱 WALL-FOLLOW: Turning to face bearing ${Math.round(wallFollowBearing)}° (diff=${Math.round(diff)}°)`);
        const turnAngle = getLeftTurnAngle(orientation, wallFollowBearing);
        const turnDirection = getTurnDirection(orientation, wallFollowBearing);
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }
      // Facing correct direction - check if we're actually stuck
      // If all yaws tried (including backtracking direction), fall through to BREAK_WALL
      if (isExhausted) {
        console.log(`🧱 WALL-FOLLOW: All yaws exhausted at dead end - breaking wall to escape!`);
        // Fall through to BREAK_WALL logic below
      } else {
        // Still have untried yaws - just press ArrowUp to continue backtracking
        console.log(`🧱 WALL-FOLLOW: Backtracking (press ArrowUp)`);
        return { turn: false };
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🔥 DEAD POCKET DETECTION: Check if ALL neighbors are fully explored
    // If so, we're trapped in an exhausted component
    // After 3 detections, RESTART with fresh graph
    // ═══════════════════════════════════════════════════════════
    if (isExhausted && currentNode.successfulYaws.size > 0) {
      const neighbors = enhancedGraph.connections.get(currentLocation);
      if (neighbors && neighbors.size > 0) {
        let allNeighborsDead = true;
        for (const neighbor of neighbors) {
          const neighborNode = enhancedGraph.get(neighbor);
          if (neighborNode && !neighborNode.isFullyExplored) {
            allNeighborsDead = false;
            break;
          }
        }

        if (allNeighborsDead) {
          deadPocketCount++;
          console.log(`🔥 DEAD POCKET DETECTED! All ${neighbors.size} neighbors fully explored (${deadPocketCount}/3)`);

          if (deadPocketCount >= 3) {
            console.log(`🔥 DEAD POCKET ESCAPE: Component exhausted! RESTARTING exploration...`);
            console.log(`   Clearing graph memory to find new territory...`);

            // Clear the graph - start fresh
            enhancedGraph.nodes.clear();
            enhancedGraph.connections.clear();

            // Reset PLEDGE state
            wallFollowMode = false;
            wallFollowBearing = null;
            forwardBearing = null;
            deadPocketCount = 0;
            committedDirection = null;
            consecutiveStraightMoves = 0;

            console.log(`   ✅ Graph cleared! Next move will start fresh exploration`);

            // Force a random yaw to break out
            const randomYaw = [0, 60, 120, 180, 240, 300][Math.floor(Math.random() * 6)];
            const turnAngle = getLeftTurnAngle(orientation, randomYaw);
            const turnDirection = getTurnDirection(orientation, randomYaw);
            return { turn: true, angle: turnAngle, direction: turnDirection };
          }
        }
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🚨 BREAK THE WALL: When truly stuck (retry successful yaw)
    // Used when:
    // 1. FORWARD mode: all yaws exhausted, escape Street View jitter
    // 2. WALL-FOLLOW mode: stuck at dead end with no backtracking exit
    // ═══════════════════════════════════════════════════════════
    if (isExhausted && currentNode.successfulYaws.size > 0) {
      const successfulYawsArray = Array.from(currentNode.successfulYaws);
      const randomSuccessfulYaw = successfulYawsArray[Math.floor(Math.random() * successfulYawsArray.length)];
      console.log(`🚨 BREAK WALL: All yaws exhausted! Retrying successful yaw ${randomSuccessfulYaw}°`);
      const turnAngle = getLeftTurnAngle(orientation, randomSuccessfulYaw);
      const turnDirection = getTurnDirection(orientation, randomSuccessfulYaw);
      consecutiveStraightMoves = 0;
      lastDecisionWasTurn = true;
      wallFollowMode = false;
      wallFollowBearing = null;
      forwardBearing = null;
      return { turn: true, angle: turnAngle, direction: turnDirection };
    }

    // ═══════════════════════════════════════════════════════════
    // 🚨 FALLBACK: successfulYaws is empty but we must have gotten in somehow
    // Use graph connections to find where we came from and try reverse yaw
    // This is the ultimate escape - graph remembers connections even if successfulYaws doesn't
    // ═══════════════════════════════════════════════════════════
    if (isExhausted && currentNode.successfulYaws.size === 0) {
      const neighbors = enhancedGraph.connections.get(currentLocation);
      if (neighbors && neighbors.size > 0) {
        // Get the most recent neighbor (where we likely came from)
        const neighborLoc = Array.from(neighbors)[0];
        // Calculate yaw FROM current TO neighbor (reverse direction - where we came from)
        const currentParts = currentLocation.split(',').map(Number);
        const neighborParts = neighborLoc.split(',').map(Number);
        const dLat = neighborParts[0] - currentParts[0];  // TO neighbor
        const dLng = neighborParts[1] - currentParts[1];
        let reverseYaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (reverseYaw < 0) reverseYaw += 360;
        reverseYaw = Math.round(reverseYaw);

        console.log(`🚨 BREAK WALL: No successfulYaws, using reverse yaw ${reverseYaw}° from graph`);
        const turnAngle = getLeftTurnAngle(orientation, reverseYaw);
        const turnDirection = getTurnDirection(orientation, reverseYaw);
        consecutiveStraightMoves = 0;
        lastDecisionWasTurn = true;
        wallFollowMode = false;
        wallFollowBearing = null;
        forwardBearing = null;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }
      // No graph connections either - try any yaw as last resort
      console.log(`🚨 BREAK WALL: No graph connections, trying random yaw`);
      const randomYaw = [0, 60, 120, 180, 240, 300][Math.floor(Math.random() * 6)];
      const turnAngle = getLeftTurnAngle(orientation, randomYaw);
      const turnDirection = getTurnDirection(orientation, randomYaw);
      return { turn: true, angle: turnAngle, direction: turnDirection };
    }

    // ═══════════════════════════════════════════════════════════
    // FORWARD MODE: At node with untried yaws - try them
    // Pick untried yaw closest to effective bearing (committed direction)
    // If stuck (stuckCount >= 1), try ANY untried yaw regardless of angle
    // Otherwise only turn if reasonable (<90°) to avoid massive realignments
    // ═══════════════════════════════════════════════════════════
    if (currentNode.hasUntriedYaws()) {
      const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !currentNode.triedYaws.has(y));

      // If stuck, try first untried yaw immediately (no angle checks)
      if (stuckCount >= 1) {
        const nextYaw = untriedYaws[0];
        const turnAngle = getLeftTurnAngle(orientation, nextYaw);
        const turnDirection = getTurnDirection(orientation, nextYaw);
        console.log(`🔍 STUCK! Trying untried yaw ${nextYaw}° (turn ${Math.round(turnAngle)}° ${turnDirection})`);
        consecutiveStraightMoves = 0;
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }

      // Not stuck - find untried yaw closest to EFFECTIVE BEARING
      let bestUntiredYaw = null;
      let bestDiff = Infinity;

      for (const yaw of untriedYaws) {
        const diffToForward = yawDifference(effectiveBearing, yaw);
        if (diffToForward < bestDiff) {
          bestDiff = diffToForward;
          bestUntiredYaw = yaw;
        }
      }

      const nextYaw = bestUntiredYaw;
      if (nextYaw !== null) {
        // ═══════════════════════════════════════════════════════════
        // 🎯 YAW ALIGNMENT: Only turn if angle is reasonable (<90°)
        // Prevents massive realignments that waste time and cause stuck detection
        // Also use ±20° tolerance to avoid micro-adjustments
        // ═══════════════════════════════════════════════════════════
        const diff = yawDifference(orientation, nextYaw);
        if (diff > 20 && diff < 90) {
          console.log(`🔍 FORWARD: Trying yaw ${nextYaw}° (diff=${Math.round(diff)}° from orientation, ${Math.round(bestDiff)}° from effective bearing)`);
          const turnAngle = getLeftTurnAngle(orientation, nextYaw);
          const turnDirection = getTurnDirection(orientation, nextYaw);
          consecutiveStraightMoves = 0;
          lastDecisionWasTurn = true;
          linearSegmentStart = null;
          return { turn: true, angle: turnAngle, direction: turnDirection };
        } else if (diff <= 20) {
          console.log('[DEBUG] Already facing target yaw (within ±20° tolerance), moving forward');
          return { turn: false };
        } else {
          // Turn too large (>90°) - don't realign, just go straight
          console.log(`[DEBUG] Skipping yaw ${nextYaw}° alignment - turn too large (${Math.round(diff)}° > 90°)`);
          return { turn: false };
        }
      }
    }

    // ═══════════════════════════════════════════════════════════
    // FALLBACK: Retry successful exit
    // ═══════════════════════════════════════════════════════════
    if (currentNode.successfulYaws.size > 0) {
      const successfulYawsArray = Array.from(currentNode.successfulYaws);
      const randomSuccessfulYaw = successfulYawsArray[Math.floor(Math.random() * successfulYawsArray.length)];
      const diff = yawDifference(orientation, randomSuccessfulYaw);
      if (diff > 5 && diff < 355) {
        const turnAngle = getLeftTurnAngle(orientation, randomSuccessfulYaw);
        consecutiveStraightMoves = 0;
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: getTurnDirection(orientation, randomSuccessfulYaw) };
      }
      return { turn: false };
    }

    // ═══════════════════════════════════════════════════════════
    // FORWARD MODE: Go straight (no turn)
    // ═══════════════════════════════════════════════════════════
    console.log('[DEBUG] FORWARD MODE: Going straight (no turn)');
    return { turn: false };
  };

  // Helper function for getNextUntriedYaw
  function getNextUntriedYaw(node, currentOrientation) {
    if (!node.hasUntriedYaws()) return null;

    const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !node.triedYaws.has(y));
    if (untriedYaws.length === 0) return null;

    if (currentOrientation === null) {
      return untriedYaws[0];
    }

    let closestYaw = untriedYaws[0];
    let closestDiff = yawDifference(currentOrientation, closestYaw);

    for (const yaw of untriedYaws) {
      const diff = yawDifference(currentOrientation, yaw);
      if (diff < closestDiff) {
        closestDiff = diff;
        closestYaw = yaw;
      }
    }

    return closestYaw;
  }

  /**
   * Determine optimal turn direction (left or right)
   */
  function getTurnDirection(currentYaw, targetYaw) {
    const leftAngle = getLeftTurnAngle(currentYaw, targetYaw);
    const rightAngle = (360 - leftAngle) % 360;
    return rightAngle < leftAngle ? 'right' : 'left';
  }

  return {
    decide,
    enhancedGraph,
    isReturning: () => false,  // PLEDGE doesn't have return mode
    getNavigationTarget: () => null
  };
}

const createDefaultAlgorithm = createUnifiedAlgorithm;
const createExplorationAlgorithm = createUnifiedAlgorithm;
const createSurgicalAlgorithm = createUnifiedAlgorithm;
const createHunterAlgorithm = createUnifiedAlgorithm;


  // === NAVIGATION COMPATIBILITY LAYER ===
  /**
 * Navigation Strategies - Compatibility Wrapper for v4.0.0+
 * This file maintains the old API for tests and bundle validation
 * but uses the new Traversal/Wheel architecture.
 */

function createProactiveAvoidance(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeProactiveAvoidance: (yaw, loc, visited) => {
      const result = algorithm.decide({ stuckCount: 0, currentLocation: loc, visitedUrls: visited, orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createUnstuckNavigation(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeUnstuck: (stuckCount, panicThreshold, yaw) => {
      const result = algorithm.decide({ stuckCount, currentLocation: '', visitedUrls: new Set(), orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createNavigationController(cfg, callbacks) {
  return {
    tick: () => ({ action: 'move', strategy: 'normal', busy: false }),
    getCumulativeTurnAngle: () => 0,
    resetCumulativeTurnAngle: () => {},
    reset: () => {},
    getState: () => ({ globalOrientation: 0, proactive: { state: 'IDLE' }, unstuck: { state: 'IDLE' } })
  };
}

const __default_export = {
  createProactiveAvoidance,
  createUnstuckNavigation,
  createNavigationController
};


  // === CORE ENGINE ===
  /**
 * Drunk Walker Core Engine v6.1.4
 *
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording
 * - Wheel: Orientation management
 * - Traversal: Decision-making with PLEDGE wall-following
 */

const __export_dummy = { VERSION };

const defaultConfig = {
  pace: 2000,
  kbOn: true,
  panicThreshold: 3,
  radius: 50,
  targetX: 0.4,
  targetY: 0.8,
  turnDuration: 600,
  collectPath: true,
  selfAvoiding: true
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = null;
  let lastUrlYaw = null;
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;

  // Path collection
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;

  // Visited nodes memory
  let visitedUrls = new Map();
  let breadcrumbs = [];

  // Track previous location for movement recording
  let previousLocation = null;
  let previousYaw = null;
  let lastDifferentLocation = null;  // Track last location that was different from current

  // Turn state - prevent oscillation
  let isTurning = false;  // True while executing a turn
  let turnCompleted = false;  // Set to true when turn finishes
  let ticksSinceTurn = 0;  // Count ticks after turn completes
  const TURNS_COOLDOWN_TICKS = 2;  // Wait 2 ticks after turn before deciding to turn again (reduced from 3)
  let awaitingStepResult = false;  // True after turn+step, waiting to see if we moved

  // Action callbacks
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  const extractLocation = (url) => {
    try {
      const hashMatch = url.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (hashMatch) return `${hashMatch[1]},${hashMatch[2]}`;
    } catch (e) {}
    return null;
  };

  const extractYaw = (url) => {
    if (!url) return null;
    // Match both &yaw=123 and 75y,123h formats
    const match = url.match(/yaw[=%]3D?([0-9.]+)/i) || url.match(/,([0-9.]+)h/i);
    return match ? parseFloat(match[1]) : null;
  };

  const wheelCallbacks = {
    onLongKeyPress: null
  };
  const wheel = createWheel(wheelCallbacks);

  let algorithm = createDefaultAlgorithm(cfg);

  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  const setPace = (newPace) => {
    cfg.pace = newPace;
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setPolygon = (newPoly) => { poly = newPoly || []; };
  const setPathCollection = (enabled) => { isPathCollectionEnabled = enabled; };
  const setWalkPath = (path) => { walkPath = path || []; };
  const setSteps = (newSteps) => { steps = newSteps; };
  const getWalkPath = () => walkPath;
  const clearWalkPath = () => { walkPath = []; };
  const getVisitedCount = () => visitedUrls.size;
  const clearVisitedUrls = () => { visitedUrls.clear(); breadcrumbs = []; };
  const isUrlVisited = (url) => visitedUrls.has(extractLocation(url));
  const getCurrentYaw = () => wheel.getOrientation();
  const resetCurrentYaw = () => wheel.setOrientation(0);
  let cumulativeTurnAngle = 0;
  const getCumulativeTurnAngle = () => cumulativeTurnAngle;
  const resetCumulativeTurnAngle = () => { cumulativeTurnAngle = 0; };

  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    breadcrumbs = [];
    for (const step of path) {
      const loc = extractLocation(step.url);
      if (loc) {
        visitedUrls.set(loc, (visitedUrls.get(loc) || 0) + 1);
        breadcrumbs.push(loc);
      }
    }
  };

  const setUserMouseDown = (val) => { isUserMouseDown = val; };
  const setIsDrawing = (val) => { isDrawing = val; };
  const setActionHandlers = (handlers) => {
    onKeyPress = handlers.keyPress || null;
    onMouseClick = handlers.mouseClick || null;
    onStatusUpdate = handlers.statusUpdate || null;
    onLongKeyPress = handlers.longKeyPress || null;
    onWalkStop = handlers.walkStop || null;

    // Update persistent wheel callbacks
    wheelCallbacks.onLongKeyPress = onLongKeyPress;
  };

  const recordStep = () => {
    if (!isPathCollectionEnabled) return;
    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    const currentLocation = extractLocation(currentUrl);
    walkPath.push({ url: currentUrl, timestamp: Date.now() });
    if (currentLocation) {
      visitedUrls.set(currentLocation, (visitedUrls.get(currentLocation) || 0) + 1);
      if (breadcrumbs.length === 0 || breadcrumbs[breadcrumbs.length - 1] !== currentLocation) {
        breadcrumbs.push(currentLocation);
      }
      if (breadcrumbs.length > 200) breadcrumbs.shift();  // Keep last 200 for loop detection
    }
  };

  const calculateClickTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1920;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1080;
    const tx = cfg.targetX * cw;
    const ty = cfg.targetY * ch;
    return { x: tx, y: ty };
  };

  const calculateTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1920;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1080;

    if (poly.length > 0 && isDrawing) {
      const last = poly[poly.length - 1];
      return { x: last.x * cw, y: last.y * ch };
    }

    const radius = stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  const tick = () => {
    console.log(`[DEBUG] tick() START - status=${status}, isUserMouseDown=${isUserMouseDown}, isDrawing=${isDrawing}`);

    if (isUserMouseDown || isDrawing || status !== 'WALKING') {
      console.log('[DEBUG] tick() SKIP - conditions not met');
      return;
    }

    // Increment ticks since turn (for cooldown - prevent rapid re-turning)
    if (ticksSinceTurn < TURNS_COOLDOWN_TICKS + 1) {
      ticksSinceTurn++;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : (lastUrl || '');
    const currentLocation = extractLocation(currentUrl);
    const currentYaw = extractYaw(currentUrl);

    console.log(`[DEBUG] currentUrl=${currentUrl.substring(0, 80)}...`);
    console.log(`[DEBUG] currentLocation=${currentLocation}, currentYaw=${currentYaw}, previousLocation=${previousLocation}`);

    // 1. Stuck detection (Location based heartbeat)
    if (currentLocation && previousLocation && currentLocation === previousLocation) {
      stuckCount++;
      console.log(`[DEBUG] STUCK DETECTED - same location, stuckCount=${stuckCount}`);
    } else if (currentLocation && previousLocation && currentLocation !== previousLocation) {
      console.log(`[DEBUG] LOCATION CHANGED - resetting stuckCount and turn cooldown`);
      stuckCount = 0;
      ticksSinceTurn = TURNS_COOLDOWN_TICKS;  // Reset cooldown - we moved successfully
      // Track that we just arrived at a different location
      if (currentLocation !== lastDifferentLocation) {
        lastDifferentLocation = currentLocation;
      }
    }

    // 2. Sync orientation with URL ONLY if it changed since last heartbeat
    // Use 1 degree threshold to ignore minor floating point jitter
    if (currentYaw !== null && (lastUrlYaw === null || Math.abs(currentYaw - lastUrlYaw) > 1.0)) {
      console.log(`[DEBUG] Sync wheel orientation: lastUrlYaw=${lastUrlYaw}, currentYaw=${currentYaw}`);
      wheel.setOrientation(currentYaw);
      lastUrlYaw = currentYaw;
    }

    // 3. LOGGING (Critical for debugging)
    console.log(`💓 [${steps}] STUCK: ${stuckCount} | YAW: ${Math.round(wheel.getOrientation())}° | LOC: ${currentLocation}`);
    console.log(`   🔗 ${currentUrl}`);

    // 4. Record result of PREVIOUS heartbeat in the graph
    if (previousLocation && algorithm.enhancedGraph) {
      if (currentLocation && currentLocation !== previousLocation) {
        algorithm.enhancedGraph.recordMovement(
          previousLocation,
          currentLocation,
          previousYaw !== null ? previousYaw : wheel.getOrientation(),
          currentYaw || wheel.getOrientation(),
          steps
        );
      } else if (currentLocation === previousLocation) {
        // We are still at the same spot after an ArrowUp press
        algorithm.enhancedGraph.recordFailedAttempt(
          previousLocation,
          previousYaw !== null ? previousYaw : wheel.getOrientation(),
          steps
        );
      }
    }

    // 5. Decision time
    // Check if this is a new node or already visited
    const nodeVisitCount = visitedUrls.get(currentLocation) || 0;
    const isNewNode = nodeVisitCount === 0;
    const isStationary = currentLocation && previousLocation && currentLocation === previousLocation;

    // Track if we just arrived at this location (first tick after movement)
    const justArrived = currentLocation && previousLocation && currentLocation !== previousLocation;

    // Get node info from graph to check if fully scanned
    const nodeInfo = currentLocation ? algorithm.enhancedGraph.get(currentLocation) : null;
    const isFullyScanned = nodeInfo ? nodeInfo.triedYaws.size >= 6 : false;

    console.log(`[DEBUG] isStationary=${isStationary}, isNewNode=${isNewNode}, justArrived=${justArrived}, nodeVisitCount=${nodeVisitCount}, isFullyScanned=${isFullyScanned}`);

    // Check step result from previous turn+step attempt
    if (awaitingStepResult) {
      if (currentLocation !== previousLocation) {
        console.log('[DEBUG] Step succeeded! Location changed.');
      } else {
        console.log('[DEBUG] Step failed! Still at same location - record failed attempt.');
      }
      awaitingStepResult = false;  // Now we can make new decisions
    }

    let decision = { turn: false };

    // Make turn decisions when:
    // 1. Stationary at a node (not mid-movement) - normal case
    // 2. Just arrived at ANY node (new or visited) - allow yaw correction
    // But NOT when:
    // - Already turning
    // - Waiting for step result
    // - Turn cooldown active (UNLESS stuck >= 2, then skip cooldown for fast-fail)
    const isStuckAndShouldSkipCooldown = stuckCount >= 2;  // Fast-fail when clearly blocked
    const shouldMakeDecision = !isTurning && !awaitingStepResult &&
      (ticksSinceTurn >= TURNS_COOLDOWN_TICKS || isStuckAndShouldSkipCooldown) &&
      (isStationary || justArrived);

    if (shouldMakeDecision) {
      const context = {
        url: currentUrl,
        currentLocation: currentLocation,
        previousLocation: previousLocation,  // For yaw correction at new nodes
        visitedUrls,
        breadcrumbs,
        stuckCount,
        orientation: wheel.getOrientation(),
        isNewNode,
        isFullyScanned,
        justArrived,
        nodeVisitCount
      };

      console.log(`[DEBUG] ticksSinceTurn=${ticksSinceTurn}, calling algorithm.decide()...`);
      decision = algorithm.decide(context);
      console.log(`[DEBUG] decision=${JSON.stringify(decision)}`);
    } else if (isTurning) {
      console.log('[DEBUG] Skipping decision - already turning');
    } else if (!isStationary && !isNewNode) {
      console.log('[DEBUG] Skipping decision - moving through visited node');
    } else if (ticksSinceTurn < TURNS_COOLDOWN_TICKS && !isStuckAndShouldSkipCooldown) {
      console.log(`[DEBUG] Skipping decision - turn cooldown active (${ticksSinceTurn}/${TURNS_COOLDOWN_TICKS})`);
    } else if (isStuckAndShouldSkipCooldown) {
      console.log(`[DEBUG] FAST-FAIL: Skipping cooldown - stuck ${stuckCount}x, making decision immediately`);
    }

    // 6. Action: Turn (Left or Right)
    if (decision.turn) {
      let angle = decision.angle || 60;
      const direction = decision.direction || 'left';  // 'left' or 'right'

      // If direction is 'right', convert left-angle to right-angle
      // getLeftTurnAngle returns counter-clockwise angle
      // For clockwise (right) turn: rightAngle = 360 - leftAngle
      if (direction === 'right') {
        angle = (360 - angle) % 360;
      }

      console.log(`   🔄 ACTION: Turning ${direction.toUpperCase()} ${Math.round(angle)}°`);
      isTurning = true;
      turnCompleted = false;

      // Skip stepping when turning - let the turn complete first
      previousYaw = wheel.getOrientation();

      const turnCallback = () => {
        console.log('[DEBUG] Turn callback executed - pressing ArrowUp');
        isTurning = false;
        turnCompleted = true;
        ticksSinceTurn = 0;  // Reset cooldown - turn just completed
        awaitingStepResult = true;  // Wait for next tick to see if we moved

        // After turn completes, update state and trigger next tick
        previousLocation = currentLocation;
        previousYaw = wheel.getOrientation();
        lastUrl = currentUrl;
        steps++;
        recordStep();
        if (onStatusUpdate) {
          onStatusUpdate(status, steps, stuckCount);
        }
        // Trigger immediate step after turn completes
        if (cfg.kbOn) {
          if (onKeyPress) onKeyPress('ArrowUp');
        } else {
          const target = calculateClickTarget();
          if (onMouseClick) onMouseClick(target.x, target.y);
        }
      };

      if (direction === 'right') {
        wheel.turnRight(angle, turnCallback);
      } else {
        wheel.turnLeft(angle, turnCallback);
      }

      cumulativeTurnAngle += angle;
      console.log('[DEBUG] tick() RETURN EARLY - waiting for turn to complete');
      return; // Exit tick early - don't step until turn completes
    }

    // 7. Action: Always Step (The Heartbeat)
    previousLocation = currentLocation;
    previousYaw = wheel.getOrientation();
    lastUrl = currentUrl;

    // Normal movement (keyboard or mouse)
    if (cfg.kbOn) {
      if (onKeyPress) onKeyPress('ArrowUp');
    } else {
      const target = calculateClickTarget();
      if (onMouseClick) onMouseClick(target.x, target.y);
    }

    steps++;
    recordStep();

    if (onStatusUpdate) {
      onStatusUpdate(status, steps, stuckCount);
    }
    console.log('[DEBUG] tick() END');
  };

  const start = () => {
    console.log(`[DEBUG] start() called - current status=${status}, intervalId=${intervalId ? 'set' : 'null'}`);

    // Aggressively clear any existing interval
    if (intervalId) {
      console.log('[DEBUG] start() clearing existing interval before start');
      clearInterval(intervalId);
      // Remove from global tracking
      if (window.__DRUNK_WALKER_INTERVALS__) {
        window.__DRUNK_WALKER_INTERVALS__.delete(intervalId);
      }
      intervalId = null;
    }

    if (status === 'WALKING') {
      console.log('[DEBUG] start() ABORT - already walking');
      return;
    }
    status = 'WALKING';

    // Reset everything for fresh start (new session)
    steps = 0;
    stuckCount = 0;
    lastUrl = null;
    previousLocation = null;
    previousYaw = null;
    lastDifferentLocation = null;
    walkPath = [];
    visitedUrls.clear();
    breadcrumbs = [];

    // Reset algorithm state (clear graph for fresh exploration)
    algorithm.enhancedGraph.nodes.clear();
    algorithm.enhancedGraph.connections.clear();
    if (algorithm.decide.toString().includes('wallFollowMode')) {
      // Reset PLEDGE state if using PLEDGE algorithm
      // This is handled by createUnifiedAlgorithm closure
    }

    // Reset wheel orientation
    wheel.reset();
    intervalId = setInterval(tick, cfg.pace);
    // Track interval globally
    if (window.__DRUNK_WALKER_INTERVALS__) {
      window.__DRUNK_WALKER_INTERVALS__.add(intervalId);
    }
    console.log(`[DEBUG] start() interval set with pace=${cfg.pace}ms`);
    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      // Remove from global tracking
      if (window.__DRUNK_WALKER_INTERVALS__) {
        window.__DRUNK_WALKER_INTERVALS__.delete(intervalId);
      }
      intervalId = null;
    }
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }
    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = null;
    status = 'IDLE';
    wheel.reset();
    previousLocation = null;
    previousYaw = null;
  };

  return {
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,
    getVisitedUrls: () => visitedUrls,
    getCurrentYaw,
    resetCurrentYaw,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    restoreVisitedFromPath,
    setUserMouseDown,
    setIsDrawing,
    setActionHandlers,
    start,
    stop,
    reset,
    tick,
    getConfig: () => ({ ...cfg }),
    getNavigation: () => null,
    getNavigationState: () => ({}),
    setAlgorithm: (newAlgorithm) => { algorithm = newAlgorithm; }
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */

const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};

/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}

/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 0,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Full key event sequence
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}

/**
 * Simulate long-press keyboard event (repeated keydown/keypress)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const baseOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();
  const startTime = Date.now();

  // Initial Key Down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', { ...baseOptions, repeat: false }));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', { ...baseOptions, repeat: false }));

  // Repeat loop
  const intervalId = setInterval(() => {
    if (Date.now() - startTime >= duration) {
      clearInterval(intervalId);
      targetEl.dispatchEvent(new KeyboardEvent('keyup', { ...baseOptions, repeat: false }));
      if (callback) callback();
    } else {
      // Repeat events
      targetEl.dispatchEvent(new KeyboardEvent('keydown', { ...baseOptions, repeat: true }));
      targetEl.dispatchEvent(new KeyboardEvent('keypress', { ...baseOptions, repeat: true }));
    }
  }, 50); // Repeat every 50ms (typical browser repeat rate)
}

/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };

  const target = document.elementFromPoint(x, y) || document.body;

  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));

  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}

/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;

  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };

  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };

  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);

  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}


  // === EXPLORATION MAP ===
  /**
 * Exploration Map Component
 * Renders a mini-map showing explored territory from walker's perspective
 * v6.0.0-CYBERPUNK
 */

function createExplorationMap() {
  let canvas = null;
  let ctx = null;
  let container = null;
  let isVisible = false;
  let isExpanded = false;

  // Map state
  let centerLat = 0;
  let centerLng = 0;
  let zoom = 1;
  const baseZoom = 0.0001; // meters per pixel

  // Styles
  const CSS = {
    container: `
      position: fixed;
      bottom: 20px;
      left: 50%;
      transform: translateX(-50%);
      background: rgba(18, 18, 20, 0.85);
      backdrop-filter: blur(20px) saturate(180%);
      -webkit-backdrop-filter: blur(20px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 12px;
      padding: 12px;
      z-index: 999998;
      display: none;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
      font-size: 11px;
      color: #fff;
      box-shadow: 0 20px 40px -10px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(0, 0, 0, 0.3);
      min-width: 320px;
      transition: all 0.3s cubic-bezier(0.2, 0.8, 0.2, 1);
    `,
    header: `
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
      padding: 0 4px;
    `,
    title: `
      font-weight: 700;
      color: #fff;
      letter-spacing: -0.3px;
      display: flex;
      align-items: center;
      gap: 6px;
    `,
    controls: `
      display: flex; 
      gap: 6px;
    `,
    btn: `
      background: rgba(255, 255, 255, 0.05);
      border: 1px solid rgba(255, 255, 255, 0.1);
      color: rgba(255, 255, 255, 0.7);
      width: 24px;
      height: 24px;
      cursor: pointer;
      border-radius: 6px;
      font-size: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s;
    `,
    statsBar: `
      display: flex;
      gap: 16px;
      padding: 8px 12px;
      background: rgba(0, 0, 0, 0.3);
      border-radius: 8px;
      margin-bottom: 10px;
      font-size: 10px;
      border: 1px solid rgba(255, 255, 255, 0.05);
    `,
    statItem: `
      display: flex;
      align-items: center;
      gap: 6px;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.6);
    `,
    canvasContainer: `
      position: relative;
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 8px;
      overflow: hidden;
      background: #000;
    `
  };

  function init() {
    container = document.createElement('div');
    container.id = 'dw-map-container';
    container.style.cssText = CSS.container;

    // Header
    const header = document.createElement('div');
    header.style.cssText = CSS.header;

    const title = document.createElement('span');
    title.innerHTML = '<span>🗺️</span> EXPLORATION MAP';
    title.style.cssText = CSS.title;

    const controls = document.createElement('div');
    controls.style.cssText = CSS.controls;

    const expandBtn = document.createElement('button');
    expandBtn.innerHTML = '⛶';
    expandBtn.title = 'Expand/Collapse';
    expandBtn.style.cssText = CSS.btn;
    expandBtn.onmouseover = () => { expandBtn.style.background = 'rgba(255,255,255,0.1)'; expandBtn.style.color = '#fff'; };
    expandBtn.onmouseout = () => { expandBtn.style.background = 'rgba(255,255,255,0.05)'; expandBtn.style.color = 'rgba(255,255,255,0.7)'; };
    expandBtn.onclick = () => toggleExpand();

    const closeBtn = document.createElement('button');
    closeBtn.innerHTML = '✕';
    closeBtn.title = 'Close (M)';
    closeBtn.style.cssText = CSS.btn;
    closeBtn.onmouseover = () => { closeBtn.style.background = 'rgba(255, 50, 50, 0.2)'; closeBtn.style.color = '#ff4d4d'; closeBtn.style.borderColor = 'rgba(255, 50, 50, 0.3)'; };
    closeBtn.onmouseout = () => { closeBtn.style.background = 'rgba(255,255,255,0.05)'; closeBtn.style.color = 'rgba(255,255,255,0.7)'; closeBtn.style.borderColor = 'rgba(255,255,255,0.1)'; };
    closeBtn.onclick = () => hide();

    controls.appendChild(expandBtn);
    controls.appendChild(closeBtn);
    header.appendChild(title);
    header.appendChild(controls);

    // Stats bar
    const statsBar = document.createElement('div');
    statsBar.id = 'dw-map-stats';
    statsBar.style.cssText = CSS.statsBar;

    const stat = (color, label, id) => `
      <div style="${CSS.statItem}">
        <span style="width:6px;height:6px;border-radius:50%;background:${color};box-shadow:0 0 6px ${color};"></span>
        <span>${label}: <strong id="${id}" style="color:#fff;">0</strong></span>
      </div>
    `;

    statsBar.innerHTML = `
      ${stat('#00ff80', 'Visited', 'dw-stat-visited')}
      ${stat('#ffb74d', 'Crossroads', 'dw-stat-crossroads')}
      ${stat('#ff4d4d', 'Dead ends', 'dw-stat-deadends')}
    `;

    // Canvas container
    const canvasContainer = document.createElement('div');
    canvasContainer.style.cssText = CSS.canvasContainer;

    canvas = document.createElement('canvas');
    canvas.width = 300;
    canvas.height = 200;
    canvas.style.cssText = 'display: block; width: 100%; height: 100%;';

    canvasContainer.appendChild(canvas);
    ctx = canvas.getContext('2d');

    container.appendChild(header);
    container.appendChild(statsBar);
    container.appendChild(canvasContainer);

    document.body.appendChild(container);

    document.addEventListener('keydown', (e) => {
      if (e.key === 'm' || e.key === 'M') {
        e.preventDefault();
        toggle();
      }
    });
  }

  function toggle() {
    if (!container) init();
    isVisible = !isVisible;
    container.style.display = isVisible ? 'block' : 'none';
    if (isVisible) render();
  }

  function show() {
    if (!container) init();
    isVisible = true;
    container.style.display = 'block';
    render();
  }

  function hide() {
    isVisible = false;
    if (container) container.style.display = 'none';
  }

  function toggleExpand() {
    isExpanded = !isExpanded;
    if (isExpanded) {
      canvas.width = 600;
      canvas.height = 400;
      container.style.minWidth = '620px';
    } else {
      canvas.width = 300;
      canvas.height = 200;
      container.style.minWidth = '320px';
    }
    render();
  }

  function gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom) {
    const scale = zoom * 10000000;
    const x = width / 2 + (lng - centerLng) * scale;
    const y = height / 2 - (lat - centerLat) * scale * 1.5;
    return { x, y };
  }

  function render(transitionGraph, currentLocation, visitedUrls) {
    if (!ctx || !canvas) return;

    const width = canvas.width;
    const height = canvas.height;

    // Clear canvas with deep space blue
    ctx.fillStyle = '#0a0a0c';
    ctx.fillRect(0, 0, width, height);

    // Grid background
    ctx.strokeStyle = '#1a1a1c';
    ctx.lineWidth = 1;
    ctx.beginPath();
    for(let x=0; x<width; x+=20) { ctx.moveTo(x,0); ctx.lineTo(x,height); }
    for(let y=0; y<height; y+=20) { ctx.moveTo(0,y); ctx.lineTo(width,y); }
    ctx.stroke();

    if (!transitionGraph) {
      ctx.fillStyle = '#444';
      ctx.font = '12px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('AWAITING TELEMETRY...', width / 2, height / 2);
      return;
    }

    const stats = transitionGraph.getStats();
    const locations = Array.from(transitionGraph.connections.keys());

    if (locations.length === 0) {
      ctx.fillStyle = '#444';
      ctx.font = '12px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('NO DATA COLLECTED', width / 2, height / 2);
      return;
    }

    let minLat = Infinity, maxLat = -Infinity;
    let minLng = Infinity, maxLng = -Infinity;

    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
      minLng = Math.min(minLng, lng);
      maxLng = Math.max(maxLng, lng);
    });

    centerLat = (minLat + maxLat) / 2;
    centerLng = (minLng + maxLng) / 2;

    const latRange = maxLat - minLat || 0.0001;
    const lngRange = maxLng - minLng || 0.0001;
    zoom = Math.min(width / lngRange / 100000, height / latRange / 100000) * 0.7;

    // Draw edges
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.1)';
    ctx.lineWidth = 1;

    locations.forEach(loc => {
      const connections = transitionGraph.getConnections(loc);
      const [lat1, lng1] = loc.split(',').map(Number);
      const pos1 = gpsToScreen(lat1, lng1, centerLat, centerLng, width, height, zoom);

      connections.forEach(conn => {
        const [lat2, lng2] = conn.split(',').map(Number);
        const pos2 = gpsToScreen(lat2, lng2, centerLat, centerLng, width, height, zoom);

        ctx.beginPath();
        ctx.moveTo(pos1.x, pos1.y);
        ctx.lineTo(pos2.x, pos2.y);
        ctx.stroke();
      });
    });

    // Draw nodes
    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      const pos = gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom);

      const isCrossroad = transitionGraph.isCrossroad(loc);
      const isCurrent = loc === currentLocation;
      const isVisited = visitedUrls ? visitedUrls.has(loc) : false;

      if (isCurrent) {
        // Pulse effect
        const pulse = (Date.now() / 1000) % 1;
        ctx.fillStyle = `rgba(0, 255, 128, ${1-pulse})`;
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 12 * pulse + 4, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#00ff80';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 4, 0, Math.PI * 2);
        ctx.fill();

        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 6, 0, Math.PI * 2);
        ctx.stroke();
      } else if (isCrossroad) {
        ctx.fillStyle = '#ffb74d';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 3, 0, Math.PI * 2);
        ctx.fill();
      } else if (isVisited) {
        ctx.fillStyle = '#00ff80';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 2, 0, Math.PI * 2);
        ctx.fill();
      } else {
        ctx.fillStyle = '#ff4d4d';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 1.5, 0, Math.PI * 2);
        ctx.fill();
      }
    });

    const deadEnds = locations.filter(loc => {
      const conns = transitionGraph.getConnections(loc);
      return conns.size === 1;
    }).length;

    document.getElementById('dw-stat-visited').textContent = locations.length;
    document.getElementById('dw-stat-crossroads').textContent = stats.crossroads || 0;
    document.getElementById('dw-stat-deadends').textContent = deadEnds;
  }

  return {
    init, toggle, show, hide, toggleExpand, render, isVisible: () => isVisible
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Compact Draggable Panel
 * v6.6.0-LOGS-FIX
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '6.6.0',
    autoStart = true,
    onPathCollectionToggle = null
  } = options;

  let container = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let startStopBtn = null;

  // Session logs storage - collect from console
  const sessionLogs = [];
  const originalConsoleLog = console.log;
  const originalConsoleWarn = console.warn;
  const originalConsoleError = console.error;

  // Hook console to capture logs
  const hookConsole = () => {
    console.log = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleLog.apply(console, args);
    };
    console.warn = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ⚠️ ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleWarn.apply(console, args);
    };
    console.error = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ❌ ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleError.apply(console, args);
    };
  };

  // Hook console immediately
  hookConsole();

  const makeDraggable = (element) => {
    let isDragging = false;
    let startX, startY, initialLeft, initialTop;

    element.addEventListener('mousedown', (e) => {
      if (e.target.tagName === 'BUTTON' || e.target.tagName === 'INPUT' || e.target.closest('button') || e.target.closest('input')) {
        return;
      }
      isDragging = true;
      startX = e.clientX;
      startY = e.clientY;
      const rect = element.getBoundingClientRect();
      initialLeft = rect.left;
      initialTop = rect.top;
      element.style.cursor = 'grabbing';
      element.style.transition = 'none';
      element.style.userSelect = 'none';
    });

    document.addEventListener('mousemove', (e) => {
      if (!isDragging) return;
      e.preventDefault();
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      element.style.left = `${initialLeft + dx}px`;
      element.style.top = `${initialTop + dy}px`;
      element.style.bottom = 'auto';
      element.style.right = 'auto';
    });

    document.addEventListener('mouseup', () => {
      if (isDragging) {
        isDragging = false;
        element.style.cursor = 'grab';
        element.style.transition = '';
        element.style.userSelect = '';
      }
    });
  };

  const createUI = () => {
    document.querySelectorAll('.dw-float-ui').forEach(el => el.remove());

    container = document.createElement('div');
    container.className = 'dw-float-ui';
    container.style.cssText = `
      position: fixed;
      bottom: 20px;
      left: 20px;
      padding: 5px;
      background: rgba(30, 30, 32, 0.95);
      backdrop-filter: blur(10px);
      -webkit-backdrop-filter: blur(10px);
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 6px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.4);
      z-index: 1000000;
      display: flex;
      flex-direction: column;
      gap: 4px;
      cursor: grab;
      user-select: none;
      -webkit-user-select: none;
    `;

    // Stats row
    const statRow = document.createElement('div');
    statRow.style.cssText = `display: flex; gap: 4px;`;
    statRow.innerHTML = `
      <div style="display:flex;flex-direction:column;align-items:center;padding:4px 6px;background:rgba(255,255,255,0.08);border-radius:4px;flex:1;min-width:0;">
        <span style="font-size:7px;color:rgba(255,255,255,0.5);text-transform:uppercase;letter-spacing:0.3px;font-weight:500;">Steps</span>
        <span id="dw-steps" style="font-size:11px;font-weight:600;color:#fff;margin-top:1px;">0</span>
      </div>
      <div style="display:flex;flex-direction:column;align-items:center;padding:4px 6px;background:rgba(255,255,255,0.08);border-radius:4px;flex:1;min-width:0;">
        <span style="font-size:7px;color:rgba(255,255,255,0.5);text-transform:uppercase;letter-spacing:0.3px;font-weight:500;">Visited</span>
        <span id="dw-visited" style="font-size:11px;font-weight:600;color:#fff;margin-top:1px;">0</span>
      </div>
    `;
    container.appendChild(statRow);
    stepsEl = statRow.querySelector('#dw-steps');
    visitedEl = statRow.querySelector('#dw-visited');

    // START/STOP button
    startStopBtn = document.createElement('button');
    startStopBtn.style.cssText = `
      width:100%;display:flex;align-items:center;justify-content:center;gap:4px;padding:5px 8px;
      background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.12);border-radius:4px;
      color:#e8eaed;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
      font-size:10px;font-weight:500;cursor:pointer;transition:all 0.1s;text-transform:none;letter-spacing:0;
    `;
    startStopBtn.innerHTML = '<span>▶</span> START';
    startStopBtn.onmouseover = () => { 
      if (!engine.isNavigating()) {
        startStopBtn.style.background = 'rgba(255,255,255,0.12)';
      }
    };
    startStopBtn.onmouseout = () => { 
      if (!engine.isNavigating()) {
        startStopBtn.style.background = 'rgba(255,255,255,0.08)';
      }
    };
    startStopBtn.onmousedown = () => {
      if (!engine.isNavigating()) {
        startStopBtn.style.background = 'rgba(255,255,255,0.15)';
      }
    };
    startStopBtn.onmouseup = () => {
      if (!engine.isNavigating()) {
        startStopBtn.style.background = 'rgba(255,255,255,0.12)';
      }
    };
    startStopBtn.onclick = (e) => {
      e.stopPropagation();
      if (engine.isNavigating()) engine.stop();
      else engine.start();
      updateStartStopBtn();
    };
    container.appendChild(startStopBtn);

    // Save Path / Save Logs row
    const saveRow = document.createElement('div');
    saveRow.style.cssText = `display: flex; gap: 4px;`;
    saveRow.innerHTML = `
      <button id="dw-save-path" style="flex:1;padding:4px 6px;font-size:9px;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.1);border-radius:4px;color:#e8eaed;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-weight:500;cursor:pointer;transition:all 0.1s;">💾 Path</button>
      <button id="dw-save-logs" style="flex:1;padding:4px 6px;font-size:9px;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.1);border-radius:4px;color:#e8eaed;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-weight:500;cursor:pointer;transition:all 0.1s;">📄 Logs</button>
    `;
    const saveButtons = saveRow.querySelectorAll('button');
    saveButtons.forEach(btn => {
      btn.onmouseover = () => {
        btn.style.background = 'rgba(255,255,255,0.1)';
      };
      btn.onmouseout = () => {
        btn.style.background = 'rgba(255,255,255,0.06)';
      };
    });
    container.appendChild(saveRow);
    saveRow.querySelector('#dw-save-path').onclick = (e) => { e.stopPropagation(); exportPath(); };
    saveRow.querySelector('#dw-save-logs').onclick = (e) => { e.stopPropagation(); exportLogs(); };

    // Pace control
    const paceRow = document.createElement('div');
    paceRow.style.cssText = `display:flex;flex-direction:column;gap:3px;padding-top:4px;border-top:1px solid rgba(255,255,255,0.1);`;
    paceRow.innerHTML = `
      <span style="font-size:8px;color:rgba(255,255,255,0.5);text-align:center;">Pace: <span id="dw-pace-val">${(engine.getConfig().pace / 1000).toFixed(1)}s</span></span>
      <input type="range" min="500" max="5000" step="100" value="${engine.getConfig().pace}" style="width:100%;-webkit-appearance:none;height:3px;background:rgba(255,255,255,0.15);border-radius:2px;outline:none;cursor:pointer;" />
    `;
    const sliderStyle = document.createElement('style');
    sliderStyle.textContent = `
      .dw-float-ui input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:10px;height:10px;background:rgba(255,255,255,0.8);border-radius:50%;cursor:pointer;}
      .dw-float-ui input[type=range]::-moz-range-thumb{width:10px;height:10px;background:rgba(255,255,255,0.8);border:none;border-radius:50%;cursor:pointer;}
    `;
    container.appendChild(sliderStyle);
    container.appendChild(paceRow);
    const paceSlider = paceRow.querySelector('input');
    paceValEl = paceRow.querySelector('#dw-pace-val');
    paceSlider.oninput = (e) => {
      e.stopPropagation();
      paceValEl.innerText = (paceSlider.value / 1000).toFixed(1) + 's';
      engine.setPace(parseInt(paceSlider.value));
    };

    document.body.appendChild(container);
    makeDraggable(container);

    if (onPathCollectionToggle) onPathCollectionToggle(true);
    engine.setSelfAvoiding(true);
  };

  const updateStartStopBtn = () => {
    if (!startStopBtn) return;
    if (engine.isNavigating()) {
      startStopBtn.innerHTML = '<span>⏹</span> STOP';
      startStopBtn.style.background = 'rgba(255, 80, 80, 0.2)';
      startStopBtn.style.color = '#ff8a80';
      startStopBtn.style.borderColor = 'rgba(255, 80, 80, 0.4)';
    } else {
      startStopBtn.innerHTML = '<span>▶</span> START';
      startStopBtn.style.background = 'rgba(255,255,255,0.08)';
      startStopBtn.style.color = '#e8eaed';
      startStopBtn.style.borderColor = 'rgba(255,255,255,0.12)';
    }
  };

  const exportPath = () => {
    const walkPath = engine.getWalkPath();
    if (walkPath.length === 0) { alert('No path recorded yet.'); return; }
    const blob = new Blob([JSON.stringify(walkPath, null, 2)], { type: 'application/json' });
    downloadFile(blob, `dw-path-${Date.now()}.json`);
  };

  const exportLogs = () => {
    if (sessionLogs.length === 0) { alert('No logs captured yet.'); return; }
    const blob = new Blob([sessionLogs.join('\n')], { type: 'text/plain' });
    downloadFile(blob, `dw-logs-${Date.now()}.txt`);
  };

  const downloadFile = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateStartStopBtn();
  };

  const init = () => {
    if (!document.body) return { destroy: () => {} };
    try {
      createUI();
      updateStartStopBtn();
      if (autoStart) engine.start();
      console.log('🟣 UI Initialized (Draggable Panel)');
      return { destroy };
    } catch (e) {
      console.error('UI Init Failed:', e);
      return { destroy: () => {} };
    }
  };

  const destroy = () => {
    engine.stop();
    document.querySelectorAll('.dw-float-ui').forEach(el => el.remove());
  };

  return { init, destroy, onStatusUpdate };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */

// Global initialization lock
let __INITIALIZING__ = false;

// Global interval tracking for cleanup
window.__DRUNK_WALKER_INTERVALS__ = window.__DRUNK_WALKER_INTERVALS__ || new Set();

// Cleanup function for ALL intervals
const cleanupAllIntervals = () => {
  if (window.__DRUNK_WALKER_INTERVALS__) {
    console.log(`🤪 Cleaning up ${window.__DRUNK_WALKER_INTERVALS__.size} existing interval(s)...`);
    window.__DRUNK_WALKER_INTERVALS__.forEach(id => clearInterval(id));
    window.__DRUNK_WALKER_INTERVALS__.clear();
  }
};

// Allow restart by clearing previous instance
if (window.DRUNK_WALKER) {
  console.log('🤪 Drunk Walker: Stopping previous instance...');
  try {
    window.DRUNK_WALKER.stop();
  } catch(e) {
    console.warn('Error stopping previous instance:', e);
  }
  // Remove the global immediately to prevent race conditions
  delete window.DRUNK_WALKER;
  window.DRUNK_WALKER_ACTIVE = false;
}

// Aggressive cleanup before new instance
cleanupAllIntervals();

// Remove any existing UI panel from previous runs
const existingPanel = document.getElementById('dw-modern-panel');
if (existingPanel) {
  console.log('🤪 Removing existing UI panel...');
  existingPanel.remove();
}

// Small delay to ensure cleanup is processed by browser
setTimeout(() => {
  window.DRUNK_WALKER_ACTIVE = true;
  console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

  // Initialize when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initialize);
  } else {
    initialize();
  }
}, 100);

// Wait for DOM to be ready before initializing
const initialize = () => {
  // Prevent double initialization
  if (__INITIALIZING__) {
    console.log('🤪 [initialize] Already initializing, skipping...');
    return;
  }
  __INITIALIZING__ = true;

  // Double-check and remove any panel that might have appeared
  const existingPanel = document.getElementById('dw-modern-panel');
  if (existingPanel) {
    console.log('🤪 [initialize] Removing panel that appeared during init...');
    existingPanel.remove();
  }

  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // ═══════════════════════════════════════════════════════════
    // 💾 AUTO-SAVE: Simple walk data persistence
    // Saves walk progress to localStorage every 60 seconds
    // ═══════════════════════════════════════════════════════════
    const AUTOSAVE_INTERVAL = 60000; // 60 seconds
    let autoSaveTimer = null;
    const saveWalkData = () => {
      const walkData = {
        version: VERSION,
        timestamp: Date.now(),
        steps: engine.getSteps(),
        visited: engine.getVisitedCount(),
        path: engine.getWalkPath()
      };
      try {
        localStorage.setItem('drunk-walker-autosave', JSON.stringify(walkData));
        console.log(`💾 Walk saved: ${walkData.steps} steps, ${walkData.visited} unique`);
      } catch (e) {
        console.warn('💾 Auto-save failed:', e.message);
      }
    };

    // Load previous walk if exists
    try {
      const saved = localStorage.getItem('drunk-walker-autosave');
      if (saved) {
        const data = JSON.parse(saved);
        const age = Date.now() - data.timestamp;
        if (age < 3600000 && data.path && data.path.length > 0) { // 1 hour max
          engine.setSteps(data.steps);
          engine.setWalkPath(data.path);
          engine.restoreVisitedFromPath(data.path);
          console.log(`💾 Previous walk restored: ${data.steps} steps, ${data.visited} unique`);
        }
      }
    } catch (e) {
      console.warn('💾 Could not load previous walk:', e.message);
    }

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create exploration map
    const map = createExplorationMap();
    map.init();

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: (status, steps, stuckCount) => {
        ui.onStatusUpdate(status, steps, stuckCount);
        // Update map periodically (every 10 ticks)
        if (steps % 10 === 0 && map.isVisible()) {
          const transitionGraph = engine.getTransitionGraph();
          const currentLocation = engine.getWalkPath().length > 0 
            ? engine.getWalkPath()[engine.getWalkPath().length - 1].location 
            : null;
          map.render(transitionGraph, currentLocation, engine.getVisitedUrls());
        }
      },
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Start auto-save timer
    autoSaveTimer = setInterval(saveWalkData, AUTOSAVE_INTERVAL);
    console.log('💾 Auto-save enabled: walks saved every 60 seconds');

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      map,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        if (autoSaveTimer) clearInterval(autoSaveTimer);
        saveWalkData(); // Final save on stop
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      },
      exportWalk: () => {
        // Export walk data to JSON file
        const data = {
          version: VERSION,
          timestamp: Date.now(),
          steps: engine.getSteps(),
          visited: engine.getVisitedCount(),
          path: engine.getWalkPath(),
          graph: engine.getTransitionGraph()
        };
        const json = JSON.stringify(data, null, 2);
        const blob = new Blob([json], { type: 'application/json' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `drunk-walker-${Date.now()}.json`;
        a.click();
        URL.revokeObjectURL(url);
        console.log('📤 Walk exported');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
    __INITIALIZING__ = false;  // Reset lock on error
  }
};

// NOTE: Initialization is handled by the setTimeout above to ensure
// proper cleanup of any previous instance. The setTimeout gives the
// browser time to process the cleanup before creating a new instance.

}();