// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v3.70.0-EXP - CONSOLE VERSION
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// Any changes made here will be LOST on next build.
//
// TO MAKE CHANGES:
//   Edit files in src/ directory, then run: node build.js
//   - src/core/wheel.js       - Wheel component
//   - src/core/traversal.js   - Traversal algorithms
//   - src/core/navigation.js  - Compatibility layer
//   - src/core/engine.js      - Core engine (state, timing, path recording)
//   - src/input/handlers.js   - Keyboard/mouse events
//   - src/ui/controller.js    - Control panel UI
//   - src/main.js             - Entry point
// ═══════════════════════════════════════════════════════════════════════════════
// This version is optimized for pasting into browser console
// 1. Type: allow pasting
// 2. Paste this code
// 3. Press Enter

void function initDrunkWalker(){
  if (window.DRUNK_WALKER_ACTIVE) {
    console.log('🤪 Drunk Walker already running. Refresh page to restart.');
    return;
  }
  window.DRUNK_WALKER_ACTIVE = true;

  // === WHEEL ===
  /**
 * Wheel component for Drunk Walker
 * Manages orientation and turning (only left)
 */

function createWheel(callbacks) {
  const { onLongKeyPress } = callbacks;
  let orientation = 0; // 0-359

  const getOrientation = () => orientation;

  const setOrientation = (newOrientation) => {
    orientation = normalizeAngle(newOrientation);
  };

  const turnLeft = (angle, callback) => {
    // Convert angle to duration (10ms per degree as per existing code)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));

    if (onLongKeyPress) {
      onLongKeyPress('ArrowLeft', clampedDuration, () => {
        orientation = normalizeAngle(orientation - angle);
        if (callback) callback();
      });
    } else {
      orientation = normalizeAngle(orientation - angle);
      if (callback) callback();
    }
  };

  const normalizeAngle = (angle) => {
    angle = angle % 360;
    if (angle < 0) angle += 360;
    return angle;
  };

  return {
    getOrientation,
    setOrientation,
    turnLeft,
    reset: () => { orientation = 0; }
  };
}


  // === TRAVERSAL ALGORITHMS ===
  /**
 * Traversal algorithms for Drunk Walker
 * This is where decision-making logic lives
 */

/**
 * Normalizes angle to 0-359
 */
function normalizeAngle(angle) {
  angle = angle % 360;
  if (angle < 0) angle += 360;
  return angle;
}

/**
 * Predict next location given current location, orientation, and step distance
 */
function predictNextLocation(currentLocation, orientation, stepDistance = 0.0005) {
  if (!currentLocation || typeof currentLocation !== 'string') return null;
  const parts = currentLocation.split(',');
  if (parts.length < 2) return currentLocation;

  const [lat, lng] = parts.map(Number);
  const yawRad = orientation * Math.PI / 180;
  
  // Approximate lat/lng offset based on yaw (simplified projection)
  const dLat = Math.cos(yawRad) * stepDistance;
  const dLng = Math.sin(yawRad) * stepDistance / Math.cos(lat * Math.PI / 180);
  
  const nextLat = (lat + dLat).toFixed(6);
  const nextLng = (lng + dLng).toFixed(6);
  
  return `${nextLat},${nextLng}`;
}

/**
 * Advanced Traversal Algorithm
 * Implements:
 * A. Weighted "Heatmap" Exploration
 * B. Systematic Search Pattern for stuck recovery
 * C. Path avoidance using breadcrumbs
 */
function createDefaultAlgorithm(cfg) {
  const panicThreshold = cfg.panicThreshold || 3;
  
  // State for Systematic Search Pattern (Spiral Recovery)
  let lastSearchAngle = 0;

  /**
   * Decide what to do next
   * @param {Object} context - current state
   * @returns {Object} { turn: boolean, angle?: number }
   */
  const decide = (context) => {
    const { stuckCount, currentLocation, visitedUrls, breadcrumbs, orientation } = context;

    // PRIORITY 1: Systematic Search (Stuck Recovery)
    if (cfg.expOn && stuckCount >= panicThreshold) {
      // If we just got stuck, start with a small angle
      // If we stay stuck, escalate the angle to scan all directions
      if (stuckCount === panicThreshold) {
        lastSearchAngle = 30;
      } else {
        lastSearchAngle = (lastSearchAngle + 30) % 360;
        if (lastSearchAngle === 0) lastSearchAngle = 30;
      }
      
      console.log(`Systematic Search: stuckCount=${stuckCount}, angle=${lastSearchAngle}`);
      return { turn: true, angle: lastSearchAngle };
    }

    // PRIORITY 2: Weighted Exploration (Proactive Avoidance)
    if (cfg.expOn && cfg.selfAvoiding && currentLocation && stuckCount === 0) {
      // Reset search angle when not stuck
      lastSearchAngle = 0;

      // Scan 360 degrees in 30 degree increments
      const scanAngles = [0, 30, -30, 60, -60, 90, -90, 120, -120, 150, -150, 180];
      let bestScore = Infinity;
      let bestAngle = 0;

      for (const angle of scanAngles) {
        const testOrientation = normalizeAngle(orientation + angle);
        const testLocation = predictNextLocation(currentLocation, testOrientation);
        
        if (!testLocation) continue;

        // Calculate score: Lower is better
        // 1. Visit Count (Heatmap)
        const visitCount = visitedUrls.get(testLocation) || 0;
        
        // 2. Breadcrumb Penalty (Scent) - avoid recently visited areas more strongly
        let breadcrumbPenalty = 0;
        breadcrumbs.forEach((bc, index) => {
          if (bc === testLocation) {
            // Penalty is higher for more recent breadcrumbs
            breadcrumbPenalty += (index + 1); 
          }
        });

        // 3. Forward bias: slight preference for staying the same course if everything else is equal
        const forwardBias = (angle === 0) ? -0.1 : 0;

        const score = (visitCount * 10) + breadcrumbPenalty + forwardBias;

        if (score < bestScore) {
          bestScore = score;
          bestAngle = angle;
        }
      }

      // Only turn if the best angle is NOT the current one
      if (bestAngle !== 0) {
        console.log(`Exploration Decision: angle=${bestAngle}, score=${bestScore}`);
        return { turn: true, angle: Math.abs(bestAngle) };
      }
    }

    return { turn: false };
  };

  return { decide };
}


  // === NAVIGATION COMPATIBILITY LAYER ===
  /**
 * Navigation Strategies - Compatibility Wrapper for v4.0.0+
 * This file maintains the old API for tests and bundle validation
 * but uses the new Traversal/Wheel architecture.
 */



function createProactiveAvoidance(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeProactiveAvoidance: (yaw, loc, visited) => {
      const result = algorithm.decide({ stuckCount: 0, currentLocation: loc, visitedUrls: visited, orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createUnstuckNavigation(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeUnstuck: (stuckCount, panicThreshold, yaw) => {
      const result = algorithm.decide({ stuckCount, currentLocation: '', visitedUrls: new Set(), orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createNavigationController(cfg, callbacks) {
  return {
    tick: () => ({ action: 'move', strategy: 'normal', busy: false }),
    getCumulativeTurnAngle: () => 0,
    resetCumulativeTurnAngle: () => {},
    reset: () => {},
    getState: () => ({ globalOrientation: 0, proactive: { state: 'IDLE' }, unstuck: { state: 'IDLE' } })
  };
}




  // === CORE ENGINE ===
  // State management, tick timing, path recording
  // TO CHANGE ENGINE: Edit src/core/engine.js
  /**
 * Drunk Walker Core Engine
 * Independent navigation logic - works without UI
 * 
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording (this file)
 * - Wheel: Orientation management (in src/core/wheel.js)
 * - Traversal: Decision-making logic (in src/core/traversal.js)
 * 
 * TO CHANGE NAVIGATION BEHAVIOR:
 * Edit src/core/traversal.js - NOT this file
 */




const VERSION = '3.70.0-EXP';

const defaultConfig = {
  pace: 2000,
  kbOn: true,      // Keyboard mode ON by default
  expOn: true,     // Experimental mode ON by default (enables unstuck algorithm)
  panicThreshold: 3,
  radius: 50,
  targetX: 0.5,    // 50% of screen width
  targetY: 0.7,    // 70% of screen height
  turnDuration: 600,  // ms to hold ArrowLeft for ~60° turn (fixed)
  collectPath: true,  // Path recording ENABLED by default
  selfAvoiding: true  // Self-avoiding walk ENABLED by default (opt-out)
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = typeof window !== 'undefined' ? window.location.href : '';
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;
  let isBusy = false;

  // Path collection (opt-in)
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;

  // Visited nodes memory for self-avoiding walk
  let visitedUrls = new Map(); // location -> count
  let breadcrumbs = []; // last 20 locations

  // Action callbacks (to be provided by caller)
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  // Extract location from Street View URL
  const extractLocation = (url) => {
    try {
      const urlObj = new URL(url);
      const hash = urlObj.hash || urlObj.pathname;
      const match = hash.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (match) {
        return `${match[1]},${match[2]}`;
      }
      const placeMatch = urlObj.searchParams.get('place_id');
      if (placeMatch) {
        return `place:${placeMatch}`;
      }
      return urlObj.pathname + urlObj.hash;
    } catch (e) {
      return url;
    }
  };

  // Components
  const wheel = createWheel({
    onLongKeyPress: (key, duration, callback) => {
      if (onLongKeyPress) onLongKeyPress(key, duration, callback);
      else if (callback) callback();
    }
  });

  let algorithm = createDefaultAlgorithm(cfg);

  // State getters
  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  // Configuration setters
  const setPace = (newPace) => {
    cfg.pace = newPace;
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setExperimentalMode = (on) => { cfg.expOn = on; };
  const setPolygon = (points) => { poly = points; };
  const setPathCollection = (enabled) => {
    isPathCollectionEnabled = enabled;
    cfg.collectPath = enabled;
    if (!enabled) walkPath = [];
  };
  const setWalkPath = (path) => { walkPath = path ? [...path] : []; };
  const setSteps = (count) => { steps = count; };
  const getWalkPath = () => [...walkPath];
  const clearWalkPath = () => { walkPath = []; };

  const recordStep = () => {
    if (isPathCollectionEnabled) {
      const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
      const location = extractLocation(currentUrl);
      walkPath.push({
        url: currentUrl,
        currentYaw: Math.round(wheel.getOrientation())
      });
      if (cfg.selfAvoiding) {
        const count = visitedUrls.get(location) || 0;
        visitedUrls.set(location, count + 1);

        breadcrumbs.push(location);
        if (breadcrumbs.length > 20) breadcrumbs.shift();
      }
    }
  };

  const isUrlVisited = (location) => visitedUrls.has(location);
  const clearVisitedUrls = () => { visitedUrls.clear(); breadcrumbs = []; };
  const getVisitedCount = () => visitedUrls.size;
  const getCurrentYaw = () => wheel.getOrientation();
  const resetCurrentYaw = () => { wheel.reset(); };
  const getCumulativeTurnAngle = getCurrentYaw;
  const resetCumulativeTurnAngle = resetCurrentYaw;

  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    breadcrumbs = [];
    path.forEach(step => {
      let loc = step.location;
      if (!loc && step.url) {
        loc = extractLocation(step.url);
      }
      if (loc) {
        const count = visitedUrls.get(loc) || 0;
        visitedUrls.set(loc, count + 1);

        breadcrumbs.push(loc);
        if (breadcrumbs.length > 20) breadcrumbs.shift();
      }
    });
  };

  const setUserMouseDown = (down) => { isUserMouseDown = down; };
  const setIsDrawing = (drawing) => { isDrawing = drawing; };

  const setActionHandlers = ({ keyPress, mouseClick, statusUpdate, longKeyPress, walkStop }) => {
    onKeyPress = keyPress;
    onMouseClick = mouseClick;
    onStatusUpdate = statusUpdate;
    onLongKeyPress = longKeyPress;
    onWalkStop = walkStop;
  };

  const updateStuckDetection = () => {
    if (!cfg.expOn) {
      stuckCount = 0;
      return;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    if (currentUrl === lastUrl) {
      stuckCount++;
    } else {
      lastUrl = currentUrl;
      stuckCount = 0;
    }
  };

  const getStatusText = () => {
    if (!cfg.expOn || stuckCount === 0) return 'WALKING';
    if (stuckCount >= cfg.panicThreshold) return `PANIC! (STUCK ${stuckCount})`;
    return `STUCK (${stuckCount})`;
  };

  const calculateClickTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1000;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1000;

    if (poly.length > 2) {
      const minX = Math.min(...poly.map(p => p.x));
      const maxX = Math.max(...poly.map(p => p.x));
      const minY = Math.min(...poly.map(p => p.y));
      const maxY = Math.max(...poly.map(p => p.y));

      let tx, ty, attempts = 0;
      do {
        tx = minX + Math.random() * (maxX - minX);
        ty = minY + Math.random() * (maxY - minY);
        attempts++;
      } while (!inPoly({ x: tx, y: ty }, poly) && attempts < 100);

      return { x: tx, y: ty };
    }

    const radius = cfg.expOn && stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  const inPoly = (p, vs) => {
    let inside = false;
    for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
      const xi = vs[i].x, yi = vs[i].y;
      const xj = vs[j].x, yj = vs[j].y;
      const intersect = ((yi > p.y) !== (yj > p.y)) &&
        (p.x < (xj - xi) * (p.y - yi) / (yj - yi) + xi);
      if (intersect) inside = !inside;
    }
    return inside;
  };

  const tick = () => {
    if (isUserMouseDown || isDrawing) return;

    updateStuckDetection();

    if (onStatusUpdate) {
      onStatusUpdate(getStatusText(), steps, stuckCount);
    }

    if (isBusy) {
      // Skip decision and movement, but still count the step as "busy"
      steps++;
      recordStep();
      return;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    const currentLocation = extractLocation(currentUrl);

    // Get algorithm decision
    const context = {
      url: currentUrl,
      location: currentLocation,
      visitedUrls,
      breadcrumbs,
      stuckCount,
      orientation: wheel.getOrientation()
    };

    const decision = algorithm.decide(context);

    if (decision.turn) {
      // Turn BEFORE pressing ArrowUp
      isBusy = true;
      wheel.turnLeft(decision.angle || 60, () => {
        // Continue with ArrowUp after turn finishes
        if (cfg.kbOn) {
          if (onKeyPress) onKeyPress('ArrowUp');
        } else {
          const target = calculateClickTarget();
          if (onMouseClick) onMouseClick(target.x, target.y);
        }
        // Step and record are handled by the main tick or here
        // Wait, if we set isBusy=true, the current tick should still count as a step
        isBusy = false;
      });
      // The tick that triggered the turn also counts as a step
      steps++;
      recordStep();
    } else {
      // Normal movement
      if (cfg.kbOn) {
        if (onKeyPress) onKeyPress('ArrowUp');
      } else {
        const target = calculateClickTarget();
        if (onMouseClick) onMouseClick(target.x, target.y);
      }
      steps++;
      recordStep();
    }
    
    console.log(`url=${currentUrl}, currentYaw=${Math.round(wheel.getOrientation())}`);
  };

  const start = () => {
    if (status === 'WALKING') return;
    status = 'WALKING';
    if (steps === 0) {
      stuckCount = 0;
      lastUrl = typeof window !== 'undefined' ? window.location.href : '';
    }
    if (intervalId) clearInterval(intervalId);
    intervalId = setInterval(tick, cfg.pace);
    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }
    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = '';
    status = 'IDLE';
    wheel.reset();
  };

  return {
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setExperimentalMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,
    getCurrentYaw,
    resetCurrentYaw,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    restoreVisitedFromPath,
    setUserMouseDown,
    setIsDrawing,
    setActionHandlers,
    start,
    stop,
    reset,
    tick,
    getConfig: () => ({ ...cfg }),
    // Stubs for backward compatibility
    getNavigation: () => null,
    getNavigationState: () => ({}),
    setAlgorithm: (newAlgorithm) => { algorithm = newAlgorithm; }
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */

const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};

/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas[width][height]') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}

/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Full key event sequence for maximum compatibility
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}

/**
 * Simulate long-press keyboard event (keydown -> hold -> keyup)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Key down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  
  // Hold for duration, then release
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
    if (callback) callback();
  }, duration);
}

/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };

  const target = document.elementFromPoint(x, y) || document.body;

  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));

  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}

/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;

  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };

  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };

  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);

  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Control Panel Management
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '3.70.0-EXP',
    autoStart = true,
    onPathCollectionToggle = null  // Callback for path collection toggle
  } = options;

  let container = null;
  let btn = null;
  let statusEl = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let paceSlider = null;
  let downloadLogsBtn = null;
  let minimizeBtn = null;
  let mainContent = null;
  let isMinimized = false;
  
  // Session logs storage
  const sessionLogs = [];
  const originalConsoleLog = console.log;
  
  // Intercept console.log to capture logs
  console.log = function(...args) {
    const timestamp = new Date().toISOString();
    const message = args.map(arg => 
      typeof arg === 'object' ? JSON.stringify(arg) : String(arg)
    ).join(' ');
    sessionLogs.push(`[${timestamp}] ${message}`);
    originalConsoleLog.apply(console, args);
  };

  // Create UI elements
  const createUI = () => {
    container = document.createElement('div');
    container.id = 'dw-ctrl-panel';
    container.style.cssText = 'position:fixed;top:20px;right:20px;background:rgba(0,0,0,0.9);color:#0f0;padding:15px;font-family:monospace;z-index:999999;border:2px solid #0f0;border-radius:10px;box-shadow:0 0 15px #0f0;min-width:180px;user-select:none;';

    // Header with minimize button
    const header = document.createElement('div');
    header.style.cssText = 'display:flex;justify-content:space-between;align-items:center;margin-bottom:5px;';
    
    const title = document.createElement('div');
    title.innerText = `🤪 DRUNK WALKER v${version}`;
    title.style.fontSize = '12px';
    title.style.fontWeight = 'bold';
    
    minimizeBtn = document.createElement('button');
    minimizeBtn.innerText = '−';
    minimizeBtn.style.cssText = 'background:none;border:1px solid #0f0;color:#0f0;cursor:pointer;padding:0 5px;font-weight:bold;font-size:14px;';
    minimizeBtn.onclick = toggleMinimize;
    
    header.appendChild(title);
    header.appendChild(minimizeBtn);
    container.appendChild(header);

    const hr = document.createElement('hr');
    hr.id = 'dw-header-hr';
    hr.style.borderColor = '#0f0';
    container.appendChild(hr);

    // Visible Steps (Always visible or in steps section)
    const stepsLine = document.createElement('div');
    stepsLine.style.margin = '5px 0';
    stepsLine.innerHTML = 'STEPS: <span id="dw-steps">0</span>';
    container.appendChild(stepsLine);
    stepsEl = stepsLine.querySelector('#dw-steps');

    // Main Content wrapper (Toggleable)
    mainContent = document.createElement('div');
    mainContent.id = 'dw-main-content';
    
    // Remaining Stats
    const stats = document.createElement('div');
    stats.style.margin = '5px 0';
    stats.innerHTML = 'STATUS: <span id="dw-status">IDLE</span><br>VISITED: <span id="dw-visited">0</span>';
    mainContent.appendChild(stats);
    statusEl = stats.querySelector('#dw-status');
    visitedEl = stats.querySelector('#dw-visited');

    // Pace control
    const paceLabel = document.createElement('div');
    paceLabel.style.fontSize = '10px';
    paceLabel.style.marginTop = '10px';
    paceLabel.innerHTML = 'PACE: <span id="dw-pace-val">2.0</span>s';
    mainContent.appendChild(paceLabel);
    paceValEl = paceLabel.querySelector('#dw-pace-val');

    paceSlider = document.createElement('input');
    paceSlider.type = 'range';
    paceSlider.min = '500';
    paceSlider.max = '5000';
    paceSlider.step = '100';
    paceSlider.value = engine.getConfig().pace;
    paceSlider.style.width = '100%';
    paceSlider.oninput = () => {
      const newPace = parseInt(paceSlider.value);
      if (paceValEl) paceValEl.innerText = (newPace / 1000).toFixed(1);
      engine.setPace(newPace);
    };
    mainContent.appendChild(paceSlider);

    // Path export button (Download only)
    const exportDiv = document.createElement('div');
    exportDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    // Download path JSON button
    const downloadPathBtn = document.createElement('button');
    downloadPathBtn.innerText = '💾 Download Path';
    downloadPathBtn.style.cssText = 'flex:1;padding:6px;background:#28a745;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadPathBtn.onclick = () => {
      const walkPath = engine.getWalkPath();
      if (walkPath.length === 0) {
        alert('No path recorded. Start walking!');
        return;
      }
      const jsonStr = JSON.stringify(walkPath, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      downloadPathBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadPathBtn.innerText = '💾 Download Path';
      }, 2000);
    };
    
    exportDiv.appendChild(downloadPathBtn);
    mainContent.appendChild(exportDiv);

    // Download logs button
    const logsDiv = document.createElement('div');
    logsDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    downloadLogsBtn = document.createElement('button');
    downloadLogsBtn.innerText = '📄 Download Logs';
    downloadLogsBtn.style.cssText = 'width:100%;padding:6px;background:#ff6600;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadLogsBtn.onclick = () => {
      if (sessionLogs.length === 0) {
        alert('No logs recorded yet. Start walking to generate logs!');
        return;
      }
      
      const logContent = sessionLogs.join('\n');
      const blob = new Blob([logContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-logs-${new Date().toISOString().replace(/[:.]/g, '-')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      downloadLogsBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadLogsBtn.innerText = '📄 Download Logs';
      }, 2000);
    };
    
    logsDiv.appendChild(downloadLogsBtn);
    mainContent.appendChild(logsDiv);

    // Restore Walk from JSON button
    const restoreBtn = document.createElement('button');
    restoreBtn.innerText = '📂 Restore Walk';
    restoreBtn.style.cssText = 'width:100%;margin-top:8px;padding:6px;background:#663399;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    restoreBtn.onclick = () => {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json,application/json';
      input.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const walkPath = JSON.parse(event.target.result);
            if (!Array.isArray(walkPath) || walkPath.length === 0) {
              throw new Error('Invalid walk path format');
            }
            
            // Validate path structure
            const firstStep = walkPath[0];
            if (!firstStep.url && !firstStep.location) {
              throw new Error('Invalid path entries');
            }
            
            // Restore walk path
            engine.setWalkPath(walkPath);

            // Restore visited URLs from path
            engine.restoreVisitedFromPath(walkPath);

            // Navigate to last URL in path
            const lastStep = walkPath[walkPath.length - 1];
            if (lastStep.url) {
              window.location.href = lastStep.url;
            }
            
            console.log(`🤪 DRUNK WALKER: Restored walk with ${walkPath.length} steps`);
            alert(`✓ Walk restored!\n\n${walkPath.length} steps loaded\nNavigating to last position...`);
          } catch (err) {
            console.error('Failed to restore walk:', err);
            alert('❌ Failed to restore walk\n\n' + err.message + '\n\nPlease ensure the file is a valid walk JSON export.');
          }
        };
        reader.readAsText(file);
      };
      input.click();
    };
    mainContent.appendChild(restoreBtn);

    // Start/Stop button
    btn = document.createElement('button');
    btn.innerText = '▶ START';
    btn.style.cssText = 'width:100%;margin-top:10px;padding:8px;background:#0f0;color:#000;border:none;font-weight:bold;cursor:pointer;border-radius:5px;';
    btn.onclick = () => {
      if (engine.isNavigating()) {
        engine.stop();
      } else {
        engine.start();
      }
      updateButton();
    };
    mainContent.appendChild(btn);

    container.appendChild(mainContent);
    document.body.appendChild(container);
    
    // Ensure features are enabled by default as requested
    if (onPathCollectionToggle) onPathCollectionToggle(true);
    engine.setSelfAvoiding(true);
  };

  const toggleMinimize = () => {
    isMinimized = !isMinimized;
    if (isMinimized) {
      mainContent.style.display = 'none';
      minimizeBtn.innerText = '+';
      container.style.minWidth = '100px';
    } else {
      mainContent.style.display = 'block';
      minimizeBtn.innerText = '−';
      container.style.minWidth = '180px';
    }
  };

  // Update button appearance based on state
  const updateButton = () => {
    if (!btn) return;
    if (engine.isNavigating()) {
      btn.innerText = '🔴 STOP';
      btn.style.background = '#f00';
    } else {
      btn.innerText = '▶ START';
      btn.style.background = '#0f0';
    }
  };

  // Status update handler
  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (statusEl) statusEl.innerText = statusText;
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateButton();
  };

  // Initialize
  const init = () => {
    // Wait for DOM to be ready
    if (!document.body) {
      console.error('🤪 DRUNK WALKER: document.body not ready yet');
      return { destroy: () => {} };
    }

    try {
      createUI();
      updateButton();

      if (autoStart) {
        engine.start();
      }

      console.log('🤪 Control panel created successfully');
      return { destroy };
    } catch (error) {
      console.error('🤪 DRUNK WALKER: Failed to initialize UI:', error);
      return { destroy: () => {} };
    }
  };

  // Path collection state getter - always true now
  const getPathCollectionEnabled = () => true;

  // Cleanup
  const destroy = () => {
    engine.stop();
    if (container) {
      container.remove();
      container = null;
    }
  };

  return { init, destroy, onStatusUpdate, getPathCollectionEnabled };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */





// Allow restart by clearing previous instance
if (window.DRUNK_WALKER_ACTIVE) {
  console.log('🤪 Drunk Walker: Restarting...');
  if (window.DRUNK_WALKER) {
    try { window.DRUNK_WALKER.stop(); } catch(e) {}
  }
}

window.DRUNK_WALKER_ACTIVE = true;

console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

// Wait for DOM to be ready before initializing
const initialize = () => {
  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: ui.onStatusUpdate,
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
  }
};

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initialize);
} else {
  initialize();
}

}();