// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v3.67.7-EXP - CONSOLE VERSION
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
// 
// This file is generated by build.js from source files in src/
// Any changes made here will be LOST on next build.
//
// TO MAKE CHANGES:
//   Edit files in src/ directory, then run: node build.js
//   - src/core/navigation.js  - Navigation strategies (self-avoiding, unstuck)
//   - src/core/engine.js      - Core engine (state, timing, path recording)
//   - src/input/handlers.js   - Keyboard/mouse events
//   - src/ui/controller.js    - Control panel UI
//   - src/main.js             - Entry point
// ═══════════════════════════════════════════════════════════════════════════════
// This version is optimized for pasting into browser console
// 1. Type: allow pasting
// 2. Paste this code
// 3. Press Enter

void function initDrunkWalker(){
  if (window.DRUNK_WALKER_ACTIVE) {
    console.log('🤪 Drunk Walker already running. Refresh page to restart.');
    return;
  }
  window.DRUNK_WALKER_ACTIVE = true;

  // === NAVIGATION STRATEGIES ===
  // Pluggable movement algorithms (self-avoiding, unstuck, etc.)
  // TO CHANGE NAVIGATION: Edit src/core/navigation.js
  /**
 * Navigation Strategies - Pluggable Movement Algorithms
 * 
 * ============================================================================
 * ARCHITECTURE
 * ============================================================================
 * 
 * This module contains ALL navigation/movement logic as swappable strategies.
 * The engine (engine.js) delegates movement decisions to this module.
 * 
 * TO CHANGE NAVIGATION BEHAVIOR:
 * 1. Edit this file (src/core/navigation.js)
 * 2. Or create a new strategy function and swap it in createNavigationController()
 * 
 * ============================================================================
 * STRATEGIES
 * ============================================================================
 * 
 * 1. createSelfAvoidingNavigation()
 *    - Prefers unvisited locations
 *    - Turns left 20°-50° at visited nodes
 *    - Immediately steps forward after turning
 *    - Verifies URL changed before allowing next action
 * 
 * 2. createUnstuckNavigation()
 *    - Recovery from stuck state (≥3 ticks at same URL)
 *    - Turns left 30°-90° with random bounded variation
 *    - Immediately steps forward after turning
 *    - Guaranteed to never get stuck (360° coverage)
 * 
 * 3. createNavigationController()
 *    - Combines both strategies
 *    - Priority: Unstuck > Self-Avoiding > Normal movement
 *    - State machine prevents continuous rotation
 * 
 * ============================================================================
 * STATE MACHINE
 * ============================================================================
 * 
 * Both strategies use the same state machine:
 * 
 *   IDLE ──▶ TURNING ──▶ MOVING ──▶ VERIFYING ──▶ IDLE
 *            (turn)     (step)     (check URL)
 * 
 * While busy (not IDLE), navigation.tick() returns { busy: true },
 * preventing new decisions until the current sequence completes.
 * 
 * ============================================================================
 * INTERFACE
 * ============================================================================
 * 
 * Each strategy returns an object with:
 * - executeStep/executeUnstuck(): Main action, returns { action, busy, ... }
 * - isBusy(): Check if sequence in progress
 * - getCumulativeTurnAngle(): Total degrees turned
 * - resetCumulativeTurnAngle(): Reset angle tracking
 * - reset(): Reset all state
 * - getState(): Debug info
 * 
 * createNavigationController() provides:
 * - tick(context): Main entry point, returns { action, busy, strategy }
 * - getCumulativeTurnAngle(), resetCumulativeTurnAngle(), reset, getState()
 * 
 * ============================================================================
 * EXAMPLE: Creating a Custom Strategy
 * ============================================================================
 * 
 * function createMyCustomNavigation(cfg, callbacks) {
 *   let state = 'IDLE';
 *   
 *   const executeStep = (currentUrl, visitedUrls) => {
 *     if (state !== 'IDLE') return { action: 'none', busy: false };
 *     
 *     // Your custom logic here
 *     if (shouldTurn()) {
 *       state = 'TURNING';
 *       callbacks.onLongKeyPress('ArrowLeft', 500, () => {
 *         callbacks.onKeyPress('ArrowUp');
 *         setTimeout(() => { state = 'IDLE'; }, cfg.pace);
 *       });
 *       return { action: 'turn', busy: true };
 *     }
 *     
 *     return { action: 'move', busy: false };
 *   };
 *   
 *   return {
 *     executeStep,
 *     isBusy: () => state !== 'IDLE',
 *     getCumulativeTurnAngle: () => 0,
 *     resetCumulativeTurnAngle: () => {},
 *     reset: () => { state = 'IDLE'; },
 *     getState: () => ({ state })
 *   };
 * }
 */

// ═══════════════════════════════════════════════════════════════════════════════
// SELF-AVOIDING NAVIGATION STRATEGY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Self-Avoiding Random Walk Navigation
 * 
 * Behavior:
 * - Detects when at a visited location
 * - Turns left with random bounded angle (20°-50°)
 * - Immediately steps forward after turn
 * - Verifies URL changed before allowing next action
 * 
 * @param {Object} cfg - Configuration object
 * @param {Object} callbacks - Callback functions
 * @returns {Object} Navigation strategy instance
 */
function createSelfAvoidingNavigation(cfg, callbacks) {
  const { onKeyPress, onLongKeyPress, onStatusUpdate, extractLocation } = callbacks;

  // State machine: 'IDLE' | 'TURNING' | 'MOVING' | 'VERIFYING'
  let state = 'IDLE';
  let urlBeforeTurn = '';
  let cumulativeTurnAngle = 0;
  
  // Track tried turn directions at each location to avoid repeating
  // Key: location, Value: Set of turn angles tried (binned to 30° = 12 directions)
  const triedTurns = new Map();

  /**
   * Bin turn angle to nearest 30° (12 directions)
   * @param {number} angle - Turn angle (0-360)
   * @returns {number} Binned angle
   */
  const binTurnAngle = (angle) => {
    return Math.round(angle / 30) * 30;
  };

  /**
   * Get a new turn angle that hasn't been tried at this location
   * @param {string} location - Current location
   * @returns {number} Turn angle in ms (200-500ms = 20°-50°)
   */
  const getNewTurnAngle = (location) => {
    const tried = triedTurns.get(location) || new Set();
    
    // Generate random angle between 20°-50° (200-500ms)
    // If we've tried 3+ angles, just pick random
    if (tried.size >= 3) {
      triedTurns.delete(location);  // Reset memory
      return getRandomTurnAngle();
    }
    
    // Try up to 5 times to find untried angle
    for (let i = 0; i < 5; i++) {
      const angle = getRandomTurnAngle();
      const binned = binTurnAngle(angle);
      if (!tried.has(binned)) {
        tried.add(binned);
        triedTurns.set(location, tried);
        return angle;
      }
    }
    
    // All angles tried, pick random anyway
    return getRandomTurnAngle();
  };

  /**
   * Get random turn angle (20°-50° = 200-500ms)
   * @returns {number} Turn duration in ms
   */
  const getRandomTurnAngle = () => {
    const randomVariation = (Math.random() - 0.5) * 300;  // ±150ms = ±15°
    const baseDuration = cfg.turnDuration / 2;  // ~300ms = ~30°
    return Math.max(200, Math.min(500, baseDuration + randomVariation));
  };

  /**
   * Execute self-avoiding step
   * @param {string} currentUrl - Current page URL
   * @param {Set} visitedUrls - Set of visited location identifiers
   * @returns {Object} Action result: { action: 'turn'|'move'|'none', ... }
   */
  const executeStep = (currentUrl, visitedUrls) => {
    if (!cfg.selfAvoiding || !onKeyPress) return { action: 'none' };
    if (state !== 'IDLE') return { action: 'none' }; // Already in progress

    const currentLocation = extractLocation(currentUrl);
    
    // Self-avoiding only triggers when we're stuck (URL hasn't changed)
    // This is handled by the engine's stuck detection, not here
    // Self-avoiding just influences TURN DIRECTION selection
    
    // ALWAYS TURN LEFT - but pick angle we haven't tried at this location
    const turnKey = 'ArrowLeft';
    const turnDuration = getNewTurnAngle(currentLocation);
    const turnAngleChange = Math.round(turnDuration / 10);

    // Update cumulative turn angle
    cumulativeTurnAngle = (cumulativeTurnAngle + turnAngleChange) % 360;

    // Start turn + move sequence: TURN -> MOVE -> VERIFY
    urlBeforeTurn = currentUrl;
    state = 'TURNING';

    if (onLongKeyPress) {
      onLongKeyPress(turnKey, turnDuration, () => {
        console.log(`⬅️ Self-avoiding turn ~${turnAngleChange}° (cumulative: ${cumulativeTurnAngle}°)`);
        // After turn completes, immediately step forward
        if (onKeyPress) onKeyPress('ArrowUp');
        console.log(`⬆️ Moving forward after turn`);

        // Verify after delay
        setTimeout(() => {
          state = 'VERIFYING';
          const newUrl = typeof window !== 'undefined' ? window.location.href : urlBeforeTurn;
          const newLocation = extractLocation(newUrl);

          if (newUrl !== urlBeforeTurn) {
            visitedUrls.add(newLocation);
            console.log(`✅ Self-avoiding step successful - moved to: ${newLocation} (stuck reset to 0)`);
            // Clear tried turns for new location
            triedTurns.delete(newLocation);
          } else {
            console.log(`⚠️ Still at same location after ${turnAngleChange}° turn`);
          }

          state = 'IDLE';
          // Reset stuck count on success (handled by engine via callback)
          if (onStatusUpdate) {
            onStatusUpdate('WALKING', 0, 0);  // Reset stuck on successful move
          }
        }, cfg.pace);
      });
    }

    return {
      action: 'turn',
      turnAngle: turnAngleChange,
      cumulativeTurnAngle
    };
  };

  /**
   * Check if navigation sequence is in progress
   * @returns {boolean} True if busy with turn/move/verify sequence
   */
  const isBusy = () => state !== 'IDLE';

  /**
   * Get current cumulative turn angle
   * @returns {number} Degrees turned (0-360)
   */
  const getCumulativeTurnAngle = () => cumulativeTurnAngle;

  /**
   * Reset cumulative turn angle
   */
  const resetCumulativeTurnAngle = () => { cumulativeTurnAngle = 0; };

  /**
   * Reset strategy state
   */
  const reset = () => {
    state = 'IDLE';
    urlBeforeTurn = '';
    cumulativeTurnAngle = 0;
    triedTurns.clear();
  };

  /**
   * Get current state for debugging
   * @returns {Object} Current state info
   */
  const getState = () => ({
    state,
    urlBeforeTurn,
    cumulativeTurnAngle
  });

  return {
    executeStep,
    isBusy,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    reset,
    getState
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// UNSTUCK NAVIGATION STRATEGY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Unstuck Algorithm - Recovery from being stuck
 * 
 * Behavior:
 * - Detects when stuck (URL unchanged for N ticks)
 * - Turns left with random bounded angle (30°-90°)
 * - Immediately steps forward after turn
 * - Verifies URL changed, increments stuck counter if still stuck
 * - Guaranteed to eventually escape (360° coverage)
 * 
 * @param {Object} cfg - Configuration object
 * @param {Object} callbacks - Callback functions
 * @returns {Object} Navigation strategy instance
 */
function createUnstuckNavigation(cfg, callbacks) {
  const { onKeyPress, onLongKeyPress, onStatusUpdate } = callbacks;

  // State machine: 'IDLE' | 'TURNING' | 'MOVING' | 'VERIFYING'
  let state = 'IDLE';
  let urlBeforeUnstuck = '';
  let cumulativeTurnAngle = 0;

  /**
   * Execute unstuck sequence
   * @param {number} stuckCount - Current stuck counter
   * @param {number} panicThreshold - Threshold to trigger unstuck
   * @returns {Object} Action result: { action: 'turn'|'move'|'none', ... }
   */
  const executeUnstuck = (stuckCount, panicThreshold) => {
    if (state !== 'IDLE') return { action: 'none' };
    if (!cfg.expOn || stuckCount < panicThreshold) return { action: 'none' };

    console.log(`🚨 UNSTUCK TRIGGERED: Stuck count=${stuckCount} (threshold=${panicThreshold})`);

    // Start unstuck sequence: TURN -> MOVE -> VERIFY
    urlBeforeUnstuck = window.location.href;
    state = 'TURNING';

    // Turn left with bounded randomization (~30° to ~90°)
    // ALWAYS turns left - never right, never stuck
    const baseTurnDuration = cfg.turnDuration;  // 600ms = ~60°
    const randomVariation = (Math.random() - 0.5) * 600;  // ±300ms = ±30°
    const turnDuration = Math.max(300, Math.min(900, baseTurnDuration + randomVariation));
    const turnAngle = Math.round(turnDuration / 10);

    if (onLongKeyPress) {
      onLongKeyPress('ArrowLeft', turnDuration, () => {
        // Track turn angle
        cumulativeTurnAngle = (cumulativeTurnAngle + turnAngle) % 360;
        console.log(`⬅️ Unstuck: Turning left ~${turnAngle}° (cumulative: ${cumulativeTurnAngle}°)`);

        // After turn, move forward
        state = 'MOVING';
        if (onKeyPress) onKeyPress('ArrowUp');
        console.log(`⬆️ Unstuck: Moving forward after turn`);

        // Verify after delay
        setTimeout(() => {
          state = 'VERIFYING';
          const newUrl = typeof window !== 'undefined' ? window.location.href : urlBeforeUnstuck;

          // stuckCount returned here: 0 if moved, stuckCount+1 if still stuck
          let newStuckCount = 0;
          if (newUrl !== urlBeforeUnstuck) {
            // Successfully moved to new location - FRESH START!
            newStuckCount = 0;
            console.log(`✅ Unstuck SUCCESS - moved to new location (stuck reset to 0)`);
          } else {
            // Still at same location - increment stuck
            newStuckCount = stuckCount + 1;
            console.log(`⚠️ Still at same location after ${turnAngle}° left turn (stuck=${newStuckCount})`);
          }

          state = 'IDLE';
          // Return stuckCount to engine for reset
          if (onStatusUpdate) {
            onStatusUpdate('WALKING', 0, newStuckCount);
          }
        }, cfg.pace);
      });
    }

    return {
      action: 'turn',
      turnAngle,
      cumulativeTurnAngle,
      willUpdateStuckCount: true
    };
  };

  /**
   * Check if unstuck sequence is in progress
   * @returns {boolean} True if busy with turn/move/verify sequence
   */
  const isBusy = () => state !== 'IDLE';

  /**
   * Get current cumulative turn angle
   * @returns {number} Degrees turned (0-360)
   */
  const getCumulativeTurnAngle = () => cumulativeTurnAngle;

  /**
   * Reset cumulative turn angle
   */
  const resetCumulativeTurnAngle = () => { cumulativeTurnAngle = 0; };

  /**
   * Reset strategy state
   */
  const reset = () => {
    state = 'IDLE';
    urlBeforeUnstuck = '';
    cumulativeTurnAngle = 0;
  };

  /**
   * Get current state for debugging
   * @returns {Object} Current state info
   */
  const getState = () => ({
    state,
    urlBeforeUnstuck,
    cumulativeTurnAngle
  });

  return {
    executeUnstuck,
    isBusy,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    reset,
    getState
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMBINED NAVIGATION CONTROLLER
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Combined Navigation Controller
 *
 * Manages both self-avoiding and unstuck strategies.
 * 
 * STRATEGY:
 * - Self-avoiding: Only triggers when stuck (same as unstuck)
 * - Self-avoiding influences TURN DIRECTION (avoids repeating same turn angles)
 * - Unstuck: Falls back if self-avoiding doesn't trigger
 *
 * @param {Object} cfg - Configuration object
 * @param {Object} callbacks - Callback functions
 * @returns {Object} Navigation controller instance
 */
function createNavigationController(cfg, callbacks) {
  const selfAvoiding = createSelfAvoidingNavigation(cfg, callbacks);
  const unstuck = createUnstuckNavigation(cfg, callbacks);

  /**
   * Main navigation tick
   * @param {Object} context - Current navigation context
   * @param {string} context.currentUrl - Current page URL
   * @param {Set} context.visitedUrls - Set of visited locations
   * @param {number} context.stuckCount - Current stuck counter
   * @param {boolean} context.isKeyboardMode - True if keyboard mode enabled
   * @returns {Object} Navigation result
   */
  const tick = (context) => {
    const { currentUrl, visitedUrls, stuckCount, isKeyboardMode } = context || {};

    // Check if either strategy is busy
    if (selfAvoiding.isBusy() || unstuck.isBusy()) {
      return { action: 'none', busy: true };
    }

    // Skip navigation logic if no context provided (busy check only)
    if (!context) {
      return { action: 'none', busy: false };
    }

    // Priority: Self-avoiding when stuck > Unstuck when stuck > Normal movement
    // Self-avoiding only triggers when stuck (not on every revisit)
    if (isKeyboardMode && cfg.selfAvoiding && stuckCount >= cfg.panicThreshold) {
      // Use self-avoiding turn (picks new turn angle) when stuck
      const result = selfAvoiding.executeStep(currentUrl, visitedUrls);
      if (result.action !== 'none') {
        return {
          ...result,
          strategy: 'self-avoiding',
          busy: true
        };
      }
    }
    
    // Fallback to unstuck if self-avoiding didn't trigger
    if (cfg.expOn && stuckCount >= cfg.panicThreshold) {
      const result = unstuck.executeUnstuck(stuckCount, cfg.panicThreshold);
      if (result.action !== 'none') {
        return {
          ...result,
          strategy: 'unstuck',
          busy: true
        };
      }
    }

    // Normal movement (no special navigation needed)
    return {
      action: 'move',
      strategy: 'normal',
      busy: false
    };
  };

  /**
   * Get cumulative turn angle (from either strategy)
   * @returns {number} Total degrees turned
   */
  const getCumulativeTurnAngle = () => {
    return selfAvoiding.getCumulativeTurnAngle() || unstuck.getCumulativeTurnAngle();
  };

  /**
   * Reset all navigation state
   */
  const reset = () => {
    selfAvoiding.reset();
    unstuck.reset();
  };

  /**
   * Get navigation state for debugging
   * @returns {Object} Navigation state
   */
  const getState = () => ({
    selfAvoiding: selfAvoiding.getState(),
    unstuck: unstuck.getState()
  });

  return {
    tick,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle: () => {
      selfAvoiding.resetCumulativeTurnAngle();
      unstuck.resetCumulativeTurnAngle();
    },
    reset,
    getState
  };
}

// Default export for convenience



  // === CORE ENGINE ===
  // State management, tick timing, path recording
  // TO CHANGE ENGINE: Edit src/core/engine.js
  /**
 * Drunk Walker Core Engine
 * Independent navigation logic - works without UI
 * 
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording (this file)
 * - Navigation: Movement algorithms in src/core/navigation.js (pluggable)
 * 
 * TO CHANGE NAVIGATION BEHAVIOR:
 * Edit src/core/navigation.js - NOT this file
 */



const VERSION = '3.67.7-EXP';

const defaultConfig = {
  pace: 2000,
  kbOn: true,      // Keyboard mode ON by default
  expOn: true,     // Experimental mode ON by default (enables unstuck algorithm)
  panicThreshold: 3,
  radius: 50,
  targetX: 0.5,    // 50% of screen width
  targetY: 0.7,    // 70% of screen height
  turnDuration: 600,  // ms to hold ArrowLeft for ~60° turn (fixed)
  collectPath: true,  // Path recording ENABLED by default
  selfAvoiding: true  // Self-avoiding walk ENABLED by default (opt-out)
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = typeof window !== 'undefined' ? window.location.href : '';
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;

  // Path collection (opt-in)
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;  // Initialize from config (default: true)

  // Visited nodes memory for self-avoiding walk
  let visitedUrls = new Set();

  // Cumulative turn angle tracking
  let cumulativeTurnAngle = 0;  // Total degrees turned (for path recording)

  // Navigation controller (pluggable movement algorithms)
  // Will be initialized after extractLocation is defined
  let navigation = null;

  // State getters
  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  // Configuration setters
  const setPace = (newPace) => {
    cfg.pace = newPace;
    // Update interval if running without resetting steps
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setExperimentalMode = (on) => { cfg.expOn = on; };
  const setPolygon = (points) => { poly = points; };
  const setPathCollection = (enabled) => {
    isPathCollectionEnabled = enabled;
    cfg.collectPath = enabled;
    if (!enabled) {
      walkPath = [];  // Clear path if disabled
    }
  };
  const setWalkPath = (path) => { walkPath = path ? [...path] : []; };
  const setSteps = (count) => { steps = count; };
  const getWalkPath = () => [...walkPath];  // Return copy
  const clearWalkPath = () => { walkPath = []; };

  // Extract location from Street View URL (ignores query params that change)
  // Format: https://www.google.com/maps/@lat,lng,zoom... or place_id format
  const extractLocation = (url) => {
    try {
      const urlObj = new URL(url);
      const hash = urlObj.hash || urlObj.pathname;
      // Extract @lat,lng pattern from URL hash or pathname
      const match = hash.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (match) {
        return `${match[1]},${match[2]}`;  // Return "lat,lng" as unique location
      }
      // Fallback: use place_id if available
      const placeMatch = urlObj.searchParams.get('place_id');
      if (placeMatch) {
        return `place:${placeMatch}`;
      }
      // Last resort: use full pathname
      return urlObj.pathname + urlObj.hash;
    } catch (e) {
      return url;  // Return original if parsing fails
    }
  };

  // Initialize navigation controller with stub callbacks
  // Will be updated with real callbacks when setActionHandlers is called
  navigation = createNavigationController(cfg, {
    onKeyPress: null,
    onMouseClick: null,
    onStatusUpdate: null,
    onLongKeyPress: null,
    extractLocation
  });

  const recordStep = () => {
    if (isPathCollectionEnabled) {
      const currentUrl = window.location.href;
      const location = extractLocation(currentUrl);
      walkPath.push({
        url: currentUrl,
        location: location,  // Unique location identifier (lat,lng)
        rotation: cumulativeTurnAngle,  // Actual cumulative turn angle
        direction: 'forward'  // Always forward
      });
      // Track visited locations for self-avoiding walk
      if (cfg.selfAvoiding) {
        visitedUrls.add(location);  // Use location, not full URL
      }
    }
  };
  const isUrlVisited = (location) => visitedUrls.has(location);
  const clearVisitedUrls = () => { visitedUrls.clear(); };
  const getVisitedCount = () => visitedUrls.size;
  const getCumulativeTurnAngle = () => navigation ? navigation.getCumulativeTurnAngle() : cumulativeTurnAngle;
  const resetCumulativeTurnAngle = () => {
    cumulativeTurnAngle = 0;
    if (navigation) navigation.resetCumulativeTurnAngle();
  };

  // Restore visited URLs from a path array
  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    path.forEach(step => {
      if (step.location) {
        visitedUrls.add(step.location);
      } else if (step.url) {
        const loc = extractLocation(step.url);
        if (loc) visitedUrls.add(loc);
      }
    });
  };

  // User interaction handlers
  const setUserMouseDown = (down) => { isUserMouseDown = down; };
  const setIsDrawing = (drawing) => { isDrawing = drawing; };

  // Action callbacks (to be provided by caller)
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  const setActionHandlers = ({ keyPress, mouseClick, statusUpdate, longKeyPress, walkStop }) => {
    onKeyPress = keyPress;
    onMouseClick = mouseClick;
    onStatusUpdate = statusUpdate;
    onLongKeyPress = longKeyPress;
    onWalkStop = walkStop;

    // Reinitialize navigation controller with real callbacks
    // NOTE: Navigation logic is in src/core/navigation.js
    navigation = createNavigationController(cfg, {
      onKeyPress,
      onMouseClick,
      onStatusUpdate: (statusText, _, newStuckCount) => {
        // Update stuck count from navigation callback
        // Navigation returns new stuckCount after verification
        if (newStuckCount !== undefined) {
          stuckCount = newStuckCount;
        }
        if (onStatusUpdate) onStatusUpdate(statusText, steps, stuckCount);
      },
      onLongKeyPress,
      extractLocation
    });
  };

  // Stuck detection (simple URL comparison)
  const updateStuckDetection = () => {
    if (!cfg.expOn) {
      stuckCount = 0;
      return;
    }

    const currentUrl = window.location.href;
    if (currentUrl === lastUrl) {
      stuckCount++;
    } else {
      lastUrl = currentUrl;
      stuckCount = 0;
    }
  };

  const getStatusText = () => {
    if (!cfg.expOn || stuckCount === 0) return 'WALKING';
    if (stuckCount >= cfg.panicThreshold) return `PANIC! (STUCK ${stuckCount})`;
    return `STUCK (${stuckCount})`;
  };

  const calculateClickTarget = () => {
    const cw = window.innerWidth;
    const ch = window.innerHeight;

    // If polygon defined, pick random point inside
    if (poly.length > 2) {
      const minX = Math.min(...poly.map(p => p.x));
      const maxX = Math.max(...poly.map(p => p.x));
      const minY = Math.min(...poly.map(p => p.y));
      const maxY = Math.max(...poly.map(p => p.y));

      let tx, ty, attempts = 0;
      do {
        tx = minX + Math.random() * (maxX - minX);
        ty = minY + Math.random() * (maxY - minY);
        attempts++;
      } while (!inPoly({ x: tx, y: ty }, poly) && attempts < 100);

      return { x: tx, y: ty };
    }

    // Default target with wobble
    const radius = cfg.expOn && stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  // Polygon hit testing (kept for future use)
  const inPoly = (p, vs) => {
    let inside = false;
    for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
      const xi = vs[i].x, yi = vs[i].y;
      const xj = vs[j].x, yj = vs[j].y;
      const intersect = ((yi > p.y) !== (yj > p.y)) &&
        (p.x < (xj - xi) * (p.y - yi) / (yj - yi) + xi);
      if (intersect) inside = !inside;
    }
    return inside;
  };

  // Main navigation tick
  const tick = () => {
    // Skip if user is interacting
    if (isUserMouseDown || isDrawing) return;

    updateStuckDetection();

    if (onStatusUpdate) {
      onStatusUpdate(getStatusText(), steps, stuckCount);
    }

    // Get navigation decision (also checks if busy)
    const navResult = navigation.tick({
      currentUrl: window.location.href,
      visitedUrls,
      stuckCount,
      isKeyboardMode: cfg.kbOn
    });

    // Handle navigation result
    if (navResult.busy) {
      // Navigation is handling the action (turning, moving, verifying)
      // stuckCount will be reset by navigation callback after verification
      steps++;
      recordStep();
      return;
    }

    // Normal movement
    if (cfg.kbOn) {
      // Keyboard mode: press ArrowUp for forward movement
      console.log(`⬆️ Step #${steps + 1}: Moving forward`);
      if (onKeyPress) onKeyPress('ArrowUp');
    } else {
      // Click mode: calculate and click target
      const target = calculateClickTarget();
      console.log(`🖱️ Step #${steps + 1}: Clicking at (${Math.round(target.x)}, ${Math.round(target.y)})`);
      if (onMouseClick) onMouseClick(target.x, target.y);
    }

    // Increment step counter - every tick = one step (time-based, not movement-based)
    steps++;

    // Record step for path collection (after movement)
    recordStep();
  };

  // Control functions
  const start = () => {
    if (status === 'WALKING') return;

    status = 'WALKING';
    // Only reset on first start, not on resume
    if (steps === 0) {
      stuckCount = 0;
      lastUrl = window.location.href;
    }

    if (intervalId) clearInterval(intervalId);
    intervalId = setInterval(tick, cfg.pace);

    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }

    // Submit walk path if collection enabled
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }

    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = '';
    status = 'IDLE';
    cumulativeTurnAngle = 0;  // Reset turn angle on reset
    if (navigation) navigation.reset();  // Reset navigation state
  };

  return {
    // State
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,

    // Configuration
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setExperimentalMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },

    // Visited nodes
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,

    // Turn angle tracking
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    restoreVisitedFromPath,

    // Interaction
    setUserMouseDown,
    setIsDrawing,

    // Handlers
    setActionHandlers,

    // Control
    start,
    stop,
    reset,

    // Direct access for testing
    tick,
    getConfig: () => ({ ...cfg }),

    // Navigation access (for debugging/testing)
    getNavigation: () => navigation,
    getNavigationState: () => navigation ? navigation.getState() : null
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */

const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};

/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas[width][height]') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}

/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Full key event sequence for maximum compatibility
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}

/**
 * Simulate long-press keyboard event (keydown -> hold -> keyup)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Key down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  
  // Hold for duration, then release
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
    if (callback) callback();
  }, duration);
}

/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };

  const target = document.elementFromPoint(x, y) || document.body;

  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));

  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}

/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;

  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };

  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };

  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);

  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Control Panel Management
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '3.67.5-EXP',
    autoStart = true,
    onPathCollectionToggle = null  // Callback for path collection toggle
  } = options;

  let container = null;
  let btn = null;
  let statusEl = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let paceSlider = null;
  let collectCheckbox = null;
  let copyPathBtn = null;
  let updateBtn = null;
  let downloadLogsBtn = null;
  
  // Session logs storage
  const sessionLogs = [];
  const originalConsoleLog = console.log;
  
  // Intercept console.log to capture logs
  console.log = function(...args) {
    const timestamp = new Date().toISOString();
    const message = args.map(arg => 
      typeof arg === 'object' ? JSON.stringify(arg) : String(arg)
    ).join(' ');
    sessionLogs.push(`[${timestamp}] ${message}`);
    originalConsoleLog.apply(console, args);
  };

  // Create UI elements
  const createUI = () => {
    container = document.createElement('div');
    container.id = 'dw-ctrl-panel';
    container.style.cssText = 'position:fixed;top:20px;right:20px;background:rgba(0,0,0,0.9);color:#0f0;padding:15px;font-family:monospace;z-index:999999;border:2px solid #0f0;border-radius:10px;box-shadow:0 0 15px #0f0;min-width:180px;user-select:none;';

    // Title
    const title = document.createElement('div');
    title.innerHTML = `🤪 DRUNK WALKER v${version}<hr style="border-color:#0f0">`;
    container.appendChild(title);

    // Stats
    const stats = document.createElement('div');
    stats.style.margin = '10px 0';
    stats.innerHTML = 'STATUS: <span id="dw-status">IDLE</span><br>STEPS: <span id="dw-steps">0</span><br>VISITED: <span id="dw-visited">0</span>';
    container.appendChild(stats);
    statusEl = stats.querySelector('#dw-status');
    stepsEl = stats.querySelector('#dw-steps');
    visitedEl = stats.querySelector('#dw-visited');

    // Pace control
    const paceLabel = document.createElement('div');
    paceLabel.style.fontSize = '10px';
    paceLabel.innerHTML = 'PACE: <span id="dw-pace-val">2.0</span>s';
    container.appendChild(paceLabel);
    paceValEl = paceLabel.querySelector('#dw-pace-val');

    paceSlider = document.createElement('input');
    paceSlider.type = 'range';
    paceSlider.min = '500';
    paceSlider.max = '5000';
    paceSlider.step = '100';
    paceSlider.value = engine.getConfig().pace;
    paceSlider.style.width = '100%';
    paceSlider.oninput = () => {
      const newPace = parseInt(paceSlider.value);
      if (paceValEl) paceValEl.innerText = (newPace / 1000).toFixed(1);
      engine.setPace(newPace);
    };
    container.appendChild(paceSlider);

    // Path collection toggle (opt-in)
    const collectDiv = document.createElement('div');
    collectDiv.style.fontSize = '10px';
    collectDiv.style.marginTop = '8px';
    collectDiv.style.display = 'flex';
    collectDiv.style.alignItems = 'center';
    collectDiv.style.gap = '5px';
    collectCheckbox = document.createElement('input');
    collectCheckbox.type = 'checkbox';
    collectCheckbox.id = 'dw-record-path';
    collectCheckbox.checked = true;  // Enabled by default
    collectCheckbox.onchange = () => {
      if (onPathCollectionToggle) {
        onPathCollectionToggle(collectCheckbox.checked);
      }
    };
    const collectLabel = document.createElement('label');
    collectLabel.htmlFor = 'dw-record-path';
    collectLabel.innerText = 'Record Path';
    collectLabel.style.cursor = 'pointer';
    collectDiv.appendChild(collectCheckbox);
    collectDiv.appendChild(collectLabel);
    container.appendChild(collectDiv);

    // Self-avoiding walk toggle (opt-in)
    const selfAvoidingDiv = document.createElement('div');
    selfAvoidingDiv.style.fontSize = '10px';
    selfAvoidingDiv.style.marginTop = '4px';
    selfAvoidingDiv.style.display = 'flex';
    selfAvoidingDiv.style.alignItems = 'center';
    selfAvoidingDiv.style.gap = '5px';
    const selfAvoidingCheckbox = document.createElement('input');
    selfAvoidingCheckbox.type = 'checkbox';
    selfAvoidingCheckbox.id = 'dw-self-avoiding';
    selfAvoidingCheckbox.checked = true;  // Enabled by default (opt-out)
    selfAvoidingCheckbox.onchange = () => {
      engine.setSelfAvoiding(selfAvoidingCheckbox.checked);
    };
    const selfAvoidingLabel = document.createElement('label');
    selfAvoidingLabel.htmlFor = 'dw-self-avoiding';
    selfAvoidingLabel.innerText = 'Self-Avoiding Walk';
    selfAvoidingLabel.style.cursor = 'pointer';
    selfAvoidingDiv.appendChild(selfAvoidingCheckbox);
    selfAvoidingDiv.appendChild(selfAvoidingLabel);
    container.appendChild(selfAvoidingDiv);

    // Path export buttons (Copy + Download)
    const exportDiv = document.createElement('div');
    exportDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    // Copy path JSON button
    copyPathBtn = document.createElement('button');
    copyPathBtn.innerText = '📋 Copy';
    copyPathBtn.style.cssText = 'flex:1;padding:6px;background:#0066cc;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    copyPathBtn.onclick = () => {
      const walkPath = engine.getWalkPath();
      if (walkPath.length === 0) {
        alert('No path recorded. Enable "Record Path" and start walking!');
        return;
      }
      const jsonStr = JSON.stringify(walkPath, null, 2);
      navigator.clipboard.writeText(jsonStr).then(() => {
        copyPathBtn.innerText = '✓ Copied!';
        setTimeout(() => {
          copyPathBtn.innerText = '📋 Copy';
        }, 2000);
      }).catch(err => {
        console.error('Failed to copy:', err);
        alert('Failed to copy to clipboard');
      });
    };
    
    // Download path JSON button
    const downloadPathBtn = document.createElement('button');
    downloadPathBtn.innerText = '💾 Download';
    downloadPathBtn.style.cssText = 'flex:1;padding:6px;background:#28a745;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadPathBtn.onclick = () => {
      const walkPath = engine.getWalkPath();
      if (walkPath.length === 0) {
        alert('No path recorded. Enable "Record Path" and start walking!');
        return;
      }
      const jsonStr = JSON.stringify(walkPath, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      downloadPathBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadPathBtn.innerText = '💾 Download';
      }, 2000);
    };
    
    exportDiv.appendChild(copyPathBtn);
    exportDiv.appendChild(downloadPathBtn);
    container.appendChild(exportDiv);

    // Download logs button
    const logsDiv = document.createElement('div');
    logsDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    downloadLogsBtn = document.createElement('button');
    downloadLogsBtn.innerText = '📄 Download Logs';
    downloadLogsBtn.style.cssText = 'width:100%;padding:6px;background:#ff6600;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadLogsBtn.onclick = () => {
      if (sessionLogs.length === 0) {
        alert('No logs recorded yet. Start walking to generate logs!');
        return;
      }
      
      const logContent = sessionLogs.join('\n');
      const blob = new Blob([logContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-logs-${new Date().toISOString().replace(/[:.]/g, '-')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      downloadLogsBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadLogsBtn.innerText = '📄 Download Logs';
      }, 2000);
    };
    
    logsDiv.appendChild(downloadLogsBtn);
    container.appendChild(logsDiv);

    // Restore Walk from JSON button
    const restoreBtn = document.createElement('button');
    restoreBtn.innerText = '📂 Restore Walk';
    restoreBtn.style.cssText = 'width:100%;margin-top:8px;padding:6px;background:#663399;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    restoreBtn.onclick = () => {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json,application/json';
      input.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const walkPath = JSON.parse(event.target.result);
            if (!Array.isArray(walkPath) || walkPath.length === 0) {
              throw new Error('Invalid walk path format');
            }
            
            // Validate path structure
            const firstStep = walkPath[0];
            if (!firstStep.url && !firstStep.location) {
              throw new Error('Invalid path entries');
            }
            
            // Restore walk path
            engine.setWalkPath(walkPath);

            // Restore visited URLs from path
            engine.restoreVisitedFromPath(walkPath);

            // Navigate to last URL in path
            const lastStep = walkPath[walkPath.length - 1];
            if (lastStep.url) {
              window.location.href = lastStep.url;
            }
            
            console.log(`🤪 DRUNK WALKER: Restored walk with ${walkPath.length} steps`);
            alert(`✓ Walk restored!\n\n${walkPath.length} steps loaded\nNavigating to last position...`);
          } catch (err) {
            console.error('Failed to restore walk:', err);
            alert('❌ Failed to restore walk\n\n' + err.message + '\n\nPlease ensure the file is a valid walk JSON export.');
          }
        };
        reader.readAsText(file);
      };
      input.click();
    };
    container.appendChild(restoreBtn);

    // Update script button
    updateBtn = document.createElement('button');
    updateBtn.innerText = '🔄 Update Script';
    updateBtn.style.cssText = 'width:100%;margin-top:8px;padding:6px;background:#cc6600;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    updateBtn.onclick = () => {
      updateScriptFromGitHub();
    };
    container.appendChild(updateBtn);

    // Start/Stop button
    btn = document.createElement('button');
    btn.innerText = '▶ START';
    btn.style.cssText = 'width:100%;margin-top:10px;padding:8px;background:#0f0;color:#000;border:none;font-weight:bold;cursor:pointer;border-radius:5px;';
    btn.onclick = () => {
      if (engine.isNavigating()) {
        engine.stop();
      } else {
        engine.start();
      }
      updateButton();
    };
    container.appendChild(btn);

    document.body.appendChild(container);
  };

  // Update button appearance based on state
  const updateButton = () => {
    if (engine.isNavigating()) {
      btn.innerText = '🔴 STOP';
      btn.style.background = '#f00';
    } else {
      btn.innerText = '▶ START';
      btn.style.background = '#0f0';
    }
  };

  // Status update handler
  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (statusEl) statusEl.innerText = statusText;
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateButton();
  };

  // Initialize
  const init = () => {
    // Wait for DOM to be ready
    if (!document.body) {
      console.error('🤪 DRUNK WALKER: document.body not ready yet');
      return { destroy: () => {} };
    }

    try {
      createUI();
      updateButton();

      if (autoStart) {
        engine.start();
      }

      console.log('🤪 Control panel created successfully');
      return { destroy };
    } catch (error) {
      console.error('🤪 DRUNK WALKER: Failed to initialize UI:', error);
      return { destroy: () => {} };
    }
  };

  // Path collection state getter
  const getPathCollectionEnabled = () => collectCheckbox ? collectCheckbox.checked : false;

  // Update script from GitHub
  const updateScriptFromGitHub = async () => {
    if (!updateBtn) return;
    
    const originalText = updateBtn.innerText;
    updateBtn.innerText = '⏳ Updating...';
    updateBtn.disabled = true;

    try {
      const response = await fetch('https://raw.githubusercontent.com/genaforvena/drunk-walker/main/bookmarklet-console.js');
      if (!response.ok) {
        throw new Error('Failed to fetch latest version');
      }
      
      const latestCode = await response.text();
      
      // Extract version from latest code
      const versionMatch = latestCode.match(/v([\d.]+-EXP)/);
      const latestVersion = versionMatch ? versionMatch[1] : 'unknown';
      
      // Compare with current version
      const currentVersion = version.replace('v', '').replace('-EXP', '');
      
      if (latestVersion.includes(currentVersion)) {
        updateBtn.innerText = '✓ Up to date!';
        setTimeout(() => {
          updateBtn.innerText = originalText;
          updateBtn.disabled = false;
        }, 2000);
        alert(`You're already on the latest version (v${latestVersion})`);
        return;
      }

      // Show update confirmation
      if (confirm(`New version available: v${latestVersion}\n\nThis will copy the latest script to your clipboard. Paste it into the console to update.`)) {
        await navigator.clipboard.writeText(latestCode);
        updateBtn.innerText = '✓ Copied!';
        setTimeout(() => {
          updateBtn.innerText = originalText;
          updateBtn.disabled = false;
        }, 2000);
        alert('Latest script copied to clipboard!\n\nPaste it into the console (F12) and press Enter to update.');
      } else {
        updateBtn.innerText = originalText;
        updateBtn.disabled = false;
      }
    } catch (error) {
      console.error('Update failed:', error);
      updateBtn.innerText = '❌ Failed';
      setTimeout(() => {
        updateBtn.innerText = originalText;
        updateBtn.disabled = false;
      }, 2000);
      alert('Failed to fetch update. Please check your internet connection.');
    }
  };

  // Cleanup
  const destroy = () => {
    engine.stop();
    if (container) {
      container.remove();
      container = null;
    }
  };

  return { init, destroy, onStatusUpdate, getPathCollectionEnabled };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */





// Allow restart by clearing previous instance
if (window.DRUNK_WALKER_ACTIVE) {
  console.log('🤪 Drunk Walker: Restarting...');
  if (window.DRUNK_WALKER) {
    try { window.DRUNK_WALKER.stop(); } catch(e) {}
  }
}

window.DRUNK_WALKER_ACTIVE = true;

console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

// Wait for DOM to be ready before initializing
const initialize = () => {
  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: ui.onStatusUpdate,
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
  }
};

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initialize);
} else {
  initialize();
}

}();