// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v6.1.0-SMART-PANIC - BUNDLED BOOKMARKLET
// Built: 2026-03-22T05:19:33.644Z
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// ═══════════════════════════════════════════════════════════════════════════════

void function initDrunkWalker(){
  // Main entry point handles restart logic now
  
  // === VERSION ===
  const VERSION = '6.1.0-SMART-PANIC';

  // === WHEEL ===
  /**
 * Wheel component for Drunk Walker
 * Manages orientation and turning (left and right)
 */

function createWheel(callbacks) {
  let orientation = 0; // 0-359

  const getOrientation = () => orientation;

  const setOrientation = (newOrientation) => {
    orientation = normalizeAngle(newOrientation);
  };

  const turnLeft = (angle, callback) => {
    // Update orientation IMMEDIATELY (intent-based)
    orientation = normalizeAngle(orientation - angle);

    // Convert angle to duration (10ms per degree as per existing code)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));

    let callbackCalled = false;
    const safeCallback = () => {
      if (callbackCalled) return;
      callbackCalled = true;
      if (callback) callback();
    };

    if (callbacks.onLongKeyPress) {
      callbacks.onLongKeyPress('ArrowLeft', clampedDuration, safeCallback);
      // Safety timeout in case onLongKeyPress doesn't call back
      setTimeout(safeCallback, clampedDuration + 500);
    } else {
      safeCallback();
    }
  };

  const turnRight = (angle, callback) => {
    // Update orientation IMMEDIATELY (intent-based)
    orientation = normalizeAngle(orientation + angle);

    // Convert angle to duration (10ms per degree)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));

    let callbackCalled = false;
    const safeCallback = () => {
      if (callbackCalled) return;
      callbackCalled = true;
      if (callback) callback();
    };

    if (callbacks.onLongKeyPress) {
      callbacks.onLongKeyPress('ArrowRight', clampedDuration, safeCallback);
      // Safety timeout
      setTimeout(safeCallback, clampedDuration + 500);
    } else {
      safeCallback();
    }
  };

  const normalizeAngle = (angle) => {
    angle = angle % 360;
    if (angle < 0) angle += 360;
    return angle;
  };

  return {
    getOrientation,
    setOrientation,
    turnLeft,
    turnRight,
    reset: () => { orientation = 0; }
  };
}


  // === TRAVERSAL ALGORITHMS ===
  /**
 * Traversal Algorithms v5.4.0 - Two Mode System
 * 
 * MODE 1: FORWARD (Exploring)
 * - Go straight, no turns
 * - Until stuck >= 3 (blocked)
 * 
 * MODE 2: RETURN (Retracing)
 * - Detect: current location is in breadcrumbs (we've been here)
 * - Find: nearest node with untried yaws (crossroad candidate)
 * - Navigate: shortest path there, skip straight nodes
 */

function normalizeAngle(angle) {
  angle = angle % 360;
  if (angle < 0) angle += 360;
  return angle;
}

function yawDifference(yaw1, yaw2) {
  let diff = Math.abs(normalizeAngle(yaw1) - normalizeAngle(yaw2));
  if (diff > 180) diff = 360 - diff;
  return diff;
}

/**
 * Calculate angle to turn LEFT to reach targetYaw from currentYaw
 */
function getLeftTurnAngle(currentYaw, targetYaw) {
  let angle = (normalizeAngle(currentYaw) - normalizeAngle(targetYaw) + 360) % 360;
  return angle;
}

function extractYawFromUrl(url) {
  if (!url) return null;
  const match = url.match(/yaw%3D([0-9.]+)/);
  return match ? parseFloat(match[1]) : null;
}

function extractLocationFromUrl(url) {
  if (!url) return null;
  const hashMatch = url.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
  if (hashMatch) {
    return `${hashMatch[1]},${hashMatch[2]}`;
  }
  return null;
}

function predictNextLocation(currentLocation, orientation, stepDistance = 0.0005) {
  if (!currentLocation || typeof currentLocation !== 'string') return null;
  const parts = currentLocation.split(',');
  if (parts.length < 2) return currentLocation;
  const [lat, lng] = parts.map(Number);
  const yawRad = orientation * Math.PI / 180;
  const dLat = Math.cos(yawRad) * stepDistance;
  const dLng = Math.sin(yawRad) * stepDistance / Math.cos(lat * Math.PI / 180);
  return `${(lat + dLat).toFixed(6)},${(lng + dLng).toFixed(6)}`;
}

/**
 * Calculate yaw from recent path history using linear regression
 * Returns the direction of travel based on last N steps
 */
function calculateYawFromPath(breadcrumbs, currentLocation, minSteps = 3) {
  if (!breadcrumbs || breadcrumbs.length < minSteps || !currentLocation) {
    return null;
  }

  // Get last N unique locations from breadcrumbs
  const uniqueLocations = [];
  const seen = new Set();
  for (let i = breadcrumbs.length - 1; i >= 0 && uniqueLocations.length < 5; i--) {
    const loc = breadcrumbs[i];
    if (!seen.has(loc)) {
      seen.add(loc);
      uniqueLocations.push(loc);
    }
  }

  if (uniqueLocations.length < minSteps) {
    return null;
  }

  // Reverse to get chronological order (oldest first)
  uniqueLocations.reverse();

  // Calculate total displacement from first to last
  const first = uniqueLocations[0].split(',').map(Number);
  const last = uniqueLocations[uniqueLocations.length - 1].split(',').map(Number);

  const dLat = last[0] - first[0];
  const dLng = last[1] - first[1];

  // Calculate yaw from displacement
  let yaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
  if (yaw < 0) yaw += 360;

  return Math.round(yaw);
}

/**
 * Calculate yaw from last movement (previous location → current)
 * More accurate for new node correction
 */
function calculateYawFromLastMove(previousLocation, currentLocation) {
  if (!previousLocation || !currentLocation || previousLocation === currentLocation) {
    return null;
  }

  const prev = previousLocation.split(',').map(Number);
  const curr = currentLocation.split(',').map(Number);

  const dLat = curr[0] - prev[0];
  const dLng = curr[1] - prev[1];

  // Calculate yaw from displacement
  let yaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
  if (yaw < 0) yaw += 360;

  return Math.round(yaw);
}

class NodeInfo {
  constructor(location, lat, lng, step) {
    this.location = location;
    this.lat = lat;
    this.lng = lng;
    this.triedYaws = new Set();
    this.successfulYaws = new Set();
    this.connections = new Map();
    this.isStraight = false;
    this.isCrossroad = false;
    this.isDeadEnd = false;
    this.isFullyExplored = false;
  }

  recordAttempt(yaw, success, targetLocation = null) {
    const bucket = Math.round(normalizeAngle(yaw) / 60) * 60 % 360;
    this.triedYaws.add(bucket);
    if (success && targetLocation) {
      this.successfulYaws.add(bucket);
      this.connections.set(bucket, targetLocation);
    }
    this.updateType();
  }

  updateType() {
    const exitCount = this.connections.size;

    // Node classification
    if (this.triedYaws.size >= 6) {
      this.isFullyExplored = true;
      if (exitCount === 1) {
        this.isDeadEnd = true;
      } else if (exitCount === 2) {
        const yaws = Array.from(this.successfulYaws);
        if (yaws.length === 2) {
          this.isStraight = yawDifference(yaws[0], yaws[1]) > 150;
        }
      } else if (exitCount >= 3) {
        this.isCrossroad = true;
      }
    }
  }

  hasUntriedYaws() { return this.triedYaws.size < 6; }

  /**
   * Get untried yaw closest to current orientation
   * @param {number} currentOrientation - Current yaw orientation (optional)
   * @returns {number|null} Closest untried yaw bucket, or null if all tried
   */
  getNextUntriedYaw(currentOrientation = null) {
    if (currentOrientation === null) {
      // Fallback: return first untried (old behavior)
      for (const yaw of [0, 60, 120, 180, 240, 300]) {
        if (!this.triedYaws.has(yaw)) return yaw;
      }
      return null;
    }

    // Find untried yaw closest to current orientation
    const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !this.triedYaws.has(y));
    if (untriedYaws.length === 0) return null;

    let closestYaw = untriedYaws[0];
    let closestDiff = yawDifference(currentOrientation, closestYaw);

    for (const yaw of untriedYaws) {
      const diff = yawDifference(currentOrientation, yaw);
      if (diff < closestDiff) {
        closestDiff = diff;
        closestYaw = yaw;
      }
    }

    return closestYaw;
  }
}

class EnhancedTransitionGraph {
  constructor() {
    this.nodes = new Map();
    this.connections = new Map();
  }

  getOrCreate(location, lat, lng, step = 0) {
    if (!this.nodes.has(location)) {
      this.nodes.set(location, new NodeInfo(location, lat, lng, step));
      this.connections.set(location, new Set());
    }
    return this.nodes.get(location);
  }

  get(location) { return this.nodes.get(location); }

  recordMovement(fromLoc, toLoc, fromYaw, toYaw, step) {
    const fromNode = this.getOrCreate(fromLoc, parseFloat(fromLoc.split(',')[0]), parseFloat(fromLoc.split(',')[1]), step);
    const toNode = this.getOrCreate(toLoc, parseFloat(toLoc.split(',')[0]), parseFloat(toLoc.split(',')[1]), step);

    // Record forward direction at fromNode
    fromNode.recordAttempt(fromYaw, true, toLoc);

    // Record reverse direction at toNode (we can always go back the way we came)
    const reverseYaw = (toYaw + 180) % 360;
    toNode.recordAttempt(reverseYaw, true, fromLoc);

    toNode.entryYaw = toYaw;

    // Bidirectional connection tracking
    if (!this.connections.get(fromLoc).has(toLoc)) {
      this.connections.get(fromLoc).add(toLoc);
    }
    if (!this.connections.get(toLoc).has(fromLoc)) {
      this.connections.get(toLoc).add(fromLoc);
    }
  }

  recordFailedAttempt(location, yaw, step) {
    const parts = location.split(',');
    const node = this.getOrCreate(location, parseFloat(parts[0]), parseFloat(parts[1]), step);
    node.recordAttempt(yaw, false, null);
  }

  /**
   * Find nearest node with untried yaws by walking back through breadcrumbs
   */
  findNearestCrossroadCandidate(currentLocation, breadcrumbs) {
    // Walk backwards through breadcrumbs to find first node with untried yaws
    for (let i = breadcrumbs.length - 1; i >= 0; i--) {
      const loc = breadcrumbs[i];
      if (loc === currentLocation) continue;
      const node = this.nodes.get(loc);
      if (node && node.hasUntriedYaws()) {
        return { node, location: loc, distance: breadcrumbs.length - i };
      }
    }
    return null;
  }

  /**
   * Get path from current location to target through breadcrumbs
   */
  getPathToTarget(currentLocation, targetLocation, breadcrumbs) {
    const currentIndex = breadcrumbs.lastIndexOf(currentLocation);
    const targetIndex = breadcrumbs.lastIndexOf(targetLocation);

    if (currentIndex === -1 || targetIndex === -1) return [];

    // Return path from current to target (walking backwards)
    return breadcrumbs.slice(targetIndex, currentIndex + 1).reverse();
  }
}

/**
 * UNIFIED ALGORITHM v5.4.0 - Two Mode System
 */
function createUnifiedAlgorithm(cfg) {
  const panicThreshold = cfg.panicThreshold || 3;
  let preferredYaw = null;
  let lastSearchAngle = 0;
  let navigationTarget = null;  // {location, targetYaw, path}
  let isReturning = false;

  // Knowledge tracking for intelligent exploration
  let turnedAtNodes = new Set();  // Nodes where we made exploration turn during CURRENT backtrack session
  let fullyExploredNodes = new Set();  // Nodes where ALL 6 buckets have been tried (never re-explore)
  let backtrackCount = 0;  // Count how many times we've backtracked
  let lastBacktrackLocation = null;  // Track where we last started backtracking from

  // Yaw correction tracking
  let yawCorrectedNodes = new Set();  // Nodes where we already corrected yaw (one correction per node)

  // Progress tracking - detect when we're stuck in a local cluster
  let lastNewNodeStep = 0;  // breadcrumbs.length when we last discovered a new node
  let lastNewNodeCount = 0;  // graph.nodes count at last new node
  let consecutiveStraightMoves = 0;  // Count of consecutive straight moves (no turns)
  let lastDecisionWasTurn = false;  // Track if last decision was a turn
  let linearSegmentStart = null;  // Track start of current linear segment
  let traversedSegments = new Set();  // Segments traversed bidirectionally (format: "loc1|loc2")
  let escapeTargetLocation = null;  // Emergency escape target when stuck in loop
  let aggressiveScanCooldown = 0;  // Cooldown after aggressive scan to prevent immediate return mode

  // Wall-following DFS state
  let dfsStack = [];  // Stack of nodes to explore (LIFO for DFS)
  let dfsEntryPoint = null;  // Entry point of current DFS branch
  let wallFollowMode = false;  // True when following left wall back

  const enhancedGraph = new EnhancedTransitionGraph();

  const decide = (context) => {
    const { stuckCount, currentLocation, previousLocation, visitedUrls, breadcrumbs, orientation, isNewNode, isFullyScanned, justArrived, nodeVisitCount } = context;

    console.log(`[DEBUG] decide() called: stuck=${stuckCount}, orientation=${Math.round(orientation)}°, loc=${currentLocation}`);
    console.log(`[DEBUG] breadcrumbs.length=${breadcrumbs.length}, graph.nodes=${enhancedGraph.nodes.size}`);
    console.log(`[DEBUG] isNewNode=${isNewNode}, isFullyScanned=${isFullyScanned}, justArrived=${justArrived}`);

    if (!preferredYaw) preferredYaw = orientation;
    if (!currentLocation) {
      console.log('[DEBUG] No location, returning no turn');
      return { turn: false };
    }

    const currentParts = currentLocation.split(',').map(Number);
    const currentNode = enhancedGraph.getOrCreate(currentLocation, currentParts[0], currentParts[1]);

    console.log(`[DEBUG] currentNode.triedYaws=${[...currentNode.triedYaws].join(',')}, hasUntried=${currentNode.hasUntriedYaws()}`);

    // Track when we discover new nodes
    if (isNewNode) {
      lastNewNodeStep = breadcrumbs.length;
      lastNewNodeCount = enhancedGraph.nodes.size;
    }

    // Detect stagnation: no new nodes for many steps
    const stepsSinceNewNode = breadcrumbs.length - lastNewNodeStep;
    const isStagnant = stepsSinceNewNode > 50 && enhancedGraph.nodes.size > 50;

    if (isStagnant) {
      console.log(`⚠️ STAGNATION: ${stepsSinceNewNode} steps since new node (graph=${enhancedGraph.nodes.size} nodes)`);
    }

    // ═══════════════════════════════════════════════════════════
    // 🗑️ AGGRESSIVE PRUNING: Mark node as fully explored when 5+ yaws tried
    // (1 yaw is how we arrived, 4+ explored = nothing new to find)
    // Also mark as dead-end if only 1 untried yaw remains (the arrival yaw)
    // ═══════════════════════════════════════════════════════════
    const untriedCount = 6 - currentNode.triedYaws.size;
    if (currentNode.triedYaws.size >= 5 || untriedCount <= 1) {
      fullyExploredNodes.add(currentLocation);
    } else if (untriedCount > 1 && fullyExploredNodes.has(currentLocation)) {
      // New yaw discovered - remove from fully explored
      fullyExploredNodes.delete(currentLocation);
    }

    // ═══════════════════════════════════════════════════════════
    // 🚫 NEW NODE: Never turn at new/unsampled nodes - go straight!
    // ═══════════════════════════════════════════════════════════
    if (isNewNode) {
      console.log('[DEBUG] NEW NODE - going straight (no turn)');
      // Remove from fully explored if it was there (fresh visit)
      fullyExploredNodes.delete(currentLocation);

      // Track consecutive straight moves
      if (!lastDecisionWasTurn) {
        consecutiveStraightMoves++;

        // Track linear segment (same orientation, consecutive new nodes)
        if (linearSegmentStart === null) {
          linearSegmentStart = previousLocation || currentLocation;
        }
      } else {
        consecutiveStraightMoves = 1;
        linearSegmentStart = previousLocation || currentLocation;
      }

      console.log(`[DEBUG] consecutiveStraightMoves=${consecutiveStraightMoves}, lastDecisionWasTurn=${lastDecisionWasTurn}`);

      // ═══════════════════════════════════════════════════════════
      // 🎯 AGGRESSIVE EXPLORATION: If we've been moving straight for
      // several nodes, stop and try a side exit before continuing!
      // This prevents walking 100+ nodes down a linear street without
      // checking side paths.
      // ═══════════════════════════════════════════════════════════
      // After 5+ consecutive straight moves, force exploration of a side exit
      // BUT: Skip aggressive scan if we're discovering new nodes (DFS priority!)
      // AND: Only trigger at HIGH-PROBABILITY junctions (≥2 untried yaws)
      if (consecutiveStraightMoves >= 5 && currentNode.hasUntriedYaws() && !isNewNode) {
        const untriedCount = 6 - currentNode.triedYaws.size;
        // Only trigger aggressive scan at junctions with ≥2 untried yaws
        // (high probability of unexplored exits)
        if (untriedCount >= 2) {
          console.log(`🎯 AGGRESSIVE SCAN triggered! consecutiveStraightMoves=${consecutiveStraightMoves}, untriedCount=${untriedCount}`);
          // Pick an untried yaw that's NOT straight ahead
          const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !currentNode.triedYaws.has(y));
          // Find yaw most different from current orientation (side exit, not forward)
          let bestSideYaw = null;
          let bestDiff = 30;  // Minimum difference to be considered "side"

          for (const yaw of untriedYaws) {
            const diff = yawDifference(orientation, yaw);
            // Prefer yaws that are 60-150° from current (side exits, not straight/back)
            if (diff >= 60 && diff <= 150 && diff > bestDiff) {
              bestDiff = diff;
              bestSideYaw = yaw;
            }
          }

          // Fallback: any untried yaw that's not straight ahead
          if (bestSideYaw === null) {
            const forwardYaw = orientation;
            for (const yaw of untriedYaws) {
              if (yawDifference(yaw, forwardYaw) >= 60) {
                bestSideYaw = yaw;
                break;
              }
            }
          }

          if (bestSideYaw !== null) {
            const diff = yawDifference(orientation, bestSideYaw);
            console.log(`  bestSideYaw=${bestSideYaw}, diff=${Math.round(diff)}°`);
            if (diff > 5 && diff < 170) {
              console.log(`🎯 AGGRESSIVE SCAN: After ${consecutiveStraightMoves} straight nodes, trying side yaw ${bestSideYaw}° (diff=${Math.round(diff)}°)`);
              const turnAngle = getLeftTurnAngle(orientation, bestSideYaw);
              const turnDirection = getTurnDirection(orientation, bestSideYaw);
              lastDecisionWasTurn = true;
              aggressiveScanCooldown = 5;  // Don't enter return mode for 5 ticks after aggressive scan
              return { turn: true, angle: turnAngle, direction: turnDirection };
            } else {
              console.log(`  Skipping: diff=${Math.round(diff)}° not in range (5, 170)`);
            }
          } else {
            console.log(`  No suitable side yaw found. untriedYaws=[${untriedYaws.join(',')}]`);
          }
        } else {
          console.log(`  Skipping aggressive scan: only ${untriedCount} untried yaw(s) - low probability junction`);
        }
      }

      lastDecisionWasTurn = false;  // Reset when going straight
      return { turn: false };
    }

    // ═══════════════════════════════════════════════════════════
    // MODE DETECTION: Are we returning (retracing) or exploring?
    // ═══════════════════════════════════════════════════════════
    const lastDifferentIndex = breadcrumbs.findLastIndex(loc => loc !== currentLocation);
    const hasBeenHereBefore = lastDifferentIndex !== -1 && breadcrumbs.slice(0, lastDifferentIndex + 1).includes(currentLocation);
    const isExhausted = !currentNode.hasUntriedYaws();

    console.log(`[DEBUG] hasBeenHereBefore=${hasBeenHereBefore}, isExhausted=${isExhausted}, fullyExplored=${fullyExploredNodes.has(currentLocation)}`);

    // ═══════════════════════════════════════════════════════════
    // 🧱 WALL-FOLLOWING DFS: When hitting dead end, turn LEFT
    // and follow the wall back, exploring missed side paths
    // ═══════════════════════════════════════════════════════════

    // Push nodes with untried yaws onto DFS stack as we pass them
    if (currentNode.hasUntriedYaws() && !fullyExploredNodes.has(currentLocation)) {
      const untriedCount = 6 - currentNode.triedYaws.size;
      // Only push if not already in stack (avoid duplicates)
      const alreadyInStack = dfsStack.some(n => n.location === currentLocation);
      if (!alreadyInStack && untriedCount >= 1) {
        dfsStack.push({ location: currentLocation, untriedCount, orientation });
        console.log(`📚 DFS: Pushed ${currentLocation} to stack (${dfsStack.length} nodes)`);
      }
    }

    // When at fully-explored node with no untried yaws, pop from stack
    if (isExhausted && fullyExploredNodes.has(currentLocation) && dfsStack.length > 0) {
      // Check if current node is the top of stack - if so, pop it (we've explored it)
      if (dfsStack[dfsStack.length - 1].location === currentLocation) {
        dfsStack.pop();
        console.log(`📚 DFS: Popped ${currentLocation} from stack (${dfsStack.length} nodes remaining)`);
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🚨 HIGH REVISIT DETECTION: If we've visited this node too many
    // times, we're stuck in a loop. ESCAPE to nearest crossroad!
    // ═══════════════════════════════════════════════════════════
    const maxRevisits = 5;
    if (nodeVisitCount > maxRevisits) {
      console.log(`🚨 HIGH REVISIT: ${nodeVisitCount} visits to ${currentLocation}! Finding frontier to explore...`);

      // WALL-FOLLOWING: Find node with untried yaws by popping from DFS stack
      // This gives us the most recently discovered unexplored branch
      while (dfsStack.length > 0) {
        const candidate = dfsStack[dfsStack.length - 1];  // Peek top
        const node = enhancedGraph.nodes.get(candidate.location);

        if (node && node.hasUntriedYaws() && !fullyExploredNodes.has(candidate.location)) {
          // Found valid frontier! Navigate there
          const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !node.triedYaws.has(y));
          if (untriedYaws.length >= 1) {
            console.log(`🧱 WALL-FOLLOW: Found frontier ${candidate.location} (${untriedYaws.length} untried yaws)`);
            escapeTargetLocation = candidate.location;

            // Find untried yaw that's LEFT of our approach direction (90-180°)
            const approachYaw = (orientation + 180) % 360;
            let bestYaw = null;
            let bestDiff = 90;  // Minimum for "left" turn

            for (const yaw of untriedYaws) {
              const diff = yawDifference(approachYaw, yaw);
              // Prefer left turns (90-180° from approach)
              if (diff >= 90 && diff <= 180 && diff > bestDiff) {
                bestDiff = diff;
                bestYaw = yaw;
              }
            }

            // Fallback: any untried yaw
            if (bestYaw === null && untriedYaws.length > 0) {
              bestYaw = untriedYaws[0];
              bestDiff = yawDifference(approachYaw, bestYaw);
            }

            if (bestYaw !== null) {
              navigationTarget = {
                location: candidate.location,
                targetYaw: bestYaw,
                distance: dfsStack.length
              };
              isReturning = true;
              consecutiveStraightMoves = 0;
              wallFollowMode = true;
              console.log(`🧱 WALL-FOLLOW: Targeting yaw ${bestYaw}° (diff=${Math.round(bestDiff)}° from approach)`);
              break;
            }
          }
        }

        // Pop invalid entries (fully explored or no untried yaws)
        dfsStack.pop();
        console.log(`📚 DFS: Popped invalid entry, ${dfsStack.length} nodes remaining`);
      }

      if (dfsStack.length === 0) {
        console.log(`🧱 WALL-FOLLOW: DFS stack empty! Graph may be fully explored.`);
      }
    }

    // Reset consecutive straight moves counter when we arrive at a visited node
    if (hasBeenHereBefore) {
      consecutiveStraightMoves = 0;
      lastDecisionWasTurn = false;
      linearSegmentStart = null;  // Reset segment tracking
    }

    // Decrement aggressive scan cooldown
    if (aggressiveScanCooldown > 0) {
      aggressiveScanCooldown--;
    }

    // Detect start of backtrack (hit dead end, now returning)
    // Skip return mode if we just did an aggressive scan (exploring side exit)
    const isBacktracking = (hasBeenHereBefore || isExhausted) && !navigationTarget && aggressiveScanCooldown === 0;

    if (isBacktracking) {
      isReturning = true;

      // Loop detection: if we're backtracking from same location repeatedly, STOP
      if (lastBacktrackLocation === currentLocation) {
        backtrackCount++;
        if (backtrackCount >= 3) {
          console.log(`🛑 LOOP DETECTED! Backtracked from ${currentLocation} ${backtrackCount} times. Stopping to prevent infinite loop.`);
          return { turn: false };  // Stop the bot
        }
      } else {
        backtrackCount = 0;
        lastBacktrackLocation = currentLocation;
      }

      // Navigate to nearest node with untried buckets (skip fully explored)
      const candidate = enhancedGraph.findNearestCrossroadCandidate(currentLocation, breadcrumbs);
      if (candidate) {
        const targetYaw = candidate.node.getNextUntriedYaw(orientation);
        if (targetYaw !== null) {
          navigationTarget = {
            location: candidate.location,
            targetYaw,
            distance: candidate.distance
          };
          console.log(`🔙 RETURN MODE: Navigating to crossroad ${candidate.location} (${candidate.distance} steps away)`);
        }
      }
    } else if (!hasBeenHereBefore && !isExhausted) {
      isReturning = false;
      // Reset backtrack tracking when starting fresh exploration
      turnedAtNodes.clear();
      backtrackCount = 0;
      lastBacktrackLocation = null;
      // Don't clear yawCorrectedNodes - corrections persist across sessions
    }

    // ═══════════════════════════════════════════════════════════
    // NAVIGATION MODE: Actively going to crossroad candidate
    // ═══════════════════════════════════════════════════════════
    if (navigationTarget) {
      if (currentLocation === navigationTarget.location) {
        // Reached target! Try an untried yaw to explore new territory
        const node = enhancedGraph.nodes.get(currentLocation);
        if (node && node.hasUntriedYaws()) {
          const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !node.triedYaws.has(y));

          // Prefer yaw that's different from how we arrived
          const approachYaw = (orientation + 180) % 360;
          let bestYaw = null;
          let bestDiff = 0;

          for (const yaw of untriedYaws) {
            const diff = yawDifference(approachYaw, yaw);
            if (diff > bestDiff) {
              bestDiff = diff;
              bestYaw = yaw;
            }
          }

          if (bestYaw !== null) {
            console.log(`🎯 Reached escape node! Trying untried yaw ${bestYaw}° (diff=${Math.round(bestDiff)}° from approach)`);
            const turnAngle = getLeftTurnAngle(orientation, bestYaw);
            const turnDirection = getTurnDirection(orientation, bestYaw);
            navigationTarget = null;
            escapeTargetLocation = null;
            consecutiveStraightMoves = 0;
            lastDecisionWasTurn = true;
            return { turn: true, angle: turnAngle, direction: turnDirection };
          }
        }

        // No untried yaws - clear target and fall through
        navigationTarget = null;
        escapeTargetLocation = null;
        turnedAtNodes.clear();
        backtrackCount = 0;
        lastBacktrackLocation = null;
      }

      // Navigate by following breadcrumbs back (graph topology, not geometry!)
      // Find the previous node in the breadcrumb trail that leads to target
      const targetIndex = breadcrumbs.lastIndexOf(navigationTarget.location);
      const currentIndex = breadcrumbs.lastIndexOf(currentLocation);

      let yawToNavigate = null;

      if (targetIndex !== -1 && currentIndex !== -1 && targetIndex < currentIndex) {
        // Navigate to previous breadcrumb (closer to target)
        const previousInPath = breadcrumbs[currentIndex - 1];
        if (previousInPath && previousInPath !== currentLocation) {
          const prevParts = previousInPath.split(',').map(Number);
          const dLat = prevParts[0] - currentParts[0];
          const dLng = prevParts[1] - currentParts[1];
          yawToNavigate = Math.atan2(dLng, dLat) * 180 / Math.PI;
          if (yawToNavigate < 0) yawToNavigate += 360;
          console.log(`[DEBUG] NAVIGATION: Following breadcrumb to ${previousInPath} (target: ${navigationTarget.location})`);
        }
      }

      // Fallback: if breadcrumb navigation failed, use geometric approach
      if (yawToNavigate === null) {
        const targetParts = navigationTarget.location.split(',').map(Number);
        const dLat = targetParts[0] - currentParts[0];
        const dLng = targetParts[1] - currentParts[1];
        yawToNavigate = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (yawToNavigate < 0) yawToNavigate += 360;
        console.log(`[DEBUG] NAVIGATION: Using geometric fallback to ${navigationTarget.location}`);
      }

      // ═══════════════════════════════════════════════════════════
      // 🎯 FORWARD MOMENTUM: If node has untried yaws close to current
      // orientation, try those FIRST before continuing navigation
      // This ensures we explore side paths instead of just passing through
      // ═══════════════════════════════════════════════════════════
      if (currentNode.hasUntriedYaws()) {
        // Calculate forward bearing (direction of travel from previous node)
        let forwardBearing = orientation;  // Default to current orientation
        if (previousLocation) {
          const prevParts = previousLocation.split(',').map(Number);
          const dLat = currentParts[0] - prevParts[0];
          const dLng = currentParts[1] - prevParts[1];
          forwardBearing = Math.atan2(dLng, dLat) * 180 / Math.PI;
          if (forwardBearing < 0) forwardBearing += 360;
        }

        // Find untried yaw closest to FORWARD BEARING (not current orientation!)
        const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !currentNode.triedYaws.has(y));
        let bestUntiredYaw = null;
        let bestDiff = 90;  // Only consider yaws within 90° of forward

        for (const untriedYaw of untriedYaws) {
          const diffToForward = yawDifference(forwardBearing, untriedYaw);
          if (diffToForward < bestDiff) {
            bestDiff = diffToForward;
            bestUntiredYaw = untriedYaw;
          }
        }

        // If we found an untried yaw within 90° of forward, try it!
        if (bestUntiredYaw !== null && bestDiff <= 90) {
          console.log(`🎯 FORWARD PRIORITY: Untired yaw ${bestUntiredYaw}° is ${Math.round(bestDiff)}° from forward bearing ${Math.round(forwardBearing)}° - trying first!`);
          const turnAngle = getLeftTurnAngle(orientation, bestUntiredYaw);
          const turnDirection = getTurnDirection(orientation, bestUntiredYaw);
          consecutiveStraightMoves = 0;  // Reset on turn
          lastDecisionWasTurn = true;
          return { turn: true, angle: turnAngle, direction: turnDirection };
        }
      }

      const diff = yawDifference(orientation, yawToNavigate);

      // If stuck while navigating, fall through to PANIC mode
      if (stuckCount >= panicThreshold) {
        console.log(`[DEBUG] Stuck while navigating (stuck=${stuckCount}), falling through to PANIC`);
        // Clear navigation target so PANIC can work
        // navigationTarget stays set but we'll handle the stuck
      } else if (diff < 30) {
        return { turn: false };  // Move forward toward target
      } else {
        const turnAngle = getLeftTurnAngle(orientation, yawToNavigate);
        const turnDirection = getTurnDirection(orientation, yawToNavigate);
        consecutiveStraightMoves = 0;  // Reset on turn
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };  // Turn toward target
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🚨 PANIC MODE: If stuck for 3+ heartbeats, MUST turn
    // ═══════════════════════════════════════════════════════════
    console.log(`[DEBUG] Checking PANIC: stuckCount=${stuckCount} >= panicThreshold=${panicThreshold}? ${stuckCount >= panicThreshold}`);
    if (stuckCount >= panicThreshold) {
      // First, try any untried yaw (closest to current orientation)
      const nextYaw = currentNode.getNextUntriedYaw(orientation);
      console.log(`[DEBUG] PANIC MODE: nextYaw=${nextYaw}, successfulYaws=${[...currentNode.successfulYaws].join(',')}`);

      if (nextYaw !== null) {
        const turnAngle = getLeftTurnAngle(orientation, nextYaw);
        const turnDirection = getTurnDirection(orientation, nextYaw);
        console.log(`🚨 PANIC! Stuck ${stuckCount}x. Trying untried yaw ${nextYaw}° (angle=${Math.round(turnAngle)}° ${turnDirection})`);
        consecutiveStraightMoves = 0;  // Reset on turn
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      } else if (currentNode.successfulYaws.size > 0) {
        // All buckets tried but still stuck - retry a successful exit
        // Pick random successful yaw (one of them must work - we came from somewhere!)
        const successfulYawsArray = Array.from(currentNode.successfulYaws);
        const randomSuccessfulYaw = successfulYawsArray[Math.floor(Math.random() * successfulYawsArray.length)];
        const turnAngle = getLeftTurnAngle(orientation, randomSuccessfulYaw);
        const turnDirection = getTurnDirection(orientation, randomSuccessfulYaw);
        console.log(`🚨 PANIC! All buckets tried. Retrying successful yaw ${randomSuccessfulYaw}° (angle=${Math.round(turnAngle)}° ${turnDirection})`);
        consecutiveStraightMoves = 0;  // Reset on turn
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      } else {
        // TRULY STUCK - No successful exits recorded (shouldn't happen with bidirectional recording)
        // This means we have a data inconsistency - log error and try to recover
        console.log(`🚨 SPIN DETECTED! At ${currentLocation} - all ${currentNode.triedYaws.size} buckets tried, no successful exits!`);
        console.log(`   Tried yaw buckets: ${[...currentNode.triedYaws].join(', ')}`);
        console.log(`   This should not happen - every node should have at least the reverse direction recorded`);

        // Emergency: use entryYaw if available (go back the way we came)
        if (currentNode.entryYaw !== undefined && currentNode.entryYaw !== null) {
          const reverseYaw = (currentNode.entryYaw + 180) % 360;
          const turnAngle = getLeftTurnAngle(orientation, reverseYaw);
          const turnDirection = getTurnDirection(orientation, reverseYaw);
          console.log(`🚨 EMERGENCY! Using entryYaw ${currentNode.entryYaw}° → reverse ${reverseYaw}° (angle=${Math.round(turnAngle)}° ${turnDirection})`);
          return { turn: true, angle: turnAngle, direction: turnDirection };
        }

        // Last resort: stop the bot - we're truly stuck with no way out
        console.log(`🛑 CRITICAL: No escape route found. Bot cannot continue from this location.`);
        return { turn: false };  // Don't turn - let the bot stop naturally
      }
    }

    // ═══════════════════════════════════════════════════════════
    // FORWARD MODE: At node with untried yaws - try them
    // ═══════════════════════════════════════════════════════════

    // 🎯 STAGNATION ESCAPE: If no new nodes for a while, find boundary nodes
    // Boundary = nodes with untried yaws that are furthest from current position
    if (isStagnant && !navigationTarget) {
      // Find the oldest node in breadcrumbs with untried yaws (boundary exploration)
      const currentIndex = breadcrumbs.lastIndexOf(currentLocation);
      for (let i = 0; i < Math.min(breadcrumbs.length - 1, 100); i++) {
        const oldLoc = breadcrumbs[i];
        if (oldLoc === currentLocation) continue;
        const oldNode = enhancedGraph.nodes.get(oldLoc);
        if (oldNode && oldNode.hasUntriedYaws() && !fullyExploredNodes.has(oldLoc)) {
          const targetYaw = oldNode.getNextUntriedYaw(orientation);
          navigationTarget = {
            location: oldLoc,
            targetYaw,
            distance: Math.abs(currentIndex - i)
          };
          console.log(`🎯 BOUNDARY: Stagnation escape! Targeting boundary node ${oldLoc} (${Math.abs(currentIndex - i)} steps back)`);
          isReturning = true;
          break;
        }
      }
    }

    if (currentNode.hasUntriedYaws()) {
      // Calculate forward bearing (direction of travel from previous node)
      let forwardBearing = orientation;  // Default to current orientation
      if (previousLocation) {
        const prevParts = previousLocation.split(',').map(Number);
        const currentParts = currentLocation.split(',').map(Number);
        const dLat = currentParts[0] - prevParts[0];
        const dLng = currentParts[1] - prevParts[1];
        forwardBearing = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (forwardBearing < 0) forwardBearing += 360;
      }

      // Find untried yaw closest to FORWARD BEARING (not current orientation!)
      const untriedYaws = [0, 60, 120, 180, 240, 300].filter(y => !currentNode.triedYaws.has(y));
      let bestUntiredYaw = null;
      let bestDiff = Infinity;

      for (const yaw of untriedYaws) {
        const diffToForward = yawDifference(forwardBearing, yaw);
        if (diffToForward < bestDiff) {
          bestDiff = diffToForward;
          bestUntiredYaw = yaw;
        }
      }

      const nextYaw = bestUntiredYaw;
      console.log(`[DEBUG] FORWARD MODE: nextYaw=${nextYaw}, forwardBearing=${Math.round(forwardBearing)}°, orientation=${Math.round(orientation)}°`);
      if (nextYaw !== null) {
        const diff = yawDifference(orientation, nextYaw);
        console.log(`[DEBUG] yaw diff=${diff}°`);
        if (diff > 5 && diff < 355) {
          console.log(`🔍 Node ${currentLocation.split(',')[0]}...: Trying yaw ${nextYaw}° (${currentNode.triedYaws.size}/6), forward bearing=${Math.round(forwardBearing)}°`);
          const turnAngle = getLeftTurnAngle(orientation, nextYaw);
          const turnDirection = getTurnDirection(orientation, nextYaw);
          consecutiveStraightMoves = 0;  // Reset on turn
          lastDecisionWasTurn = true;
          linearSegmentStart = null;  // Reset segment tracking on turn
          return { turn: true, angle: turnAngle, direction: turnDirection };
        } else {
          // Already pointing close enough, just move forward
          console.log('[DEBUG] Already facing target yaw, moving forward');
          return { turn: false };
        }
      }
    }

    // ═══════════════════════════════════════════════════════════
    // 🧱 WALL-FOLLOWING: At dead end - turn LEFT (90-180°) to follow wall
    // ═══════════════════════════════════════════════════════════
    if (isExhausted && fullyExploredNodes.has(currentLocation)) {
      // Calculate approach direction (where we came from)
      let approachYaw = orientation;
      if (previousLocation) {
        const prevParts = previousLocation.split(',').map(Number);
        const currentParts = currentLocation.split(',').map(Number);
        const dLat = currentParts[0] - prevParts[0];
        const dLng = currentParts[1] - prevParts[1];
        approachYaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (approachYaw < 0) approachYaw += 360;
        // Approach yaw is opposite of travel direction
        approachYaw = (approachYaw + 180) % 360;
      }

      // Try to find untried yaw that's LEFT of approach (90-180°)
      const allYaws = [0, 60, 120, 180, 240, 300];
      let bestYaw = null;
      let bestDiff = 90;

      for (const yaw of allYaws) {
        const diff = yawDifference(approachYaw, yaw);
        // Prefer left turns (90-180° from approach)
        if (diff >= 90 && diff <= 180 && diff > bestDiff) {
          bestDiff = diff;
          bestYaw = yaw;
        }
      }

      // Fallback: try any yaw we haven't tried recently
      if (bestYaw === null) {
        for (const yaw of allYaws) {
          const diff = yawDifference(approachYaw, yaw);
          if (diff > bestDiff) {
            bestDiff = diff;
            bestYaw = yaw;
          }
        }
      }

      if (bestYaw !== null) {
        const diff = yawDifference(orientation, bestYaw);
        console.log(`🧱 WALL-FOLLOW: Dead end! Turning LEFT to yaw ${bestYaw}° (diff=${Math.round(diff)}° from orientation)`);
        const turnAngle = getLeftTurnAngle(orientation, bestYaw);
        const turnDirection = getTurnDirection(orientation, bestYaw);
        consecutiveStraightMoves = 0;
        lastDecisionWasTurn = true;
        wallFollowMode = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }
    }

    // ═══════════════════════════════════════════════════════════
    // FALLBACK: All buckets tried but not stuck - retry successful exit
    // ═══════════════════════════════════════════════════════════
    if (currentNode.successfulYaws.size > 0) {
      const successfulYawsArray = Array.from(currentNode.successfulYaws);
      const randomSuccessfulYaw = successfulYawsArray[Math.floor(Math.random() * successfulYawsArray.length)];
      const diff = yawDifference(orientation, randomSuccessfulYaw);
      console.log(`[DEBUG] FALLBACK: Retrying successful yaw ${randomSuccessfulYaw}°, diff=${diff}°`);
      if (diff > 5 && diff < 355) {
        const turnAngle = getLeftTurnAngle(orientation, randomSuccessfulYaw);
        consecutiveStraightMoves = 0;  // Reset on turn
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: getTurnDirection(orientation, randomSuccessfulYaw) };
      }
      // Already facing it, move forward
      return { turn: false };
    }

    // ═══════════════════════════════════════════════════════════
    // 🧭 YAW CORRECTION (LOWEST PRIORITY): Only if no other algorithm applied
    // ═══════════════════════════════════════════════════════════
    // Only correct if:
    // - Just arrived at this node (first decision here)
    // - Haven't corrected at this node yet
    // - Drift is significant (>15°)
    // - No other algorithm decision was made
    const pathYaw = previousLocation && previousLocation !== currentLocation
      ? calculateYawFromLastMove(previousLocation, currentLocation)
      : (breadcrumbs.length >= 3 ? calculateYawFromPath(breadcrumbs, currentLocation, 3) : null);

    const hasCorrectedHere = yawCorrectedNodes.has(currentLocation);

    if (pathYaw !== null && !hasCorrectedHere && justArrived) {
      const orientationDiff = yawDifference(orientation, pathYaw);

      // Only correct if drift is significant (>15°)
      if (orientationDiff > 15 && orientationDiff < 165) {
        yawCorrectedNodes.add(currentLocation);
        const turnDirection = getTurnDirection(orientation, pathYaw);
        console.log(`🧭 YAW CORRECTION (fallback): ${Math.round(orientation)}° → ${pathYaw}° (diff=${Math.round(orientationDiff)}°) ${turnDirection} at ${currentLocation}`);

        const turnAngle = getLeftTurnAngle(orientation, pathYaw);
        consecutiveStraightMoves = 0;  // Reset on turn
        lastDecisionWasTurn = true;
        return { turn: true, angle: turnAngle, direction: turnDirection };
      }
    }

    // ═══════════════════════════════════════════════════════════
    // FORWARD MODE: Go straight (no turn)
    // ═══════════════════════════════════════════════════════════
    console.log('[DEBUG] FORWARD MODE: Going straight (no turn)');
    return { turn: false };
  };

  /**
   * Determine optimal turn direction (left or right)
   * Returns 'right' if turning right is shorter, otherwise 'left'
   */
  function getTurnDirection(currentYaw, targetYaw) {
    const leftAngle = getLeftTurnAngle(currentYaw, targetYaw);
    const rightAngle = (360 - leftAngle) % 360;

    // Turn right if it's shorter (less than 180°)
    return rightAngle < leftAngle ? 'right' : 'left';
  }

  return {
    decide,
    enhancedGraph,
    isReturning: () => isReturning,
    getNavigationTarget: () => navigationTarget
  };
}

const createDefaultAlgorithm = createUnifiedAlgorithm;
const createExplorationAlgorithm = createUnifiedAlgorithm;
const createSurgicalAlgorithm = createUnifiedAlgorithm;
const createHunterAlgorithm = createUnifiedAlgorithm;


  // === NAVIGATION COMPATIBILITY LAYER ===
  /**
 * Navigation Strategies - Compatibility Wrapper for v4.0.0+
 * This file maintains the old API for tests and bundle validation
 * but uses the new Traversal/Wheel architecture.
 */

function createProactiveAvoidance(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeProactiveAvoidance: (yaw, loc, visited) => {
      const result = algorithm.decide({ stuckCount: 0, currentLocation: loc, visitedUrls: visited, orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createUnstuckNavigation(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeUnstuck: (stuckCount, panicThreshold, yaw) => {
      const result = algorithm.decide({ stuckCount, currentLocation: '', visitedUrls: new Set(), orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createNavigationController(cfg, callbacks) {
  return {
    tick: () => ({ action: 'move', strategy: 'normal', busy: false }),
    getCumulativeTurnAngle: () => 0,
    resetCumulativeTurnAngle: () => {},
    reset: () => {},
    getState: () => ({ globalOrientation: 0, proactive: { state: 'IDLE' }, unstuck: { state: 'IDLE' } })
  };
}

const __default_export = {
  createProactiveAvoidance,
  createUnstuckNavigation,
  createNavigationController
};


  // === CORE ENGINE ===
  /**
 * Drunk Walker Core Engine v5.3.0-STUCK-TYPE
 * 
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording
 * - Wheel: Orientation management
 * - Traversal: Decision-making with stuck type detection
 */

const __export_dummy = { VERSION };

const defaultConfig = {
  pace: 2000,
  kbOn: true,
  panicThreshold: 3,
  radius: 50,
  targetX: 0.4,
  targetY: 0.8,
  turnDuration: 600,
  collectPath: true,
  selfAvoiding: true
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = null;
  let lastUrlYaw = null;
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;

  // Path collection
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;

  // Visited nodes memory
  let visitedUrls = new Map();
  let breadcrumbs = [];

  // Track previous location for movement recording
  let previousLocation = null;
  let previousYaw = null;
  let lastDifferentLocation = null;  // Track last location that was different from current

  // Turn state - prevent oscillation
  let isTurning = false;  // True while executing a turn
  let turnCompleted = false;  // Set to true when turn finishes
  let ticksSinceTurn = 0;  // Count ticks after turn completes
  const TURNS_COOLDOWN_TICKS = 3;  // Wait 3 ticks after turn before deciding to turn again
  let awaitingStepResult = false;  // True after turn+step, waiting to see if we moved

  // Action callbacks
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  const extractLocation = (url) => {
    try {
      const hashMatch = url.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (hashMatch) return `${hashMatch[1]},${hashMatch[2]}`;
    } catch (e) {}
    return null;
  };

  const extractYaw = (url) => {
    if (!url) return null;
    // Match both &yaw=123 and 75y,123h formats
    const match = url.match(/yaw[=%]3D?([0-9.]+)/i) || url.match(/,([0-9.]+)h/i);
    return match ? parseFloat(match[1]) : null;
  };

  const wheelCallbacks = {
    onLongKeyPress: null
  };
  const wheel = createWheel(wheelCallbacks);

  let algorithm = createDefaultAlgorithm(cfg);

  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  const setPace = (newPace) => {
    cfg.pace = newPace;
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setPolygon = (newPoly) => { poly = newPoly || []; };
  const setPathCollection = (enabled) => { isPathCollectionEnabled = enabled; };
  const setWalkPath = (path) => { walkPath = path || []; };
  const setSteps = (newSteps) => { steps = newSteps; };
  const getWalkPath = () => walkPath;
  const clearWalkPath = () => { walkPath = []; };
  const getVisitedCount = () => visitedUrls.size;
  const clearVisitedUrls = () => { visitedUrls.clear(); breadcrumbs = []; };
  const isUrlVisited = (url) => visitedUrls.has(extractLocation(url));
  const getCurrentYaw = () => wheel.getOrientation();
  const resetCurrentYaw = () => wheel.setOrientation(0);
  let cumulativeTurnAngle = 0;
  const getCumulativeTurnAngle = () => cumulativeTurnAngle;
  const resetCumulativeTurnAngle = () => { cumulativeTurnAngle = 0; };

  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    breadcrumbs = [];
    for (const step of path) {
      const loc = extractLocation(step.url);
      if (loc) {
        visitedUrls.set(loc, (visitedUrls.get(loc) || 0) + 1);
        breadcrumbs.push(loc);
      }
    }
  };

  const setUserMouseDown = (val) => { isUserMouseDown = val; };
  const setIsDrawing = (val) => { isDrawing = val; };
  const setActionHandlers = (handlers) => {
    onKeyPress = handlers.keyPress || null;
    onMouseClick = handlers.mouseClick || null;
    onStatusUpdate = handlers.statusUpdate || null;
    onLongKeyPress = handlers.longKeyPress || null;
    onWalkStop = handlers.walkStop || null;

    // Update persistent wheel callbacks
    wheelCallbacks.onLongKeyPress = onLongKeyPress;
  };

  const recordStep = () => {
    if (!isPathCollectionEnabled) return;
    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    const currentLocation = extractLocation(currentUrl);
    walkPath.push({ url: currentUrl, timestamp: Date.now() });
    if (currentLocation) {
      visitedUrls.set(currentLocation, (visitedUrls.get(currentLocation) || 0) + 1);
      if (breadcrumbs.length === 0 || breadcrumbs[breadcrumbs.length - 1] !== currentLocation) {
        breadcrumbs.push(currentLocation);
      }
      if (breadcrumbs.length > 200) breadcrumbs.shift();  // Keep last 200 for loop detection
    }
  };

  const calculateClickTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1920;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1080;
    const tx = cfg.targetX * cw;
    const ty = cfg.targetY * ch;
    return { x: tx, y: ty };
  };

  const calculateTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1920;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1080;

    if (poly.length > 0 && isDrawing) {
      const last = poly[poly.length - 1];
      return { x: last.x * cw, y: last.y * ch };
    }

    const radius = stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  const tick = () => {
    console.log(`[DEBUG] tick() START - status=${status}, isUserMouseDown=${isUserMouseDown}, isDrawing=${isDrawing}`);

    if (isUserMouseDown || isDrawing || status !== 'WALKING') {
      console.log('[DEBUG] tick() SKIP - conditions not met');
      return;
    }

    // Increment ticks since turn (for cooldown - prevent rapid re-turning)
    if (ticksSinceTurn < TURNS_COOLDOWN_TICKS + 1) {
      ticksSinceTurn++;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : (lastUrl || '');
    const currentLocation = extractLocation(currentUrl);
    const currentYaw = extractYaw(currentUrl);

    console.log(`[DEBUG] currentUrl=${currentUrl.substring(0, 80)}...`);
    console.log(`[DEBUG] currentLocation=${currentLocation}, currentYaw=${currentYaw}, previousLocation=${previousLocation}`);

    // 1. Stuck detection (Location based heartbeat)
    if (currentLocation && previousLocation && currentLocation === previousLocation) {
      stuckCount++;
      console.log(`[DEBUG] STUCK DETECTED - same location, stuckCount=${stuckCount}`);
    } else if (currentLocation && previousLocation && currentLocation !== previousLocation) {
      console.log(`[DEBUG] LOCATION CHANGED - resetting stuckCount and turn cooldown`);
      stuckCount = 0;
      ticksSinceTurn = TURNS_COOLDOWN_TICKS;  // Reset cooldown - we moved successfully
      // Track that we just arrived at a different location
      if (currentLocation !== lastDifferentLocation) {
        lastDifferentLocation = currentLocation;
      }
    }

    // 2. Sync orientation with URL ONLY if it changed since last heartbeat
    // Use 1 degree threshold to ignore minor floating point jitter
    if (currentYaw !== null && (lastUrlYaw === null || Math.abs(currentYaw - lastUrlYaw) > 1.0)) {
      console.log(`[DEBUG] Sync wheel orientation: lastUrlYaw=${lastUrlYaw}, currentYaw=${currentYaw}`);
      wheel.setOrientation(currentYaw);
      lastUrlYaw = currentYaw;
    }

    // 3. LOGGING (Critical for debugging)
    console.log(`💓 [${steps}] STUCK: ${stuckCount} | YAW: ${Math.round(wheel.getOrientation())}° | LOC: ${currentLocation}`);
    console.log(`   🔗 ${currentUrl}`);

    // 4. Record result of PREVIOUS heartbeat in the graph
    if (previousLocation && algorithm.enhancedGraph) {
      if (currentLocation && currentLocation !== previousLocation) {
        algorithm.enhancedGraph.recordMovement(
          previousLocation,
          currentLocation,
          previousYaw !== null ? previousYaw : wheel.getOrientation(),
          currentYaw || wheel.getOrientation(),
          steps
        );
      } else if (currentLocation === previousLocation) {
        // We are still at the same spot after an ArrowUp press
        algorithm.enhancedGraph.recordFailedAttempt(
          previousLocation,
          previousYaw !== null ? previousYaw : wheel.getOrientation(),
          steps
        );
      }
    }

    // 5. Decision time
    // Check if this is a new node or already visited
    const nodeVisitCount = visitedUrls.get(currentLocation) || 0;
    const isNewNode = nodeVisitCount === 0;
    const isStationary = currentLocation && previousLocation && currentLocation === previousLocation;

    // Track if we just arrived at this location (first tick after movement)
    const justArrived = currentLocation && previousLocation && currentLocation !== previousLocation;

    // Get node info from graph to check if fully scanned
    const nodeInfo = currentLocation ? algorithm.enhancedGraph.get(currentLocation) : null;
    const isFullyScanned = nodeInfo ? nodeInfo.triedYaws.size >= 6 : false;

    console.log(`[DEBUG] isStationary=${isStationary}, isNewNode=${isNewNode}, justArrived=${justArrived}, nodeVisitCount=${nodeVisitCount}, isFullyScanned=${isFullyScanned}`);

    // Check step result from previous turn+step attempt
    if (awaitingStepResult) {
      if (currentLocation !== previousLocation) {
        console.log('[DEBUG] Step succeeded! Location changed.');
      } else {
        console.log('[DEBUG] Step failed! Still at same location - record failed attempt.');
      }
      awaitingStepResult = false;  // Now we can make new decisions
    }

    let decision = { turn: false };

    // Make turn decisions when:
    // 1. Stationary at a node (not mid-movement) - normal case
    // 2. Just arrived at ANY node (new or visited) - allow yaw correction
    // But NOT when:
    // - Already turning
    // - Waiting for step result
    // - Turn cooldown active
    const shouldMakeDecision = !isTurning && !awaitingStepResult && ticksSinceTurn >= TURNS_COOLDOWN_TICKS &&
      (isStationary || justArrived);

    if (shouldMakeDecision) {
      const context = {
        url: currentUrl,
        currentLocation: currentLocation,
        previousLocation: previousLocation,  // For yaw correction at new nodes
        visitedUrls,
        breadcrumbs,
        stuckCount,
        orientation: wheel.getOrientation(),
        isNewNode,
        isFullyScanned,
        justArrived,
        nodeVisitCount
      };

      console.log(`[DEBUG] ticksSinceTurn=${ticksSinceTurn}, calling algorithm.decide()...`);
      decision = algorithm.decide(context);
      console.log(`[DEBUG] decision=${JSON.stringify(decision)}`);
    } else if (isTurning) {
      console.log('[DEBUG] Skipping decision - already turning');
    } else if (!isStationary && !isNewNode) {
      console.log('[DEBUG] Skipping decision - moving through visited node');
    } else if (ticksSinceTurn < TURNS_COOLDOWN_TICKS) {
      console.log(`[DEBUG] Skipping decision - turn cooldown active (${ticksSinceTurn}/${TURNS_COOLDOWN_TICKS})`);
    }

    // 6. Action: Turn (Left or Right)
    if (decision.turn) {
      const angle = decision.angle || 60;
      const direction = decision.direction || 'left';  // 'left' or 'right'

      console.log(`   🔄 ACTION: Turning ${direction.toUpperCase()} ${angle}°`);
      isTurning = true;
      turnCompleted = false;

      // Skip stepping when turning - let the turn complete first
      previousYaw = wheel.getOrientation();

      const turnCallback = () => {
        console.log('[DEBUG] Turn callback executed - pressing ArrowUp');
        isTurning = false;
        turnCompleted = true;
        ticksSinceTurn = 0;  // Reset cooldown - turn just completed
        awaitingStepResult = true;  // Wait for next tick to see if we moved

        // After turn completes, update state and trigger next tick
        previousLocation = currentLocation;
        previousYaw = wheel.getOrientation();
        lastUrl = currentUrl;
        steps++;
        recordStep();
        if (onStatusUpdate) {
          onStatusUpdate(status, steps, stuckCount);
        }
        // Trigger immediate step after turn completes
        if (cfg.kbOn) {
          if (onKeyPress) onKeyPress('ArrowUp');
        } else {
          const target = calculateClickTarget();
          if (onMouseClick) onMouseClick(target.x, target.y);
        }
      };

      if (direction === 'right') {
        wheel.turnRight(angle, turnCallback);
      } else {
        wheel.turnLeft(angle, turnCallback);
      }

      cumulativeTurnAngle += angle;
      console.log('[DEBUG] tick() RETURN EARLY - waiting for turn to complete');
      return; // Exit tick early - don't step until turn completes
    }

    // 7. Action: Always Step (The Heartbeat)
    previousLocation = currentLocation;
    previousYaw = wheel.getOrientation();
    lastUrl = currentUrl;

    if (cfg.kbOn) {
      if (onKeyPress) onKeyPress('ArrowUp');
    } else {
      const target = calculateClickTarget();
      if (onMouseClick) onMouseClick(target.x, target.y);
    }

    steps++;
    recordStep();

    if (onStatusUpdate) {
      onStatusUpdate(status, steps, stuckCount);
    }
    console.log('[DEBUG] tick() END');
  };

  const start = () => {
    console.log(`[DEBUG] start() called - current status=${status}, intervalId=${intervalId ? 'set' : 'null'}`);

    // Aggressively clear any existing interval
    if (intervalId) {
      console.log('[DEBUG] start() clearing existing interval before start');
      clearInterval(intervalId);
      // Remove from global tracking
      if (window.__DRUNK_WALKER_INTERVALS__) {
        window.__DRUNK_WALKER_INTERVALS__.delete(intervalId);
      }
      intervalId = null;
    }

    if (status === 'WALKING') {
      console.log('[DEBUG] start() ABORT - already walking');
      return;
    }
    status = 'WALKING';
    if (steps === 0) {
      stuckCount = 0;
      lastUrl = null;
    }
    intervalId = setInterval(tick, cfg.pace);
    // Track interval globally
    if (window.__DRUNK_WALKER_INTERVALS__) {
      window.__DRUNK_WALKER_INTERVALS__.add(intervalId);
    }
    console.log(`[DEBUG] start() interval set with pace=${cfg.pace}ms`);
    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      // Remove from global tracking
      if (window.__DRUNK_WALKER_INTERVALS__) {
        window.__DRUNK_WALKER_INTERVALS__.delete(intervalId);
      }
      intervalId = null;
    }
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }
    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = null;
    status = 'IDLE';
    wheel.reset();
    previousLocation = null;
    previousYaw = null;
  };

  return {
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,
    getVisitedUrls: () => visitedUrls,
    getCurrentYaw,
    resetCurrentYaw,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    restoreVisitedFromPath,
    setUserMouseDown,
    setIsDrawing,
    setActionHandlers,
    start,
    stop,
    reset,
    tick,
    getConfig: () => ({ ...cfg }),
    getNavigation: () => null,
    getNavigationState: () => ({}),
    setAlgorithm: (newAlgorithm) => { algorithm = newAlgorithm; }
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */
const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};
/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}
/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };
  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 0,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };
  const targetEl = target || findStreetViewTarget();
  // Full key event sequence
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}
/**
 * Simulate long-press keyboard event (repeated keydown/keypress)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };
  const baseOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 0,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };
  const targetEl = target || findStreetViewTarget();
  const startTime = Date.now();
  // Initial Key Down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', { ...baseOptions, repeat: false }));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', { ...baseOptions, repeat: false }));
  // Repeat loop
  const intervalId = setInterval(() => {
    if (Date.now() - startTime >= duration) {
      clearInterval(intervalId);
      targetEl.dispatchEvent(new KeyboardEvent('keyup', { ...baseOptions, repeat: false }));
      if (callback) callback();
    } else {
      // Repeat events
      targetEl.dispatchEvent(new KeyboardEvent('keydown', { ...baseOptions, repeat: true }));
      targetEl.dispatchEvent(new KeyboardEvent('keypress', { ...baseOptions, repeat: true }));
    }
  }, 50); // Repeat every 50ms (typical browser repeat rate)
}
/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };
  const target = document.elementFromPoint(x, y) || document.body;
  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));
  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}
/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;
  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };
  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };
  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);
  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}

  // === EXPLORATION MAP ===
  /**
 * Exploration Map Component
 * Renders a mini-map showing explored territory from walker's perspective
 * v6.0.0-CYBERPUNK
 */

function createExplorationMap() {
  let canvas = null;
  let ctx = null;
  let container = null;
  let isVisible = false;
  let isExpanded = false;

  // Map state
  let centerLat = 0;
  let centerLng = 0;
  let zoom = 1;
  const baseZoom = 0.0001; // meters per pixel

  // Styles
  const CSS = {
    container: `
      position: fixed;
      bottom: 20px;
      left: 50%;
      transform: translateX(-50%);
      background: rgba(18, 18, 20, 0.85);
      backdrop-filter: blur(20px) saturate(180%);
      -webkit-backdrop-filter: blur(20px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.08);
      border-radius: 12px;
      padding: 12px;
      z-index: 999998;
      display: none;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, monospace;
      font-size: 11px;
      color: #fff;
      box-shadow: 0 20px 40px -10px rgba(0, 0, 0, 0.6), 0 0 0 1px rgba(0, 0, 0, 0.3);
      min-width: 320px;
      transition: all 0.3s cubic-bezier(0.2, 0.8, 0.2, 1);
    `,
    header: `
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 10px;
      padding: 0 4px;
    `,
    title: `
      font-weight: 700;
      color: #fff;
      letter-spacing: -0.3px;
      display: flex;
      align-items: center;
      gap: 6px;
    `,
    controls: `
      display: flex; 
      gap: 6px;
    `,
    btn: `
      background: rgba(255, 255, 255, 0.05);
      border: 1px solid rgba(255, 255, 255, 0.1);
      color: rgba(255, 255, 255, 0.7);
      width: 24px;
      height: 24px;
      cursor: pointer;
      border-radius: 6px;
      font-size: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
      transition: all 0.2s;
    `,
    statsBar: `
      display: flex;
      gap: 16px;
      padding: 8px 12px;
      background: rgba(0, 0, 0, 0.3);
      border-radius: 8px;
      margin-bottom: 10px;
      font-size: 10px;
      border: 1px solid rgba(255, 255, 255, 0.05);
    `,
    statItem: `
      display: flex;
      align-items: center;
      gap: 6px;
      font-weight: 500;
      color: rgba(255, 255, 255, 0.6);
    `,
    canvasContainer: `
      position: relative;
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 8px;
      overflow: hidden;
      background: #000;
    `
  };

  function init() {
    container = document.createElement('div');
    container.id = 'dw-map-container';
    container.style.cssText = CSS.container;

    // Header
    const header = document.createElement('div');
    header.style.cssText = CSS.header;

    const title = document.createElement('span');
    title.innerHTML = '<span>🗺️</span> EXPLORATION MAP';
    title.style.cssText = CSS.title;

    const controls = document.createElement('div');
    controls.style.cssText = CSS.controls;

    const expandBtn = document.createElement('button');
    expandBtn.innerHTML = '⛶';
    expandBtn.title = 'Expand/Collapse';
    expandBtn.style.cssText = CSS.btn;
    expandBtn.onmouseover = () => { expandBtn.style.background = 'rgba(255,255,255,0.1)'; expandBtn.style.color = '#fff'; };
    expandBtn.onmouseout = () => { expandBtn.style.background = 'rgba(255,255,255,0.05)'; expandBtn.style.color = 'rgba(255,255,255,0.7)'; };
    expandBtn.onclick = () => toggleExpand();

    const closeBtn = document.createElement('button');
    closeBtn.innerHTML = '✕';
    closeBtn.title = 'Close (M)';
    closeBtn.style.cssText = CSS.btn;
    closeBtn.onmouseover = () => { closeBtn.style.background = 'rgba(255, 50, 50, 0.2)'; closeBtn.style.color = '#ff4d4d'; closeBtn.style.borderColor = 'rgba(255, 50, 50, 0.3)'; };
    closeBtn.onmouseout = () => { closeBtn.style.background = 'rgba(255,255,255,0.05)'; closeBtn.style.color = 'rgba(255,255,255,0.7)'; closeBtn.style.borderColor = 'rgba(255,255,255,0.1)'; };
    closeBtn.onclick = () => hide();

    controls.appendChild(expandBtn);
    controls.appendChild(closeBtn);
    header.appendChild(title);
    header.appendChild(controls);

    // Stats bar
    const statsBar = document.createElement('div');
    statsBar.id = 'dw-map-stats';
    statsBar.style.cssText = CSS.statsBar;

    const stat = (color, label, id) => `
      <div style="${CSS.statItem}">
        <span style="width:6px;height:6px;border-radius:50%;background:${color};box-shadow:0 0 6px ${color};"></span>
        <span>${label}: <strong id="${id}" style="color:#fff;">0</strong></span>
      </div>
    `;

    statsBar.innerHTML = `
      ${stat('#00ff80', 'Visited', 'dw-stat-visited')}
      ${stat('#ffb74d', 'Crossroads', 'dw-stat-crossroads')}
      ${stat('#ff4d4d', 'Dead ends', 'dw-stat-deadends')}
    `;

    // Canvas container
    const canvasContainer = document.createElement('div');
    canvasContainer.style.cssText = CSS.canvasContainer;

    canvas = document.createElement('canvas');
    canvas.width = 300;
    canvas.height = 200;
    canvas.style.cssText = 'display: block; width: 100%; height: 100%;';

    canvasContainer.appendChild(canvas);
    ctx = canvas.getContext('2d');

    container.appendChild(header);
    container.appendChild(statsBar);
    container.appendChild(canvasContainer);

    document.body.appendChild(container);

    document.addEventListener('keydown', (e) => {
      if (e.key === 'm' || e.key === 'M') {
        e.preventDefault();
        toggle();
      }
    });
  }

  function toggle() {
    if (!container) init();
    isVisible = !isVisible;
    container.style.display = isVisible ? 'block' : 'none';
    if (isVisible) render();
  }

  function show() {
    if (!container) init();
    isVisible = true;
    container.style.display = 'block';
    render();
  }

  function hide() {
    isVisible = false;
    if (container) container.style.display = 'none';
  }

  function toggleExpand() {
    isExpanded = !isExpanded;
    if (isExpanded) {
      canvas.width = 600;
      canvas.height = 400;
      container.style.minWidth = '620px';
    } else {
      canvas.width = 300;
      canvas.height = 200;
      container.style.minWidth = '320px';
    }
    render();
  }

  function gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom) {
    const scale = zoom * 10000000;
    const x = width / 2 + (lng - centerLng) * scale;
    const y = height / 2 - (lat - centerLat) * scale * 1.5;
    return { x, y };
  }

  function render(transitionGraph, currentLocation, visitedUrls) {
    if (!ctx || !canvas) return;

    const width = canvas.width;
    const height = canvas.height;

    // Clear canvas with deep space blue
    ctx.fillStyle = '#0a0a0c';
    ctx.fillRect(0, 0, width, height);

    // Grid background
    ctx.strokeStyle = '#1a1a1c';
    ctx.lineWidth = 1;
    ctx.beginPath();
    for(let x=0; x<width; x+=20) { ctx.moveTo(x,0); ctx.lineTo(x,height); }
    for(let y=0; y<height; y+=20) { ctx.moveTo(0,y); ctx.lineTo(width,y); }
    ctx.stroke();

    if (!transitionGraph) {
      ctx.fillStyle = '#444';
      ctx.font = '12px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('AWAITING TELEMETRY...', width / 2, height / 2);
      return;
    }

    const stats = transitionGraph.getStats();
    const locations = Array.from(transitionGraph.connections.keys());

    if (locations.length === 0) {
      ctx.fillStyle = '#444';
      ctx.font = '12px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('NO DATA COLLECTED', width / 2, height / 2);
      return;
    }

    let minLat = Infinity, maxLat = -Infinity;
    let minLng = Infinity, maxLng = -Infinity;

    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
      minLng = Math.min(minLng, lng);
      maxLng = Math.max(maxLng, lng);
    });

    centerLat = (minLat + maxLat) / 2;
    centerLng = (minLng + maxLng) / 2;

    const latRange = maxLat - minLat || 0.0001;
    const lngRange = maxLng - minLng || 0.0001;
    zoom = Math.min(width / lngRange / 100000, height / latRange / 100000) * 0.7;

    // Draw edges
    ctx.strokeStyle = 'rgba(255, 255, 255, 0.1)';
    ctx.lineWidth = 1;

    locations.forEach(loc => {
      const connections = transitionGraph.getConnections(loc);
      const [lat1, lng1] = loc.split(',').map(Number);
      const pos1 = gpsToScreen(lat1, lng1, centerLat, centerLng, width, height, zoom);

      connections.forEach(conn => {
        const [lat2, lng2] = conn.split(',').map(Number);
        const pos2 = gpsToScreen(lat2, lng2, centerLat, centerLng, width, height, zoom);

        ctx.beginPath();
        ctx.moveTo(pos1.x, pos1.y);
        ctx.lineTo(pos2.x, pos2.y);
        ctx.stroke();
      });
    });

    // Draw nodes
    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      const pos = gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom);

      const isCrossroad = transitionGraph.isCrossroad(loc);
      const isCurrent = loc === currentLocation;
      const isVisited = visitedUrls ? visitedUrls.has(loc) : false;

      if (isCurrent) {
        // Pulse effect
        const pulse = (Date.now() / 1000) % 1;
        ctx.fillStyle = `rgba(0, 255, 128, ${1-pulse})`;
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 12 * pulse + 4, 0, Math.PI * 2);
        ctx.fill();

        ctx.fillStyle = '#00ff80';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 4, 0, Math.PI * 2);
        ctx.fill();

        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 6, 0, Math.PI * 2);
        ctx.stroke();
      } else if (isCrossroad) {
        ctx.fillStyle = '#ffb74d';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 3, 0, Math.PI * 2);
        ctx.fill();
      } else if (isVisited) {
        ctx.fillStyle = '#00ff80';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 2, 0, Math.PI * 2);
        ctx.fill();
      } else {
        ctx.fillStyle = '#ff4d4d';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 1.5, 0, Math.PI * 2);
        ctx.fill();
      }
    });

    const deadEnds = locations.filter(loc => {
      const conns = transitionGraph.getConnections(loc);
      return conns.size === 1;
    }).length;

    document.getElementById('dw-stat-visited').textContent = locations.length;
    document.getElementById('dw-stat-crossroads').textContent = stats.crossroads || 0;
    document.getElementById('dw-stat-deadends').textContent = deadEnds;
  }

  return {
    init, toggle, show, hide, toggleExpand, render, isVisible: () => isVisible
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Compact Draggable Panel
 * v6.6.0-LOGS-FIX
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '6.6.0',
    autoStart = true,
    onPathCollectionToggle = null
  } = options;

  let container = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let startStopBtn = null;

  // Session logs storage - collect from console
  const sessionLogs = [];
  const originalConsoleLog = console.log;
  const originalConsoleWarn = console.warn;
  const originalConsoleError = console.error;

  // Hook console to capture logs
  const hookConsole = () => {
    console.log = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleLog.apply(console, args);
    };
    console.warn = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ⚠️ ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleWarn.apply(console, args);
    };
    console.error = function(...args) {
      const msg = `[${new Date().toISOString().substr(11, 8)}] ❌ ${args.join(' ')}`;
      sessionLogs.push(msg);
      if (sessionLogs.length > 5000) sessionLogs.shift();
      originalConsoleError.apply(console, args);
    };
  };

  // Hook console immediately
  hookConsole();

  const makeDraggable = (element) => {
    let isDragging = false;
    let startX, startY, initialLeft, initialTop;

    element.addEventListener('mousedown', (e) => {
      if (e.target.tagName === 'BUTTON' || e.target.tagName === 'INPUT' || e.target.closest('button') || e.target.closest('input')) {
        return;
      }
      isDragging = true;
      startX = e.clientX;
      startY = e.clientY;
      const rect = element.getBoundingClientRect();
      initialLeft = rect.left;
      initialTop = rect.top;
      element.style.cursor = 'grabbing';
      element.style.transition = 'none';
      element.style.userSelect = 'none';
    });

    document.addEventListener('mousemove', (e) => {
      if (!isDragging) return;
      e.preventDefault();
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      element.style.left = `${initialLeft + dx}px`;
      element.style.top = `${initialTop + dy}px`;
      element.style.bottom = 'auto';
      element.style.right = 'auto';
    });

    document.addEventListener('mouseup', () => {
      if (isDragging) {
        isDragging = false;
        element.style.cursor = 'grab';
        element.style.transition = '';
        element.style.userSelect = '';
      }
    });
  };

  const createUI = () => {
    document.querySelectorAll('.dw-float-ui').forEach(el => el.remove());

    container = document.createElement('div');
    container.className = 'dw-float-ui';
    container.style.cssText = `
      position: fixed;
      bottom: 20px;
      left: 20px;
      width: 130px;
      padding: 12px;
      background: rgba(18, 18, 20, 0.95);
      backdrop-filter: blur(20px) saturate(180%);
      -webkit-backdrop-filter: blur(20px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.15);
      border-radius: 12px;
      box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
      z-index: 1000000;
      display: flex;
      flex-direction: column;
      gap: 8px;
      cursor: grab;
      user-select: none;
      -webkit-user-select: none;
    `;

    // Stats row
    const statRow = document.createElement('div');
    statRow.style.cssText = `display: flex; gap: 6px;`;
    statRow.innerHTML = `
      <div style="display:flex;flex-direction:column;align-items:center;padding:6px 8px;background:rgba(255,255,255,0.06);border-radius:8px;flex:1;">
        <span style="font-size:7px;color:rgba(255,255,255,0.45);text-transform:uppercase;letter-spacing:0.5px;">Steps</span>
        <span id="dw-steps" style="font-size:14px;font-weight:700;color:#fff;margin-top:2px;">0</span>
      </div>
      <div style="display:flex;flex-direction:column;align-items:center;padding:6px 8px;background:rgba(255,255,255,0.06);border-radius:8px;flex:1;">
        <span style="font-size:7px;color:rgba(255,255,255,0.45);text-transform:uppercase;letter-spacing:0.5px;">Visited</span>
        <span id="dw-visited" style="font-size:14px;font-weight:700;color:#fff;margin-top:2px;">0</span>
      </div>
    `;
    container.appendChild(statRow);
    stepsEl = statRow.querySelector('#dw-steps');
    visitedEl = statRow.querySelector('#dw-visited');

    // START/STOP button
    startStopBtn = document.createElement('button');
    startStopBtn.style.cssText = `
      width:100%;display:flex;align-items:center;justify-content:center;gap:6px;padding:8px 12px;
      background:rgba(255,255,255,0.08);border:1px solid rgba(255,255,255,0.12);border-radius:8px;
      color:#f0f0f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
      font-size:11px;font-weight:600;cursor:pointer;transition:all 0.2s;text-transform:uppercase;letter-spacing:0.5px;
    `;
    startStopBtn.innerHTML = '<span>▶</span> START';
    startStopBtn.onmouseover = () => { if (!engine.isNavigating()) startStopBtn.style.background = 'rgba(255,255,255,0.12)'; };
    startStopBtn.onmouseout = () => { if (!engine.isNavigating()) startStopBtn.style.background = 'rgba(255,255,255,0.08)'; };
    startStopBtn.onclick = (e) => {
      e.stopPropagation();
      if (engine.isNavigating()) engine.stop();
      else engine.start();
      updateStartStopBtn();
    };
    container.appendChild(startStopBtn);

    // Save Path / Save Logs row
    const saveRow = document.createElement('div');
    saveRow.style.cssText = `display: flex; gap: 6px;`;
    saveRow.innerHTML = `
      <button id="dw-save-path" style="flex:1;padding:6px 10px;font-size:12px;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.1);border-radius:7px;color:#f0f0f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-weight:500;cursor:pointer;transition:all 0.2s;">💾 Path</button>
      <button id="dw-save-logs" style="flex:1;padding:6px 10px;font-size:12px;background:rgba(255,255,255,0.06);border:1px solid rgba(255,255,255,0.1);border-radius:7px;color:#f0f0f0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-weight:500;cursor:pointer;transition:all 0.2s;">📄 Logs</button>
    `;
    container.appendChild(saveRow);
    saveRow.querySelector('#dw-save-path').onclick = (e) => { e.stopPropagation(); exportPath(); };
    saveRow.querySelector('#dw-save-logs').onclick = (e) => { e.stopPropagation(); exportLogs(); };

    // Pace control
    const paceRow = document.createElement('div');
    paceRow.style.cssText = `display:flex;flex-direction:column;gap:4px;padding-top:4px;border-top:1px solid rgba(255,255,255,0.08);`;
    paceRow.innerHTML = `
      <span style="font-size:8px;color:rgba(255,255,255,0.5);text-align:center;">Pace: <span id="dw-pace-val">${(engine.getConfig().pace / 1000).toFixed(1)}s</span></span>
      <input type="range" min="500" max="5000" step="100" value="${engine.getConfig().pace}" style="width:100%;-webkit-appearance:none;height:4px;background:rgba(255,255,255,0.15);border-radius:2px;outline:none;cursor:pointer;" />
    `;
    const sliderStyle = document.createElement('style');
    sliderStyle.textContent = `
      .dw-float-ui input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:14px;height:14px;background:rgba(255,255,255,0.8);border-radius:50%;cursor:pointer;}
      .dw-float-ui input[type=range]::-moz-range-thumb{width:14px;height:14px;background:rgba(255,255,255,0.8);border:none;border-radius:50%;cursor:pointer;}
    `;
    container.appendChild(sliderStyle);
    container.appendChild(paceRow);
    const paceSlider = paceRow.querySelector('input');
    paceValEl = paceRow.querySelector('#dw-pace-val');
    paceSlider.oninput = (e) => {
      e.stopPropagation();
      paceValEl.innerText = (paceSlider.value / 1000).toFixed(1) + 's';
      engine.setPace(parseInt(paceSlider.value));
    };

    document.body.appendChild(container);
    makeDraggable(container);

    if (onPathCollectionToggle) onPathCollectionToggle(true);
    engine.setSelfAvoiding(true);
  };

  const updateStartStopBtn = () => {
    if (!startStopBtn) return;
    if (engine.isNavigating()) {
      startStopBtn.innerHTML = '<span>⏹</span> STOP';
      startStopBtn.style.background = 'rgba(255, 80, 80, 0.25)';
      startStopBtn.style.color = '#ff6b6b';
      startStopBtn.style.borderColor = 'rgba(255, 80, 80, 0.4)';
    } else {
      startStopBtn.innerHTML = '<span>▶</span> START';
      startStopBtn.style.background = 'rgba(255,255,255,0.08)';
      startStopBtn.style.color = '#f0f0f0';
      startStopBtn.style.borderColor = 'rgba(255,255,255,0.12)';
    }
  };

  const exportPath = () => {
    const walkPath = engine.getWalkPath();
    if (walkPath.length === 0) { alert('No path recorded yet.'); return; }
    const blob = new Blob([JSON.stringify(walkPath, null, 2)], { type: 'application/json' });
    downloadFile(blob, `dw-path-${Date.now()}.json`);
  };

  const exportLogs = () => {
    if (sessionLogs.length === 0) { alert('No logs captured yet.'); return; }
    const blob = new Blob([sessionLogs.join('\n')], { type: 'text/plain' });
    downloadFile(blob, `dw-logs-${Date.now()}.txt`);
  };

  const downloadFile = (blob, filename) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateStartStopBtn();
  };

  const init = () => {
    if (!document.body) return { destroy: () => {} };
    try {
      createUI();
      updateStartStopBtn();
      if (autoStart) engine.start();
      console.log('🟣 UI Initialized (Draggable Panel)');
      return { destroy };
    } catch (e) {
      console.error('UI Init Failed:', e);
      return { destroy: () => {} };
    }
  };

  const destroy = () => {
    engine.stop();
    document.querySelectorAll('.dw-float-ui').forEach(el => el.remove());
  };

  return { init, destroy, onStatusUpdate };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */

// Global initialization lock
let __INITIALIZING__ = false;

// Global interval tracking for cleanup
window.__DRUNK_WALKER_INTERVALS__ = window.__DRUNK_WALKER_INTERVALS__ || new Set();

// Cleanup function for ALL intervals
const cleanupAllIntervals = () => {
  if (window.__DRUNK_WALKER_INTERVALS__) {
    console.log(`🤪 Cleaning up ${window.__DRUNK_WALKER_INTERVALS__.size} existing interval(s)...`);
    window.__DRUNK_WALKER_INTERVALS__.forEach(id => clearInterval(id));
    window.__DRUNK_WALKER_INTERVALS__.clear();
  }
};

// Allow restart by clearing previous instance
if (window.DRUNK_WALKER) {
  console.log('🤪 Drunk Walker: Stopping previous instance...');
  try {
    window.DRUNK_WALKER.stop();
  } catch(e) {
    console.warn('Error stopping previous instance:', e);
  }
  // Remove the global immediately to prevent race conditions
  delete window.DRUNK_WALKER;
  window.DRUNK_WALKER_ACTIVE = false;
}

// Aggressive cleanup before new instance
cleanupAllIntervals();

// Remove any existing UI panel from previous runs
const existingPanel = document.getElementById('dw-modern-panel');
if (existingPanel) {
  console.log('🤪 Removing existing UI panel...');
  existingPanel.remove();
}

// Small delay to ensure cleanup is processed by browser
setTimeout(() => {
  window.DRUNK_WALKER_ACTIVE = true;
  console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

  // Initialize when DOM is ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initialize);
  } else {
    initialize();
  }
}, 100);

// Wait for DOM to be ready before initializing
const initialize = () => {
  // Prevent double initialization
  if (__INITIALIZING__) {
    console.log('🤪 [initialize] Already initializing, skipping...');
    return;
  }
  __INITIALIZING__ = true;

  // Double-check and remove any panel that might have appeared
  const existingPanel = document.getElementById('dw-modern-panel');
  if (existingPanel) {
    console.log('🤪 [initialize] Removing panel that appeared during init...');
    existingPanel.remove();
  }

  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create exploration map
    const map = createExplorationMap();
    map.init();

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: (status, steps, stuckCount) => {
        ui.onStatusUpdate(status, steps, stuckCount);
        // Update map periodically (every 10 ticks)
        if (steps % 10 === 0 && map.isVisible()) {
          const transitionGraph = engine.getTransitionGraph();
          const currentLocation = engine.getWalkPath().length > 0 
            ? engine.getWalkPath()[engine.getWalkPath().length - 1].location 
            : null;
          map.render(transitionGraph, currentLocation, engine.getVisitedUrls());
        }
      },
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      map,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
    __INITIALIZING__ = false;  // Reset lock on error
  }
};

// NOTE: Initialization is handled by the setTimeout above to ensure
// proper cleanup of any previous instance. The setTimeout gives the
// browser time to process the cleanup before creating a new instance.

}();