// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v3.70.0-EXP - CONSOLE VERSION
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// Any changes made here will be LOST on next build.
//
// TO MAKE CHANGES:
//   Edit files in src/ directory, then run: node build.js
//   - src/core/navigation.js  - Navigation strategies (self-avoiding, unstuck)
//   - src/core/engine.js      - Core engine (state, timing, path recording)
//   - src/input/handlers.js   - Keyboard/mouse events
//   - src/ui/controller.js    - Control panel UI
//   - src/main.js             - Entry point
// ═══════════════════════════════════════════════════════════════════════════════
// This version is optimized for pasting into browser console
// 1. Type: allow pasting
// 2. Paste this code
// 3. Press Enter

void function initDrunkWalker(){
  if (window.DRUNK_WALKER_ACTIVE) {
    console.log('🤪 Drunk Walker already running. Refresh page to restart.');
    return;
  }
  window.DRUNK_WALKER_ACTIVE = true;

  // === NAVIGATION STRATEGIES ===
  // Pluggable movement algorithms (self-avoiding, unstuck, etc.)
  // TO CHANGE NAVIGATION: Edit src/core/navigation.js
  /**
 * Navigation Strategies - Pluggable Movement Algorithms
 */

// ═══════════════════════════════════════════════════════════════════════════════
// PROACTIVE SELF-AVOIDING STRATEGY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Proactive Self-Avoiding Algorithm - Prevent entering visited areas
 *
 * Behavior:
 * - Before moving forward, check if the next location is already visited
 * - If visited, proactively turn toward unvisited direction BEFORE getting stuck
 * - Uses lookahead to predict next position based on current heading
 * - Prefers right turns first (less common, more exploration), then left
 *
 * Key invariants:
 * - Only triggers when NOT stuck (proactive, not reactive)
 * - Scans multiple angles to find unvisited direction
 * - Falls back to unstuck algorithm if all directions are visited
 */
function createProactiveAvoidance(cfg, callbacks) {
  const { onKeyPress, onLongKeyPress, onStatusUpdate, extractLocation } = callbacks;

  let state = 'IDLE';
  let urlBeforeTurn = '';

  // Track which directions we've tried at each location
  const locationAttempts = new Map();

  /**
   * Predict next location given current location, yaw, and step distance
   */
  const predictNextLocation = (currentLocation, yaw, stepDistance = 0.0005) => {
    const [lat, lng] = currentLocation.split(',').map(Number);
    const yawRad = yaw * Math.PI / 180;
    
    // Approximate lat/lng offset based on yaw (simplified projection)
    const dLat = Math.cos(yawRad) * stepDistance;
    const dLng = Math.sin(yawRad) * stepDistance / Math.cos(lat * Math.PI / 180);
    
    const nextLat = (lat + dLat).toFixed(6);
    const nextLng = (lng + dLng).toFixed(6);
    
    return `${nextLat},${nextLng}`;
  };

  /**
   * Check if a direction leads to visited location
   */
  const isDirectionVisited = (currentLocation, yaw, visitedUrls) => {
    const predicted = predictNextLocation(currentLocation, yaw);
    return visitedUrls.has(predicted);
  };

  /**
   * Find best unvisited direction by scanning angles
   * Returns { yaw, angle } or null if all directions visited
   */
  const findUnvisitedDirection = (currentLocation, currentYaw, visitedUrls) => {
    // Scan angles relative to current yaw: prefer perpendicular directions first
    const scanAngles = [90, -90, 45, -45, 135, -135, 180, 0];
    
    for (const angle of scanAngles) {
      const testYaw = normalizeAngle(currentYaw + angle);
      if (!isDirectionVisited(currentLocation, testYaw, visitedUrls)) {
        return { yaw: testYaw, angle };
      }
    }
    
    return null; // All directions visited
  };

  const executeProactiveAvoidance = (currentYaw, currentLocation, visitedUrls) => {
    if (state !== 'IDLE') return { action: 'none' };
    if (!cfg.expOn || !cfg.selfAvoiding) return { action: 'none' };
    if (!currentLocation) return { action: 'none' };

    // Check if forward direction leads to visited location
    const forwardVisited = isDirectionVisited(currentLocation, currentYaw, visitedUrls);
    
    if (!forwardVisited) {
      // Forward is clear, no avoidance needed
      return { action: 'none' };
    }

    // Forward leads to visited area, find alternative
    const bestDirection = findUnvisitedDirection(currentLocation, currentYaw, visitedUrls);
    
    if (!bestDirection) {
      // All directions visited, fall back to unstuck
      return { action: 'none', fallback: true };
    }

    urlBeforeTurn = window.location.href;
    state = 'TURNING';

    // Track this attempt
    const attemptsKey = currentLocation;
    const prevAttempts = locationAttempts.get(attemptsKey) || [];
    locationAttempts.set(attemptsKey, [...prevAttempts, bestDirection.angle]);

    const turnAngle = bestDirection.angle;
    const turnDuration = Math.round(Math.abs(turnAngle) * 10);
    const clampedDuration = Math.max(300, Math.min(900, turnDuration));

    if (onLongKeyPress) {
      const turnKey = turnAngle > 0 ? 'ArrowRight' : 'ArrowLeft';
      onLongKeyPress(turnKey, clampedDuration, () => {
        console.log(`proactive: url=${urlBeforeTurn}, currentYaw=${Math.round(bestDirection.yaw)}`);
        state = 'MOVING';
        if (onKeyPress) onKeyPress('ArrowUp');

        setTimeout(() => {
          state = 'IDLE';
          if (onStatusUpdate) {
            onStatusUpdate('WALKING', 0, 0);
          }
        }, cfg.pace);
      });
    }

    return {
      action: 'turn',
      turnAngle,
      newYaw: bestDirection.yaw,
      isProactive: true
    };
  };

  return {
    executeProactiveAvoidance,
    isBusy: () => state !== 'IDLE',
    reset: () => {
      state = 'IDLE';
      urlBeforeTurn = '';
      locationAttempts.clear();
    },
    getState: () => ({ state, locationAttemptsCount: locationAttempts.size })
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// UNSTUCK NAVIGATION STRATEGY
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Unstuck Algorithm - Recovery from being stuck
 *
 * Behavior:
 * - Detects when stuck (URL unchanged for N ticks)
 * - Stores relative turn deltas (always negative/left) per location
 * - Applies progressively sharper left turns from current arrival facing
 * - Immediately steps forward after turn
 * - Verifies URL changed, increments stuck counter if still stuck
 *
 * Key invariants:
 * - lastTurnDelta is always negative (left turn magnitude)
 * - Same location revisited gets escalating left turn (more negative each time)
 * - Turn is always relative to how we arrived (physically coherent)
 */
function createUnstuckNavigation(cfg, callbacks) {
  const { onKeyPress, onLongKeyPress, onStatusUpdate, extractLocation } = callbacks;

  let state = 'IDLE';
  let urlBeforeUnstuck = '';

  // Memory of relative turn deltas per location (always negative, 0 to -90 degrees)
  const locationTurnDeltas = new Map();

  const executeUnstuck = (stuckCount, panicThreshold, currentYaw) => {
    if (state !== 'IDLE') return { action: 'none' };
    if (!cfg.expOn || stuckCount < panicThreshold) return { action: 'none' };

    const currentUrl = window.location.href;
    const currentLocation = extractLocation(currentUrl);

    urlBeforeUnstuck = currentUrl;
    state = 'TURNING';

    // Get previous delta for this location (always negative or 0)
    const prevTurnDelta = locationTurnDeltas.get(currentLocation) || 0;

    // Compute baseDelta: prevDelta + random left increment (-15 to -45 degrees)
    // If first visit (prevDelta = 0), this gives fresh left turn of -15 to -45
    // If revisited, this makes turn more leftward than last time
    const randomLeftIncrement = -15 - Math.random() * 30;  // -15 to -45
    let baseDelta = prevTurnDelta + randomLeftIncrement;

    // Clamp to -90 degrees maximum (ensure we don't turn more than 90° left)
    baseDelta = Math.max(-90, baseDelta);

    // Store the delta we're using (always negative)
    locationTurnDeltas.set(currentLocation, baseDelta);

    // Apply to current arrival facing: newYaw = normalize(currentYaw + baseDelta)
    const newYaw = normalizeAngle(currentYaw + baseDelta);
    const turnAngle = Math.abs(baseDelta);  // Duration based on magnitude

    // Convert angle to duration (10ms per degree)
    const turnDuration = Math.round(turnAngle * 10);
    const clampedDuration = Math.max(300, Math.min(900, turnDuration));

    if (onLongKeyPress) {
      onLongKeyPress('ArrowLeft', clampedDuration, () => {
        console.log(`url=${currentUrl}, currentYaw=${Math.round(newYaw)}`);
        state = 'MOVING';
        if (onKeyPress) onKeyPress('ArrowUp');

        setTimeout(() => {
          state = 'VERIFYING';
          const newUrl = typeof window !== 'undefined' ? window.location.href : urlBeforeUnstuck;

          let newStuckCount = 0;
          if (newUrl !== urlBeforeUnstuck) {
            newStuckCount = 0;
          } else {
            newStuckCount = stuckCount + 1;
          }

          state = 'IDLE';
          if (onStatusUpdate) {
            onStatusUpdate('WALKING', 0, newStuckCount);
          }
        }, cfg.pace);
      });
    }

    return {
      action: 'turn',
      turnAngle: baseDelta,  // Return signed delta (negative for left)
      newYaw
    };
  };

  return {
    executeUnstuck,
    isBusy: () => state !== 'IDLE',
    reset: () => {
      state = 'IDLE';
      urlBeforeUnstuck = '';
      locationTurnDeltas.clear();
    },
    getState: () => ({ state, locationTurnDeltasCount: locationTurnDeltas.size }),
    getDeltaForLocation: (loc) => locationTurnDeltas.get(loc) || 0
  };
}

/**
 * Normalize angle to 0-360 range
 */
function normalizeAngle(angle) {
  angle = angle % 360;
  if (angle < 0) angle += 360;
  return angle;
}

// ═══════════════════════════════════════════════════════════════════════════════
// COMBINED NAVIGATION CONTROLLER
// ═══════════════════════════════════════════════════════════════════════════════

function createNavigationController(cfg, callbacks) {
  const proactive = createProactiveAvoidance(cfg, callbacks);
  const unstuck = createUnstuckNavigation(cfg, callbacks);

  // Global orientation (start + all turns made)
  let globalOrientation = 0;

  const tick = (context) => {
    const { stuckCount, currentYaw, currentLocation, visitedUrls } = context || {};

    if (proactive.isBusy() || unstuck.isBusy()) {
      return { action: 'none', busy: true };
    }

    if (!context) return { action: 'none', busy: false };

    // PRIORITY 1: Proactive avoidance (when NOT stuck)
    // Check if we should avoid visited areas before moving
    if (cfg.expOn && cfg.selfAvoiding && stuckCount === 0) {
      const result = proactive.executeProactiveAvoidance(currentYaw, currentLocation, visitedUrls);
      if (result.action === 'turn') {
        // Update global orientation with signed delta
        globalOrientation += result.turnAngle;
        if (globalOrientation < 0) globalOrientation += 360;
        if (globalOrientation >= 360) globalOrientation -= 360;
        return { ...result, strategy: 'proactive', busy: true, cumulativeTurnAngle: globalOrientation };
      }
      // If fallback: true, all directions visited - let unstuck handle it
    }

    // PRIORITY 2: Unstuck (when stuck for N ticks)
    if (cfg.expOn && stuckCount >= cfg.panicThreshold) {
      const result = unstuck.executeUnstuck(stuckCount, cfg.panicThreshold, currentYaw);
      if (result.action !== 'none') {
        // Update global orientation with signed delta (negative for left turn)
        globalOrientation += result.turnAngle;
        if (globalOrientation < 0) globalOrientation += 360;
        if (globalOrientation >= 360) globalOrientation -= 360;
        return { ...result, strategy: 'unstuck', busy: true, cumulativeTurnAngle: globalOrientation };
      }
    }

    // Normal movement (no special navigation needed)
    return { action: 'move', strategy: 'normal', busy: false };
  };

  return {
    tick,
    getCumulativeTurnAngle: () => globalOrientation,
    resetCumulativeTurnAngle: () => { globalOrientation = 0; },
    reset: () => {
      proactive.reset();
      unstuck.reset();
      globalOrientation = 0;
    },
    getState: () => ({
      globalOrientation,
      proactive: proactive.getState(),
      unstuck: unstuck.getState()
    })
  };
}




  // === CORE ENGINE ===
  // State management, tick timing, path recording
  // TO CHANGE ENGINE: Edit src/core/engine.js
  /**
 * Drunk Walker Core Engine
 * Independent navigation logic - works without UI
 * 
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording (this file)
 * - Navigation: Movement algorithms in src/core/navigation.js (pluggable)
 * 
 * TO CHANGE NAVIGATION BEHAVIOR:
 * Edit src/core/navigation.js - NOT this file
 */



const VERSION = '3.70.0-EXP';

const defaultConfig = {
  pace: 2000,
  kbOn: true,      // Keyboard mode ON by default
  expOn: true,     // Experimental mode ON by default (enables unstuck algorithm)
  panicThreshold: 3,
  radius: 50,
  targetX: 0.5,    // 50% of screen width
  targetY: 0.7,    // 70% of screen height
  turnDuration: 600,  // ms to hold ArrowLeft for ~60° turn (fixed)
  collectPath: true,  // Path recording ENABLED by default
  selfAvoiding: true  // Self-avoiding walk ENABLED by default (opt-out)
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = typeof window !== 'undefined' ? window.location.href : '';
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;

  // Path collection (opt-in)
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;  // Initialize from config (default: true)

  // Visited nodes memory for self-avoiding walk
  let visitedUrls = new Set();

  // Current facing direction (yaw) - starts at 0° (north)
  let currentYaw = 0;

  // Navigation controller (pluggable movement algorithms)
  // Will be initialized after extractLocation is defined
  let navigation = null;

  // State getters
  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  // Configuration setters
  const setPace = (newPace) => {
    cfg.pace = newPace;
    // Update interval if running without resetting steps
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setExperimentalMode = (on) => { cfg.expOn = on; };
  const setPolygon = (points) => { poly = points; };
  const setPathCollection = (enabled) => {
    isPathCollectionEnabled = enabled;
    cfg.collectPath = enabled;
    if (!enabled) {
      walkPath = [];  // Clear path if disabled
    }
  };
  const setWalkPath = (path) => { walkPath = path ? [...path] : []; };
  const setSteps = (count) => { steps = count; };
  const getWalkPath = () => [...walkPath];  // Return copy
  const clearWalkPath = () => { walkPath = []; };

  // Extract location from Street View URL (ignores query params that change)
  // Format: https://www.google.com/maps/@lat,lng,zoom... or place_id format
  const extractLocation = (url) => {
    try {
      const urlObj = new URL(url);
      const hash = urlObj.hash || urlObj.pathname;
      // Extract @lat,lng pattern from URL hash or pathname
      const match = hash.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (match) {
        return `${match[1]},${match[2]}`;  // Return "lat,lng" as unique location
      }
      // Fallback: use place_id if available
      const placeMatch = urlObj.searchParams.get('place_id');
      if (placeMatch) {
        return `place:${placeMatch}`;
      }
      // Last resort: use full pathname
      return urlObj.pathname + urlObj.hash;
    } catch (e) {
      return url;  // Return original if parsing fails
    }
  };

  // Initialize navigation controller with stub callbacks
  // Will be updated with real callbacks when setActionHandlers is called
  navigation = createNavigationController(cfg, {
    onKeyPress: null,
    onMouseClick: null,
    onStatusUpdate: null,
    onLongKeyPress: null,
    extractLocation
  });

  const recordStep = () => {
    if (isPathCollectionEnabled) {
      const currentUrl = window.location.href;
      const location = extractLocation(currentUrl);
      walkPath.push({
        url: currentUrl,
        currentYaw: Math.round(currentYaw)
      });
      // Track visited locations for self-avoiding walk
      if (cfg.selfAvoiding) {
        visitedUrls.add(location);  // Use location, not full URL
      }
    }
  };
  const isUrlVisited = (location) => visitedUrls.has(location);
  const clearVisitedUrls = () => { visitedUrls.clear(); };
  const getVisitedCount = () => visitedUrls.size;
  const getCurrentYaw = () => currentYaw;
  const resetCurrentYaw = () => { currentYaw = 0; };
  // Alias for backward compatibility with tests
  const getCumulativeTurnAngle = getCurrentYaw;
  const resetCumulativeTurnAngle = resetCurrentYaw;

  // Restore visited URLs from a path array
  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    path.forEach(step => {
      if (step.location) {
        visitedUrls.add(step.location);
      } else if (step.url) {
        const loc = extractLocation(step.url);
        if (loc) visitedUrls.add(loc);
      }
    });
  };

  // User interaction handlers
  const setUserMouseDown = (down) => { isUserMouseDown = down; };
  const setIsDrawing = (drawing) => { isDrawing = drawing; };

  // Action callbacks (to be provided by caller)
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  const setActionHandlers = ({ keyPress, mouseClick, statusUpdate, longKeyPress, walkStop }) => {
    onKeyPress = keyPress;
    onMouseClick = mouseClick;
    onStatusUpdate = statusUpdate;
    onLongKeyPress = longKeyPress;
    onWalkStop = walkStop;

    // Reinitialize navigation controller with real callbacks
    // NOTE: Navigation logic is in src/core/navigation.js
    navigation = createNavigationController(cfg, {
      onKeyPress,
      onMouseClick,
      onStatusUpdate: (statusText, _, newStuckCount) => {
        // Update stuck count from navigation callback
        // Navigation returns new stuckCount after verification
        if (newStuckCount !== undefined) {
          stuckCount = newStuckCount;
        }
        if (onStatusUpdate) onStatusUpdate(statusText, steps, stuckCount);
      },
      onLongKeyPress,
      extractLocation
    });
  };

  // Stuck detection (simple URL comparison)
  const updateStuckDetection = () => {
    if (!cfg.expOn) {
      stuckCount = 0;
      return;
    }

    const currentUrl = window.location.href;
    if (currentUrl === lastUrl) {
      stuckCount++;
    } else {
      lastUrl = currentUrl;
      stuckCount = 0;
    }
  };

  const getStatusText = () => {
    if (!cfg.expOn || stuckCount === 0) return 'WALKING';
    if (stuckCount >= cfg.panicThreshold) return `PANIC! (STUCK ${stuckCount})`;
    return `STUCK (${stuckCount})`;
  };

  const calculateClickTarget = () => {
    const cw = window.innerWidth;
    const ch = window.innerHeight;

    // If polygon defined, pick random point inside
    if (poly.length > 2) {
      const minX = Math.min(...poly.map(p => p.x));
      const maxX = Math.max(...poly.map(p => p.x));
      const minY = Math.min(...poly.map(p => p.y));
      const maxY = Math.max(...poly.map(p => p.y));

      let tx, ty, attempts = 0;
      do {
        tx = minX + Math.random() * (maxX - minX);
        ty = minY + Math.random() * (maxY - minY);
        attempts++;
      } while (!inPoly({ x: tx, y: ty }, poly) && attempts < 100);

      return { x: tx, y: ty };
    }

    // Default target with wobble
    const radius = cfg.expOn && stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  // Polygon hit testing (kept for future use)
  const inPoly = (p, vs) => {
    let inside = false;
    for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
      const xi = vs[i].x, yi = vs[i].y;
      const xj = vs[j].x, yj = vs[j].y;
      const intersect = ((yi > p.y) !== (yj > p.y)) &&
        (p.x < (xj - xi) * (p.y - yi) / (yj - yi) + xi);
      if (intersect) inside = !inside;
    }
    return inside;
  };

  // Main navigation tick
  const tick = () => {
    // Skip if user is interacting
    if (isUserMouseDown || isDrawing) return;

    updateStuckDetection();

    if (onStatusUpdate) {
      onStatusUpdate(getStatusText(), steps, stuckCount);
    }

    // Get navigation decision (also checks if busy)
    const currentLocation = extractLocation(window.location.href);
    const navResult = navigation.tick({
      currentUrl: window.location.href,
      currentLocation,
      visitedUrls,
      stuckCount,
      isKeyboardMode: cfg.kbOn,
      currentYaw
    });

    // Handle navigation result
    if (navResult.busy) {
      // Navigation is handling the action (turning, moving, verifying)
      // Update currentYaw if turn was performed
      if (navResult.newYaw !== undefined) {
        currentYaw = navResult.newYaw;
      }
      // stuckCount will be reset by navigation callback after verification
      steps++;
      recordStep();
      return;
    }

    // Normal movement
    if (cfg.kbOn) {
      // Keyboard mode: press ArrowUp for forward movement
      console.log(`url=${window.location.href}, currentYaw=${Math.round(currentYaw)}`);
      if (onKeyPress) onKeyPress('ArrowUp');
    } else {
      // Click mode: calculate and click target
      const target = calculateClickTarget();
      console.log(`url=${window.location.href}, currentYaw=${Math.round(currentYaw)}`);
      if (onMouseClick) onMouseClick(target.x, target.y);
    }

    // Increment step counter - every tick = one step (time-based, not movement-based)
    steps++;

    // Record step for path collection (after movement)
    recordStep();
  };

  // Control functions
  const start = () => {
    if (status === 'WALKING') return;

    status = 'WALKING';
    // Only reset on first start, not on resume
    if (steps === 0) {
      stuckCount = 0;
      lastUrl = window.location.href;
    }

    if (intervalId) clearInterval(intervalId);
    intervalId = setInterval(tick, cfg.pace);

    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }

    // Submit walk path if collection enabled
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }

    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = '';
    status = 'IDLE';
    currentYaw = 0;  // Reset yaw on reset
    if (navigation) navigation.reset();  // Reset navigation state
  };

  return {
    // State
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,

    // Configuration
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setExperimentalMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },

    // Visited nodes
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,

    // Yaw tracking
    getCurrentYaw,
    resetCurrentYaw,
    getCumulativeTurnAngle,  // Alias for backward compatibility
    resetCumulativeTurnAngle,  // Alias for backward compatibility
    restoreVisitedFromPath,

    // Interaction
    setUserMouseDown,
    setIsDrawing,

    // Handlers
    setActionHandlers,

    // Control
    start,
    stop,
    reset,

    // Direct access for testing
    tick,
    getConfig: () => ({ ...cfg }),

    // Navigation access (for debugging/testing)
    getNavigation: () => navigation,
    getNavigationState: () => navigation ? navigation.getState() : null
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */

const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};

/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas[width][height]') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}

/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Full key event sequence for maximum compatibility
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}

/**
 * Simulate long-press keyboard event (keydown -> hold -> keyup)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };

  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };

  const targetEl = target || findStreetViewTarget();

  // Key down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  
  // Hold for duration, then release
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
    if (callback) callback();
  }, duration);
}

/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };

  const target = document.elementFromPoint(x, y) || document.body;

  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));

  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}

/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;

  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };

  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };

  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);

  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Control Panel Management
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '3.70.0-EXP',
    autoStart = true,
    onPathCollectionToggle = null  // Callback for path collection toggle
  } = options;

  let container = null;
  let btn = null;
  let statusEl = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let paceSlider = null;
  let downloadLogsBtn = null;
  let minimizeBtn = null;
  let mainContent = null;
  let isMinimized = false;
  
  // Session logs storage
  const sessionLogs = [];
  const originalConsoleLog = console.log;
  
  // Intercept console.log to capture logs
  console.log = function(...args) {
    const timestamp = new Date().toISOString();
    const message = args.map(arg => 
      typeof arg === 'object' ? JSON.stringify(arg) : String(arg)
    ).join(' ');
    sessionLogs.push(`[${timestamp}] ${message}`);
    originalConsoleLog.apply(console, args);
  };

  // Create UI elements
  const createUI = () => {
    container = document.createElement('div');
    container.id = 'dw-ctrl-panel';
    container.style.cssText = 'position:fixed;top:20px;right:20px;background:rgba(0,0,0,0.9);color:#0f0;padding:15px;font-family:monospace;z-index:999999;border:2px solid #0f0;border-radius:10px;box-shadow:0 0 15px #0f0;min-width:180px;user-select:none;';

    // Header with minimize button
    const header = document.createElement('div');
    header.style.cssText = 'display:flex;justify-content:space-between;align-items:center;margin-bottom:5px;';
    
    const title = document.createElement('div');
    title.innerText = `🤪 DRUNK WALKER v${version}`;
    title.style.fontSize = '12px';
    title.style.fontWeight = 'bold';
    
    minimizeBtn = document.createElement('button');
    minimizeBtn.innerText = '−';
    minimizeBtn.style.cssText = 'background:none;border:1px solid #0f0;color:#0f0;cursor:pointer;padding:0 5px;font-weight:bold;font-size:14px;';
    minimizeBtn.onclick = toggleMinimize;
    
    header.appendChild(title);
    header.appendChild(minimizeBtn);
    container.appendChild(header);

    const hr = document.createElement('hr');
    hr.id = 'dw-header-hr';
    hr.style.borderColor = '#0f0';
    container.appendChild(hr);

    // Visible Steps (Always visible or in steps section)
    const stepsLine = document.createElement('div');
    stepsLine.style.margin = '5px 0';
    stepsLine.innerHTML = 'STEPS: <span id="dw-steps">0</span>';
    container.appendChild(stepsLine);
    stepsEl = stepsLine.querySelector('#dw-steps');

    // Main Content wrapper (Toggleable)
    mainContent = document.createElement('div');
    mainContent.id = 'dw-main-content';
    
    // Remaining Stats
    const stats = document.createElement('div');
    stats.style.margin = '5px 0';
    stats.innerHTML = 'STATUS: <span id="dw-status">IDLE</span><br>VISITED: <span id="dw-visited">0</span>';
    mainContent.appendChild(stats);
    statusEl = stats.querySelector('#dw-status');
    visitedEl = stats.querySelector('#dw-visited');

    // Pace control
    const paceLabel = document.createElement('div');
    paceLabel.style.fontSize = '10px';
    paceLabel.style.marginTop = '10px';
    paceLabel.innerHTML = 'PACE: <span id="dw-pace-val">2.0</span>s';
    mainContent.appendChild(paceLabel);
    paceValEl = paceLabel.querySelector('#dw-pace-val');

    paceSlider = document.createElement('input');
    paceSlider.type = 'range';
    paceSlider.min = '500';
    paceSlider.max = '5000';
    paceSlider.step = '100';
    paceSlider.value = engine.getConfig().pace;
    paceSlider.style.width = '100%';
    paceSlider.oninput = () => {
      const newPace = parseInt(paceSlider.value);
      if (paceValEl) paceValEl.innerText = (newPace / 1000).toFixed(1);
      engine.setPace(newPace);
    };
    mainContent.appendChild(paceSlider);

    // Path export button (Download only)
    const exportDiv = document.createElement('div');
    exportDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    // Download path JSON button
    const downloadPathBtn = document.createElement('button');
    downloadPathBtn.innerText = '💾 Download Path';
    downloadPathBtn.style.cssText = 'flex:1;padding:6px;background:#28a745;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadPathBtn.onclick = () => {
      const walkPath = engine.getWalkPath();
      if (walkPath.length === 0) {
        alert('No path recorded. Start walking!');
        return;
      }
      const jsonStr = JSON.stringify(walkPath, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      downloadPathBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadPathBtn.innerText = '💾 Download Path';
      }, 2000);
    };
    
    exportDiv.appendChild(downloadPathBtn);
    mainContent.appendChild(exportDiv);

    // Download logs button
    const logsDiv = document.createElement('div');
    logsDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';
    
    downloadLogsBtn = document.createElement('button');
    downloadLogsBtn.innerText = '📄 Download Logs';
    downloadLogsBtn.style.cssText = 'width:100%;padding:6px;background:#ff6600;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadLogsBtn.onclick = () => {
      if (sessionLogs.length === 0) {
        alert('No logs recorded yet. Start walking to generate logs!');
        return;
      }
      
      const logContent = sessionLogs.join('\n');
      const blob = new Blob([logContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-logs-${new Date().toISOString().replace(/[:.]/g, '-')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      downloadLogsBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadLogsBtn.innerText = '📄 Download Logs';
      }, 2000);
    };
    
    logsDiv.appendChild(downloadLogsBtn);
    mainContent.appendChild(logsDiv);

    // Restore Walk from JSON button
    const restoreBtn = document.createElement('button');
    restoreBtn.innerText = '📂 Restore Walk';
    restoreBtn.style.cssText = 'width:100%;margin-top:8px;padding:6px;background:#663399;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    restoreBtn.onclick = () => {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json,application/json';
      input.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const walkPath = JSON.parse(event.target.result);
            if (!Array.isArray(walkPath) || walkPath.length === 0) {
              throw new Error('Invalid walk path format');
            }
            
            // Validate path structure
            const firstStep = walkPath[0];
            if (!firstStep.url && !firstStep.location) {
              throw new Error('Invalid path entries');
            }
            
            // Restore walk path
            engine.setWalkPath(walkPath);

            // Restore visited URLs from path
            engine.restoreVisitedFromPath(walkPath);

            // Navigate to last URL in path
            const lastStep = walkPath[walkPath.length - 1];
            if (lastStep.url) {
              window.location.href = lastStep.url;
            }
            
            console.log(`🤪 DRUNK WALKER: Restored walk with ${walkPath.length} steps`);
            alert(`✓ Walk restored!\n\n${walkPath.length} steps loaded\nNavigating to last position...`);
          } catch (err) {
            console.error('Failed to restore walk:', err);
            alert('❌ Failed to restore walk\n\n' + err.message + '\n\nPlease ensure the file is a valid walk JSON export.');
          }
        };
        reader.readAsText(file);
      };
      input.click();
    };
    mainContent.appendChild(restoreBtn);

    // Start/Stop button
    btn = document.createElement('button');
    btn.innerText = '▶ START';
    btn.style.cssText = 'width:100%;margin-top:10px;padding:8px;background:#0f0;color:#000;border:none;font-weight:bold;cursor:pointer;border-radius:5px;';
    btn.onclick = () => {
      if (engine.isNavigating()) {
        engine.stop();
      } else {
        engine.start();
      }
      updateButton();
    };
    mainContent.appendChild(btn);

    container.appendChild(mainContent);
    document.body.appendChild(container);
    
    // Ensure features are enabled by default as requested
    if (onPathCollectionToggle) onPathCollectionToggle(true);
    engine.setSelfAvoiding(true);
  };

  const toggleMinimize = () => {
    isMinimized = !isMinimized;
    if (isMinimized) {
      mainContent.style.display = 'none';
      minimizeBtn.innerText = '+';
      container.style.minWidth = '100px';
    } else {
      mainContent.style.display = 'block';
      minimizeBtn.innerText = '−';
      container.style.minWidth = '180px';
    }
  };

  // Update button appearance based on state
  const updateButton = () => {
    if (!btn) return;
    if (engine.isNavigating()) {
      btn.innerText = '🔴 STOP';
      btn.style.background = '#f00';
    } else {
      btn.innerText = '▶ START';
      btn.style.background = '#0f0';
    }
  };

  // Status update handler
  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (statusEl) statusEl.innerText = statusText;
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateButton();
  };

  // Initialize
  const init = () => {
    // Wait for DOM to be ready
    if (!document.body) {
      console.error('🤪 DRUNK WALKER: document.body not ready yet');
      return { destroy: () => {} };
    }

    try {
      createUI();
      updateButton();

      if (autoStart) {
        engine.start();
      }

      console.log('🤪 Control panel created successfully');
      return { destroy };
    } catch (error) {
      console.error('🤪 DRUNK WALKER: Failed to initialize UI:', error);
      return { destroy: () => {} };
    }
  };

  // Path collection state getter - always true now
  const getPathCollectionEnabled = () => true;

  // Cleanup
  const destroy = () => {
    engine.stop();
    if (container) {
      container.remove();
      container = null;
    }
  };

  return { init, destroy, onStatusUpdate, getPathCollectionEnabled };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */





// Allow restart by clearing previous instance
if (window.DRUNK_WALKER_ACTIVE) {
  console.log('🤪 Drunk Walker: Restarting...');
  if (window.DRUNK_WALKER) {
    try { window.DRUNK_WALKER.stop(); } catch(e) {}
  }
}

window.DRUNK_WALKER_ACTIVE = true;

console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

// Wait for DOM to be ready before initializing
const initialize = () => {
  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: ui.onStatusUpdate,
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
  }
};

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initialize);
} else {
  initialize();
}

}();