// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v5.1.0-SMART-NODES - Bundled Build
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// Any changes made here will be LOST on next build.
//
// TO MAKE CHANGES:
//   Edit files in src/ directory, then run: node build.js
//   - src/core/wheel.js       - Wheel component
//   - src/core/traversal.js   - Traversal algorithms
//   - src/core/navigation.js  - Compatibility layer
//   - src/core/engine.js      - Core engine (state, timing, path recording)
//   - src/input/handlers.js   - Keyboard/mouse events
//   - src/ui/controller.js    - Control panel UI
//   - src/main.js             - Entry point
// ═══════════════════════════════════════════════════════════════════════════════
// Generated automatically by build.js
// Paste this entire code into browser console on Google Street View
// NOTE: If you see "Allow pasting?" warning, type: allow pasting

(function(){
  if (window.DRUNK_WALKER_ACTIVE) return;
  window.DRUNK_WALKER_ACTIVE = true;

  // === WHEEL ===
  /**
 * Wheel component for Drunk Walker
 * Manages orientation and turning (only left)
 */
function createWheel(callbacks) {
  const { onLongKeyPress } = callbacks;
  let orientation = 0; // 0-359
  const getOrientation = () => orientation;
  const setOrientation = (newOrientation) => {
    orientation = normalizeAngle(newOrientation);
  };
  const turnLeft = (angle, callback) => {
    // Convert angle to duration (10ms per degree as per existing code)
    const duration = Math.round(angle * 10);
    const clampedDuration = Math.max(300, Math.min(900, duration));
    if (onLongKeyPress) {
      onLongKeyPress('ArrowLeft', clampedDuration, () => {
        orientation = normalizeAngle(orientation - angle);
        if (callback) callback();
      });
    } else {
      orientation = normalizeAngle(orientation - angle);
      if (callback) callback();
    }
  };
  const normalizeAngle = (angle) => {
    angle = angle % 360;
    if (angle < 0) angle += 360;
    return angle;
  };
  return {
    getOrientation,
    setOrientation,
    turnLeft,
    reset: () => { orientation = 0; }
  };
}

  // === TRANSITION GRAPH ===
  /**
 * Transition Graph for Drunk Walker
 * 
 * Learns actual Street View connectivity from observed transitions
 * instead of relying on mathematical prediction
 * 
 * Key Insight: Google Street View yaw drifts along paths
 * - Average yaw delta (A→B vs B→A): 125.8° (not 180°!)
 * - Only 7% of bidirectional pairs have expected 180° delta
 * - Mathematical prediction fails for ~60% of nodes
 * 
 * Solution: Learn from actual transitions (100% accurate for learned nodes)
 */

class TransitionGraph {
  constructor() {
    // location -> Set<connectedLocations>
    this.connections = new Map();

    // "loc1->loc2" -> Array<{fromYaw, toYaw, timestamp}>
    this.transitions = new Map();

    // Statistics
    this.stats = {
      totalTransitions: 0,
      uniqueConnections: 0
    };
  }

  /**
   * Record a transition from one location to another
   * @param {string} fromLoc - Starting location "lat,lng"
   * @param {string} toLoc - Destination location "lat,lng"
   * @param {number} fromYaw - Yaw at starting location
   * @param {number} toYaw - Yaw at destination location
   */
  record(fromLoc, toLoc, fromYaw, toYaw) {
    if (!fromLoc || !toLoc || fromLoc === toLoc) return;

    // Record connection
    if (!this.connections.has(fromLoc)) {
      this.connections.set(fromLoc, new Set());
    }
    const wasNew = !this.connections.get(fromLoc).has(toLoc);
    this.connections.get(fromLoc).add(toLoc);

    if (wasNew) {
      this.stats.uniqueConnections++;
    }

    // Record transition details
    const key = `${fromLoc}->${toLoc}`;
    if (!this.transitions.has(key)) {
      this.transitions.set(key, []);
    }
    this.transitions.get(key).push({
      fromYaw,
      toYaw,
      timestamp: Date.now()
    });

    this.stats.totalTransitions++;
  }

  /**
   * Get all connected locations from a given location
   * @param {string} location - Location "lat,lng"
   * @returns {Set<string>} Set of connected locations
   */
  getConnections(location) {
    return this.connections.get(location) || new Set();
  }

  /**
   * Find an unvisited escape direction from current location
   * @param {string} currentLocation - Current location "lat,lng"
   * @param {Map} visitedUrls - Map of visited locations
   * @returns {string|null} Connected unvisited location or null
   */
  findEscape(currentLocation, visitedUrls) {
    const connections = this.getConnections(currentLocation);

    for (const connected of connections) {
      if (!visitedUrls.has(connected)) {
        return connected;  // Found unvisited escape!
      }
    }

    return null;  // All learned connections are visited
  }

  /**
   * Get the average yaw correction for a transition
   * @param {string} fromLoc - Starting location
   * @param {string} toLoc - Destination location
   * @returns {number|null} Average toYaw or null if no data
   */
  getYawCorrection(fromLoc, toLoc) {
    const key = `${fromLoc}->${toLoc}`;
    const transitions = this.transitions.get(key);

    if (!transitions || transitions.length === 0) return null;

    const avgYaw = transitions.reduce((sum, t) => sum + t.toYaw, 0) / transitions.length;
    return avgYaw;
  }

  /**
   * Check if a connection exists
   * @param {string} fromLoc - Starting location
   * @param {string} toLoc - Destination location
   * @returns {boolean} True if connection exists
   */
  hasConnection(fromLoc, toLoc) {
    const connections = this.connections.get(fromLoc);
    return connections ? connections.has(toLoc) : false;
  }

  /**
   * Get bidirectional connections (A↔B)
   * @returns {Array<{a: string, b: string}>} Array of bidirectional pairs
   */
  getBidirectionalPairs() {
    const pairs = [];
    const seen = new Set();

    for (const [from, connections] of this.connections) {
      for (const to of connections) {
        const key = [from, to].sort().join('|');
        if (!seen.has(key) && this.hasConnection(to, from)) {
          pairs.push({ a: from, b: to });
          seen.add(key);
        }
      }
    }

    return pairs;
  }

  /**
   * Analyze yaw deltas for bidirectional transitions
   * @returns {Object} Statistics about yaw deltas
   */
  analyzeYawDeltas() {
    const pairs = this.getBidirectionalPairs();
    const deltas = [];

    for (const { a, b } of pairs) {
      const forward = this.getYawCorrection(a, b);
      const reverse = this.getYawCorrection(b, a);

      if (forward !== null && reverse !== null) {
        let delta = Math.abs(forward - reverse);
        if (delta > 180) delta = 360 - delta;
        deltas.push(delta);
      }
    }

    if (deltas.length === 0) {
      return { count: 0, avg: null, min: null, max: null };
    }

    return {
      count: deltas.length,
      avg: deltas.reduce((a, b) => a + b, 0) / deltas.length,
      min: Math.min(...deltas),
      max: Math.max(...deltas),
      distribution: this._getDistribution(deltas)
    };
  }

  _getDistribution(deltas) {
    const buckets = {
      '150-170': 0,
      '170-180': 0,
      '180-190': 0,
      '190-210': 0,
      'other': 0
    };

    deltas.forEach(d => {
      if (d >= 150 && d < 170) buckets['150-170']++;
      else if (d >= 170 && d < 180) buckets['170-180']++;
      else if (d >= 180 && d < 190) buckets['180-190']++;
      else if (d >= 190 && d < 210) buckets['190-210']++;
      else buckets.other++;
    });

    return buckets;
  }

  /**
   * Get graph statistics
   * @returns {Object} Graph statistics
   */
  getStats() {
    const degrees = Array.from(this.connections.values()).map(c => c.size);
    const avgDegree = degrees.length > 0 
      ? degrees.reduce((a, b) => a + b, 0) / degrees.length 
      : 0;

    return {
      ...this.stats,
      locations: this.connections.size,
      avgDegree: avgDegree.toFixed(2),
      linearNodes: degrees.filter(d => d === 2).length,
      branchingNodes: degrees.filter(d => d > 2).length,
      crossroads: degrees.filter(d => d >= 3).length  // Nodes with 3+ exits
    };
  }

  /**
   * Check if a location is a crossroad (3+ connections)
   * @param {string} location - Location to check
   * @returns {boolean} True if crossroad
   */
  isCrossroad(location) {
    const connections = this.connections.get(location);
    return connections ? connections.size >= 3 : false;
  }

  /**
   * Find escape with crossroad prioritization
   * Prefers paths that lead TO or FROM crossroads (more exploration options)
   * @param {string} currentLocation - Current location
   * @param {Map} visitedUrls - Visited locations
   * @returns {{location: string, isCrossroad: boolean, priority: number}|null}
   */
  findEscapeWithPriority(currentLocation, visitedUrls) {
    const connections = this.getConnections(currentLocation);
    if (!connections || connections.size === 0) return null;

    const options = [];

    for (const connected of connections) {
      if (!visitedUrls.has(connected)) {
        const connectedIsCrossroad = this.isCrossroad(connected);
        const currentIsCrossroad = this.isCrossroad(currentLocation);

        // Priority scoring:
        // 3 = Going TO a crossroad from a crossroad (max options)
        // 2 = Going TO a crossroad (more options ahead)
        // 1 = Going FROM a crossroad (exploiting known hub)
        // 0 = Normal path
        let priority = 0;
        if (currentIsCrossroad && connectedIsCrossroad) priority = 3;
        else if (connectedIsCrossroad) priority = 2;
        else if (currentIsCrossroad) priority = 1;

        options.push({
          location: connected,
          isCrossroad: connectedIsCrossroad,
          priority
        });
      }
    }

    if (options.length === 0) return null;

    // Sort by priority (highest first), then pick best
    options.sort((a, b) => b.priority - a.priority);
    return options[0];
  }

  /**
   * Clear all data
   */
  clear() {
    this.connections.clear();
    this.transitions.clear();
    this.stats = { totalTransitions: 0, uniqueConnections: 0 };
  }

  /**
   * Export graph to JSON (for persistence)
   * @returns {Object} Serializable graph data
   */
  toJSON() {
    return {
      connections: Array.from(this.connections.entries()).map(([loc, set]) => [loc, Array.from(set)]),
      transitions: Array.from(this.transitions.entries()),
      stats: this.stats
    };
  }

  /**
   * Import graph from JSON (from persistence)
   * @param {Object} data - Serialized graph data
   */
  fromJSON(data) {
    this.clear();

    if (data.connections) {
      for (const [loc, connections] of data.connections) {
        this.connections.set(loc, new Set(connections));
      }
    }

    if (data.transitions) {
      for (const [key, transitions] of data.transitions) {
        this.transitions.set(key, transitions);
      }
    }

    if (data.stats) {
      this.stats = data.stats;
    }
  }
}

/**
 * Create a transition graph instance
 */
function createTransitionGraph() {
  return new TransitionGraph();
}


  // === TRAVERSAL ALGORITHMS ===
  /**
 * Traversal Algorithms v5.1.0 - Smart Node Exploration
 * 
 * KEY INSIGHT: We can only know a node is "straight" AFTER trying all 6 directions.
 * Until then, every node is a potential crossroad (T-junction, 4-way, etc.)
 * 
 * EXPLORATION STRATEGY:
 * 1. Forward pass: Record every node's entry/exit yaws
 * 2. At dead end: Scan ALL 6 directions to confirm
 * 3. Navigate back: Skip "straight" nodes, stop at nodes with untried yaws
 * 4. At each stop: Try ALL 6 directions (don't stop at 2 exits - could be T-shaped!)
 * 
 * NODE CLASSIFICATION (only after trying all 6 yaws):
 * - STRAIGHT: 2 exits, ~180° apart (continue walking)
 * - CROSSROAD: 3+ exits (exploration opportunity)
 * - DEAD_END: 1 exit (mark and escape)
 * - UNKNOWN: <6 yaws tried (potential crossroad - STOP HERE!)
 */

/**
 * Normalizes angle to 0-359
 */
function normalizeAngle(angle) {
  angle = angle % 360;
  if (angle < 0) angle += 360;
  return angle;
}

/**
 * Calculate yaw difference between two angles (0-180°)
 */
function yawDifference(yaw1, yaw2) {
  let diff = Math.abs(normalizeAngle(yaw1) - normalizeAngle(yaw2));
  if (diff > 180) diff = 360 - diff;
  return diff;
}

/**
 * Extract yaw from Google Street View URL
 */
function extractYawFromUrl(url) {
  if (!url) return null;
  const match = url.match(/yaw%3D([0-9.]+)/);
  return match ? parseFloat(match[1]) : null;
}

/**
 * Extract location from Google Street View URL
 */
function extractLocationFromUrl(url) {
  if (!url) return null;
  const hashMatch = url.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
  if (hashMatch) {
    return `${hashMatch[1]},${hashMatch[2]}`;
  }
  return null;
}

/**
 * Predict next location given current location, orientation, and step distance
 */
function predictNextLocation(currentLocation, orientation, stepDistance = 0.0005) {
  if (!currentLocation || typeof currentLocation !== 'string') return null;
  const parts = currentLocation.split(',');
  if (parts.length < 2) return currentLocation;

  const [lat, lng] = parts.map(Number);
  const yawRad = orientation * Math.PI / 180;

  const dLat = Math.cos(yawRad) * stepDistance;
  const dLng = Math.sin(yawRad) * stepDistance / Math.cos(lat * Math.PI / 180);

  const nextLat = (lat + dLat).toFixed(6);
  const nextLng = (lng + dLng).toFixed(6);

  return `${nextLat},${nextLng}`;
}

/**
 * Calculate entropy of visited locations in scan directions
 */
function calculateEntropy(visitedUrls, currentLocation, orientation) {
  const scanAngles = [0, 60, -60, 120, -120, 180];

  const visitCounts = scanAngles.map(angle => {
    const testOrientation = normalizeAngle(orientation + angle);
    const testLocation = predictNextLocation(currentLocation, testOrientation);
    if (!testLocation) return 0;
    return visitedUrls.get(testLocation) || 0;
  });

  const avgVisits = visitCounts.reduce((a, b) => a + b, 0) / visitCounts.length;
  const variance = visitCounts.reduce((sum, v) => sum + Math.pow(v - avgVisits, 2), 0) / visitCounts.length;

  return { avgVisits, variance, visitCounts };
}

/**
 * NODE INFO CLASS
 * Stores metadata about each visited location
 * 
 * CRITICAL: Node type is ONLY determined after trying all 6 directions!
 * - Before 6 tries: Node is "UNKNOWN" (treat as potential crossroad)
 * - After 6 tries: Classify as STRAIGHT, CROSSROAD, or DEAD_END
 */
class NodeInfo {
  constructor(location, lat, lng, step) {
    this.location = location;
    this.lat = lat;
    this.lng = lng;
    this.firstVisitStep = step;
    this.lastVisitStep = step;

    // Yaw tracking
    this.triedYaws = new Set();      // All yaws we've attempted
    this.successfulYaws = new Set(); // Yaws that resulted in movement
    this.connections = new Map();    // yaw → targetLocation

    // Node classification (ONLY valid after trying all 6 yaws)
    this.isStraight = false;
    this.isCrossroad = false;
    this.isDeadEnd = false;
    this.isFullyExplored = false;
  }

  /**
   * Record a yaw attempt
   * @param {number} yaw - The yaw we tried
   * @param {boolean} success - Did we move?
   * @param {string|null} targetLocation - Where did we go?
   */
  recordAttempt(yaw, success, targetLocation = null) {
    this.triedYaws.add(normalizeAngle(yaw));
    this.lastVisitStep = Date.now();

    if (success && targetLocation) {
      this.successfulYaws.add(normalizeAngle(yaw));
      this.connections.set(normalizeAngle(yaw), targetLocation);
    }

    this.updateType();
  }

  /**
   * Update node classification based on tried yaws
   * ONLY classifies after all 6 directions have been tried
   */
  updateType() {
    // Can't classify until we've tried all 6 directions
    if (this.triedYaws.size < 6) {
      return;
    }

    this.isFullyExplored = true;
    const exitCount = this.connections.size;

    if (exitCount === 1) {
      this.isDeadEnd = true;
    } else if (exitCount === 2) {
      // Check if exits are ~180° apart (straight path)
      const yaws = Array.from(this.successfulYaws);
      if (yaws.length === 2) {
        const diff = yawDifference(yaws[0], yaws[1]);
        this.isStraight = diff > 150;  // ~180° ± 30° tolerance
      }
    } else if (exitCount >= 3) {
      this.isCrossroad = true;
    }
  }

  /**
   * Check if this node has untried directions
   * @returns {boolean} True if we should STOP here and scan
   */
  hasUntriedYaws() {
    return this.triedYaws.size < 6;
  }

  /**
   * Get next untried yaw
   * @returns {number|null} Next yaw to try, or null if all tried
   */
  getNextUntriedYaw() {
    const allYaws = [0, 60, 120, 180, 240, 300];
    for (const yaw of allYaws) {
      if (!this.triedYaws.has(yaw)) {
        return yaw;
      }
    }
    return null;
  }

  /**
   * Get all connected locations
   */
  getConnections() {
    return Array.from(this.connections.values());
  }

  /**
   * Get exit count (how many directions worked)
   */
  getExitCount() {
    return this.connections.size;
  }
}

/**
 * ENHANCED TRANSITION GRAPH
 * Augments the basic connection graph with node metadata
 */
class EnhancedTransitionGraph {
  constructor() {
    this.nodes = new Map();  // location → NodeInfo
    this.connections = new Map();  // location → Set<location> (backward compat)
  }

  /**
   * Get or create node info
   */
  getOrCreate(location, lat, lng, step = 0) {
    if (!this.nodes.has(location)) {
      this.nodes.set(location, new NodeInfo(location, lat, lng, step));
      this.connections.set(location, new Set());
    }
    return this.nodes.get(location);
  }

  /**
   * Get node info
   */
  get(location) {
    return this.nodes.get(location);
  }

  /**
   * Record movement from one location to another
   */
  recordMovement(fromLoc, toLoc, fromYaw, toYaw, step) {
    const fromNode = this.getOrCreate(fromLoc, 
      parseFloat(fromLoc.split(',')[0]), 
      parseFloat(fromLoc.split(',')[1]), 
      step
    );
    const toNode = this.getOrCreate(toLoc,
      parseFloat(toLoc.split(',')[0]),
      parseFloat(toLoc.split(',')[1]),
      step
    );

    // Record successful exit from fromNode
    fromNode.recordAttempt(fromYaw, true, toLoc);

    // Record entry to toNode
    toNode.entryYaw = toYaw;

    // Update backward compatibility connections
    if (!this.connections.get(fromLoc).has(toLoc)) {
      this.connections.get(fromLoc).add(toLoc);
    }
  }

  /**
   * Record failed movement attempt
   */
  recordFailedAttempt(location, yaw, step) {
    const node = this.getOrCreate(location,
      parseFloat(location.split(',')[0]),
      parseFloat(location.split(',')[1]),
      step
    );
    node.recordAttempt(yaw, false, null);
  }

  /**
   * Find nearest node with untried yaws (potential crossroad)
   * @param {string} currentLocation - Starting point
   * @param {Array<string>} pathBack - Path back to start
   * @returns {NodeInfo|null} Nearest unexplored node
   */
  findNearestUnexploredNode(currentLocation, pathBack) {
    for (const loc of pathBack) {
      const node = this.nodes.get(loc);
      if (node && !node.isFullyExplored && node.hasUntriedYaws()) {
        return node;
      }
    }
    return null;
  }

  /**
   * Get statistics
   */
  getStats() {
    const nodes = Array.from(this.nodes.values());
    return {
      totalNodes: nodes.length,
      fullyExplored: nodes.filter(n => n.isFullyExplored).length,
      straight: nodes.filter(n => n.isStraight).length,
      crossroads: nodes.filter(n => n.isCrossroad).length,
      deadEnds: nodes.filter(n => n.isDeadEnd).length,
      unknown: nodes.filter(n => !n.isFullyExplored).length
    };
  }

  /**
   * Backward compatibility - get connections for location
   */
  getConnections(location) {
    return this.connections.get(location) || new Set();
  }

  /**
   * Check if location is a crossroad
   */
  isCrossroad(location) {
    const node = this.nodes.get(location);
    return node ? node.isCrossroad : false;
  }

  /**
   * Find escape with priority (backward compatibility)
   */
  findEscapeWithPriority(currentLocation, visitedUrls) {
    const connections = this.getConnections(currentLocation);
    if (!connections || connections.size === 0) return null;

    const options = [];

    for (const connected of connections) {
      if (!visitedUrls.has(connected)) {
        const connectedNode = this.nodes.get(connected);
        const currentNode = this.nodes.get(currentLocation);
        const connectedIsCrossroad = connectedNode ? connectedNode.isCrossroad : false;
        const currentIsCrossroad = currentNode ? currentNode.isCrossroad : false;

        let priority = 0;
        if (currentIsCrossroad && connectedIsCrossroad) priority = 3;
        else if (connectedIsCrossroad) priority = 2;
        else if (currentIsCrossroad) priority = 1;

        options.push({
          location: connected,
          isCrossroad: connectedIsCrossroad,
          priority,
          yaw: currentNode ? currentNode.connections.get(connected) : null
        });
      }
    }

    if (options.length === 0) return null;

    options.sort((a, b) => b.priority - a.priority);
    return options[0];
  }
}

/**
 * UNIFIED ALGORITHM v5.1.0 - Smart Node Exploration
 * 
 * Combines direction preference with smart node exploration:
 * - Tries ALL 6 directions at each node (don't stop at 2!)
 * - Classifies nodes only after full exploration
 * - Skips "straight" nodes when navigating back
 * - Stops at nodes with untried yaws (potential crossroads)
 */
function createUnifiedAlgorithm(cfg) {
  const panicThreshold = cfg.panicThreshold || 3;
  let preferredYaw = null;
  let lastSearchAngle = 0;
  let extendedStuckCount = 0;
  let consecutiveTurns = 0;

  // Enhanced graph with node metadata
  const enhancedGraph = new EnhancedTransitionGraph();

  const decide = (context) => {
    const { 
      stuckCount, 
      currentLocation, 
      visitedUrls, 
      breadcrumbs, 
      orientation,
      transitionGraph 
    } = context;

    // Initialize preferred yaw from current orientation
    if (!preferredYaw) {
      preferredYaw = orientation;
    }

    // Get or create current node info
    if (!currentLocation) {
      return { turn: false };
    }

    const currentParts = currentLocation.split(',').map(Number);
    const currentNode = enhancedGraph.getOrCreate(
      currentLocation, 
      currentParts[0], 
      currentParts[1]
    );

    // PRIORITY 0: Oscillation Detection (A->B->A->B pattern)
    if (cfg.expOn && stuckCount === 0 && breadcrumbs.length >= 6) {
      const recent = breadcrumbs.slice(-6);
      if (recent[0] === recent[4] && recent[1] === recent[5] && recent[0] !== recent[1]) {
        console.log("🔄 OSCILLATION DETECTED! Breaking cycle with random turn");
        consecutiveTurns = 0;
        return { turn: true, angle: Math.floor(Math.random() * 360) };
      }
    }

    // PRIORITY 1: Early Loop Detection (returning to recent breadcrumb)
    if (cfg.expOn && currentLocation && stuckCount === 0) {
      const recentBreadcrumbIndex = breadcrumbs.slice(-10).indexOf(currentLocation);
      if (recentBreadcrumbIndex !== -1 && recentBreadcrumbIndex < 8) {
        console.log(`🔄 LOOP DETECTED (back to step -${10 - recentBreadcrumbIndex})! 180° escape`);
        consecutiveTurns = 0;
        return { turn: true, angle: 180 };
      }
    }

    // PRIORITY 2: Systematic Search (Stuck Recovery)
    // This triggers when we've been stuck for multiple ticks
    if (stuckCount >= panicThreshold) {
      extendedStuckCount = stuckCount;
      consecutiveTurns = 0;

      let searchIncrement = 60;
      if (stuckCount >= 10) {
        searchIncrement = 30;  // Fine-grained search
      }
      if (stuckCount >= 20) {
        const randomAngle = Math.floor(Math.random() * 360);
        console.log(`🎲 Extended stuck (${stuckCount}), random escape: ${randomAngle}°`);
        return { turn: true, angle: randomAngle };
      }

      if (stuckCount === panicThreshold) {
        lastSearchAngle = searchIncrement;
      } else {
        lastSearchAngle = (lastSearchAngle + searchIncrement) % 360;
        if (lastSearchAngle === 0) lastSearchAngle = searchIncrement;
      }
      return { turn: true, angle: lastSearchAngle };
    }

    // PRIORITY 3: Entropy-Based Escape (linear territory)
    if (cfg.expOn && cfg.selfAvoiding && currentLocation && stuckCount === 0) {
      const entropy = calculateEntropy(visitedUrls, currentLocation, orientation);
      const isLowEntropy = entropy.variance < 5 && entropy.avgVisits > 2;

      if (isLowEntropy) {
        consecutiveTurns++;
        if (consecutiveTurns >= 2) {
          const randomAngle = Math.floor(Math.random() * 360);
          console.log(`🎲 LOW ENTROPY (var=${entropy.variance.toFixed(2)}), random escape: ${randomAngle}°`);
          consecutiveTurns = 0;
          return { turn: true, angle: randomAngle };
        }
      } else {
        consecutiveTurns = 0;
      }
    }

    // PRIORITY 4: Smart Node Exploration
    // If current node has untried yaws, try them ALL (don't stop at 2!)
    if (cfg.expOn && cfg.selfAvoiding && currentNode.hasUntriedYaws()) {
      const nextYaw = currentNode.getNextUntriedYaw();
      if (nextYaw !== null) {
        const turnAngle = yawDifference(orientation, nextYaw);
        if (turnAngle > 5 && turnAngle < 355) {
          console.log(`🔍 Scanning node: trying yaw ${nextYaw}° (${currentNode.triedYaws.size}/6)`);
          return { turn: true, angle: turnAngle };
        }
      }
    }

    // PRIORITY 5: Transition Graph with Crossroad + Direction Priority
    if (cfg.expOn && cfg.selfAvoiding && currentLocation) {
      const escapeOption = enhancedGraph.findEscapeWithPriority(currentLocation, visitedUrls);

      if (escapeOption) {
        const learnedEscape = escapeOption.location;
        const parts = learnedEscape.split(',');
        const targetLat = parseFloat(parts[0]);
        const targetLng = parseFloat(parts[1]);
        const currentLat = parseFloat(currentParts[0]);
        const currentLng = parseFloat(currentParts[1]);

        const dLat = targetLat - currentLat;
        const dLng = targetLng - currentLng;
        let targetYaw = Math.atan2(dLng, dLat) * 180 / Math.PI;
        if (targetYaw < 0) targetYaw += 360;

        const directionDiff = yawDifference(targetYaw, preferredYaw);
        const crossroadScore = (3 - escapeOption.priority) / 3;
        const directionScore = directionDiff / 180;
        const combinedScore = (directionScore * 0.7) + (crossroadScore * 0.3);

        if (combinedScore < 0.7 || escapeOption.priority >= 2) {
          if (directionDiff > 10 && directionDiff < 90) {
            preferredYaw = normalizeAngle(preferredYaw + (directionDiff * 0.3));
          }

          const turnAngle = yawDifference(orientation, targetYaw);
          if (turnAngle > 10 && turnAngle < 350) {
            if (escapeOption.priority > 0) {
              console.log(`🗺️ Crossroad priority ${escapeOption.priority} escape (dir diff: ${directionDiff.toFixed(0)}°)`);
            }
            return { turn: true, angle: turnAngle };
          }
        }
      }
    }

    // PRIORITY 6: Weighted Exploration with Direction Preference (fallback)
    if (cfg.expOn && cfg.selfAvoiding && currentLocation && stuckCount === 0) {
      consecutiveTurns = 0;

      const scanAngles = [0, 60, -60, 120, -120, 180, -180];
      let bestScore = Infinity;
      let bestAngle = 0;

      for (const angle of scanAngles) {
        const testOrientation = normalizeAngle(orientation + angle);
        const testLocation = predictNextLocation(currentLocation, testOrientation);
        if (!testLocation) continue;

        const visitCount = visitedUrls.get(testLocation) || 0;
        let breadcrumbPenalty = 0;
        breadcrumbs.forEach((bc, index) => {
          if (bc === testLocation) breadcrumbPenalty += (100 - index * 5);
        });

        const predictedYaw = testOrientation;
        const directionDiff = yawDifference(predictedYaw, preferredYaw);
        const directionScore = directionDiff / 180;

        const heatmapScore = visitCount * 10;
        const forwardBias = (angle === 0) ? -0.1 : 0;
        const score = (heatmapScore * 0.5) + (directionScore * 0.3) + (breadcrumbPenalty * 0.2) + forwardBias;

        if (score < bestScore) {
          bestScore = score;
          bestAngle = angle;
        }
      }

      if (bestAngle !== 0) {
        return { turn: true, angle: Math.abs(bestAngle) };
      }
    }

    return { turn: false };
  };

  return { 
    decide,
    enhancedGraph  // Expose for recording movements
  };
}

// Default export for backward compatibility
const createDefaultAlgorithm = createUnifiedAlgorithm;

// Backward compatibility aliases
const createExplorationAlgorithm = createUnifiedAlgorithm;
const createSurgicalAlgorithm = createUnifiedAlgorithm;
const createHunterAlgorithm = createUnifiedAlgorithm;


  // === NAVIGATION COMPATIBILITY LAYER ===
  /**
 * Navigation Strategies - Compatibility Wrapper for v4.0.0+
 * This file maintains the old API for tests and bundle validation
 * but uses the new Traversal/Wheel architecture.
 */

function createProactiveAvoidance(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeProactiveAvoidance: (yaw, loc, visited) => {
      const result = algorithm.decide({ stuckCount: 0, currentLocation: loc, visitedUrls: visited, orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createUnstuckNavigation(cfg, callbacks) {
  const algorithm = createDefaultAlgorithm(cfg);
  return {
    executeUnstuck: (stuckCount, panicThreshold, yaw) => {
      const result = algorithm.decide({ stuckCount, currentLocation: '', visitedUrls: new Set(), orientation: yaw });
      return result.turn ? { action: 'turn', turnAngle: result.angle, newYaw: (yaw - result.angle + 360) % 360 } : { action: 'none' };
    },
    isBusy: () => false,
    reset: () => {},
    getState: () => ({ state: 'IDLE' })
  };
}

function createNavigationController(cfg, callbacks) {
  return {
    tick: () => ({ action: 'move', strategy: 'normal', busy: false }),
    getCumulativeTurnAngle: () => 0,
    resetCumulativeTurnAngle: () => {},
    reset: () => {},
    getState: () => ({ globalOrientation: 0, proactive: { state: 'IDLE' }, unstuck: { state: 'IDLE' } })
  };
}

const __default_export = {
  createProactiveAvoidance,
  createUnstuckNavigation,
  createNavigationController
};


  // === CORE ENGINE ===
  // State management, tick timing, path recording
  // TO CHANGE ENGINE: Edit src/core/engine.js
  /**
 * Drunk Walker Core Engine
 * Independent navigation logic - works without UI
 * 
 * ARCHITECTURE:
 * - Engine: State management, tick timing, path recording (this file)
 * - Wheel: Orientation management (in src/core/wheel.js)
 * - Traversal: Decision-making logic (in src/core/traversal.js)
 * 
 * TO CHANGE NAVIGATION BEHAVIOR:
 * Edit src/core/traversal.js - NOT this file
 */

const VERSION = '5.1.0-SMART-NODES';

const defaultConfig = {
  pace: 2000,
  kbOn: true,      // Keyboard mode ON by default
  expOn: true,     // Experimental mode ON by default (enables unstuck algorithm)
  panicThreshold: 3,
  radius: 50,
  targetX: 0.4,    // 40% of screen width (left of center)
  targetY: 0.8,    // 80% of screen height (lower than center)
  turnDuration: 600,  // ms to hold ArrowLeft for ~60° turn (fixed)
  collectPath: true,  // Path recording ENABLED by default
  selfAvoiding: true  // Self-avoiding walk ENABLED by default (opt-out)
};

function createEngine(config = {}) {
  const cfg = { ...defaultConfig, ...config };

  let status = 'IDLE';
  let steps = 0;
  let intervalId = null;
  let lastUrl = typeof window !== 'undefined' ? window.location.href : '';
  let stuckCount = 0;
  let isUserMouseDown = false;
  let poly = [];
  let isDrawing = false;
  let isBusy = false;

  // Path collection (opt-in)
  let walkPath = [];
  let isPathCollectionEnabled = cfg.collectPath;

  // Visited nodes memory for self-avoiding walk
  let visitedUrls = new Map(); // location -> count
  let breadcrumbs = []; // last 100 locations

  // Track previous location for movement recording
  let previousLocation = null;
  let previousYaw = null;

  // Transition graph for learning actual connectivity
  const transitionGraph = createTransitionGraph();
  let lastRecordedLocation = null;
  let lastRecordedYaw = null;

  // Action callbacks (to be provided by caller)
  let onKeyPress = null;
  let onMouseClick = null;
  let onStatusUpdate = null;
  let onLongKeyPress = null;
  let onWalkStop = null;

  // Extract location from Street View URL
  const extractLocation = (url) => {
    try {
      const urlObj = new URL(url);
      const hash = urlObj.hash || urlObj.pathname;
      const match = hash.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
      if (match) {
        return `${match[1]},${match[2]}`;
      }
      const placeMatch = urlObj.searchParams.get('place_id');
      if (placeMatch) {
        return `place:${placeMatch}`;
      }
      return urlObj.pathname + urlObj.hash;
    } catch (e) {
      return url;
    }
  };

  // Components
  const wheel = createWheel({
    onLongKeyPress: (key, duration, callback) => {
      if (onLongKeyPress) onLongKeyPress(key, duration, callback);
      else if (callback) callback();
    }
  });

  let algorithm = createDefaultAlgorithm(cfg);

  // State getters
  const getStatus = () => status;
  const getSteps = () => steps;
  const getStuckCount = () => stuckCount;
  const isNavigating = () => status === 'WALKING';

  // Configuration setters
  const setPace = (newPace) => {
    cfg.pace = newPace;
    if (intervalId && status === 'WALKING') {
      clearInterval(intervalId);
      intervalId = setInterval(tick, cfg.pace);
    }
  };
  const setTurnDuration = (newDuration) => { cfg.turnDuration = newDuration; };
  const setKeyboardMode = (on) => { cfg.kbOn = on; };
  const setExperimentalMode = (on) => { cfg.expOn = on; };
  const setPolygon = (points) => { poly = points; };
  const setPathCollection = (enabled) => {
    isPathCollectionEnabled = enabled;
    cfg.collectPath = enabled;
    if (!enabled) walkPath = [];
  };
  const setWalkPath = (path) => { walkPath = path ? [...path] : []; };
  const setSteps = (count) => { steps = count; };
  const getWalkPath = () => [...walkPath];
  const clearWalkPath = () => { walkPath = []; };

  const recordStep = () => {
    if (isPathCollectionEnabled) {
      const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
      const location = extractLocation(currentUrl);

      // Always record the step event for analysis
      walkPath.push({
        url: currentUrl,
        currentYaw: Math.round(wheel.getOrientation())
      });

      // ORIENTATION RECALIBRATION
      // Extract actual yaw from URL and sync internal orientation to prevent drift
      const actualYaw = extractYawFromUrl(currentUrl);
      if (actualYaw !== null) {
        wheel.setOrientation(actualYaw);
      }

      // TRANSITION GRAPH LEARNING
      // Record actual connectivity from observed transitions
      if (lastRecordedLocation && location !== lastRecordedLocation) {
        transitionGraph.record(
          lastRecordedLocation,
          location,
          lastRecordedYaw,
          actualYaw
        );
      }
      lastRecordedLocation = location;
      lastRecordedYaw = actualYaw;

      // MEMORY UPDATE LOGIC
      // Only update Breadcrumbs and Heatmap if we actually MOVED to a new location.
      // This prevents "Amnesia via Hyper-Focus" where spinning in place 20 times
      // would flush the breadcrumb buffer and make the bot forget where it came from.
      const prevLocation = breadcrumbs.length > 0 ? breadcrumbs[breadcrumbs.length - 1] : null;

      if (cfg.selfAvoiding && location !== prevLocation) {
        const count = visitedUrls.get(location) || 0;
        visitedUrls.set(location, count + 1);

        breadcrumbs.push(location);
        if (breadcrumbs.length > 100) breadcrumbs.shift();
      }
    }
  };

  const isUrlVisited = (location) => visitedUrls.has(location);
  const clearVisitedUrls = () => { visitedUrls.clear(); breadcrumbs = []; };
  const getVisitedCount = () => visitedUrls.size;
  const getCurrentYaw = () => wheel.getOrientation();
  const resetCurrentYaw = () => { wheel.reset(); };
  const getCumulativeTurnAngle = getCurrentYaw;
  const resetCumulativeTurnAngle = resetCurrentYaw;

  const restoreVisitedFromPath = (path) => {
    visitedUrls.clear();
    breadcrumbs = [];
    path.forEach(step => {
      let loc = step.location;
      if (!loc && step.url) {
        loc = extractLocation(step.url);
      }
      if (loc) {
        const count = visitedUrls.get(loc) || 0;
        visitedUrls.set(loc, count + 1);

        breadcrumbs.push(loc);
        if (breadcrumbs.length > 100) breadcrumbs.shift();
      }
    });
  };

  const setUserMouseDown = (down) => { isUserMouseDown = down; };
  const setIsDrawing = (drawing) => { isDrawing = drawing; };

  const setActionHandlers = ({ keyPress, mouseClick, statusUpdate, longKeyPress, walkStop }) => {
    onKeyPress = keyPress;
    onMouseClick = mouseClick;
    onStatusUpdate = statusUpdate;
    onLongKeyPress = longKeyPress;
    onWalkStop = walkStop;
  };

  const updateStuckDetection = () => {
    if (!cfg.expOn) {
      stuckCount = 0;
      return;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    if (currentUrl === lastUrl) {
      stuckCount++;
    } else {
      lastUrl = currentUrl;
      stuckCount = 0;
    }
  };

  const getStatusText = () => {
    if (!cfg.expOn || stuckCount === 0) return 'WALKING';
    if (stuckCount >= cfg.panicThreshold) return `PANIC! (STUCK ${stuckCount})`;
    return `STUCK (${stuckCount})`;
  };

  const calculateClickTarget = () => {
    const cw = typeof window !== 'undefined' ? window.innerWidth : 1000;
    const ch = typeof window !== 'undefined' ? window.innerHeight : 1000;

    if (poly.length > 2) {
      const minX = Math.min(...poly.map(p => p.x));
      const maxX = Math.max(...poly.map(p => p.x));
      const minY = Math.min(...poly.map(p => p.y));
      const maxY = Math.max(...poly.map(p => p.y));

      let tx, ty, attempts = 0;
      do {
        tx = minX + Math.random() * (maxX - minX);
        ty = minY + Math.random() * (maxY - minY);
        attempts++;
      } while (!inPoly({ x: tx, y: ty }, poly) && attempts < 100);

      return { x: tx, y: ty };
    }

    const radius = cfg.expOn && stuckCount >= cfg.panicThreshold
      ? cfg.radius * Math.pow(1.5, stuckCount - cfg.panicThreshold + 1)
      : cfg.radius;

    const wobble = () => (Math.random() * 2 - 1) * radius;
    return {
      x: cw * cfg.targetX + wobble(),
      y: cfg.targetY * ch + wobble()
    };
  };

  const inPoly = (p, vs) => {
    let inside = false;
    for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
      const xi = vs[i].x, yi = vs[i].y;
      const xj = vs[j].x, yj = vs[j].y;
      const intersect = ((yi > p.y) !== (yj > p.y)) &&
        (p.x < (xj - xi) * (p.y - yi) / (yj - yi) + xi);
      if (intersect) inside = !inside;
    }
    return inside;
  };

  const tick = () => {
    if (isUserMouseDown || isDrawing) return;

    updateStuckDetection();

    if (onStatusUpdate) {
      onStatusUpdate(getStatusText(), steps, stuckCount);
    }

    if (isBusy) {
      // Skip decision and movement, but still count the step as "busy"
      steps++;
      recordStep();
      return;
    }

    const currentUrl = typeof window !== 'undefined' ? window.location.href : lastUrl;
    const currentLocation = extractLocation(currentUrl);

    // Get algorithm decision
    const context = {
      url: currentUrl,
      location: currentLocation,
      visitedUrls,
      breadcrumbs,
      stuckCount,
      orientation: wheel.getOrientation(),
      transitionGraph  // Pass transition graph for learned navigation
    };

    const decision = algorithm.decide(context);

    if (decision.turn) {
      // Turn BEFORE pressing ArrowUp
      isBusy = true;
      wheel.turnLeft(decision.angle || 60, () => {
        // Continue with ArrowUp after turn finishes
        if (cfg.kbOn) {
          if (onKeyPress) onKeyPress('ArrowUp');
        } else {
          const target = calculateClickTarget();
          if (onMouseClick) onMouseClick(target.x, target.y);
        }
        isBusy = false;
      });
      steps++;
      recordStep();
    } else {
      // Normal movement - record in enhanced graph if we moved
      if (cfg.kbOn) {
        if (onKeyPress) onKeyPress('ArrowUp');
      } else {
        const target = calculateClickTarget();
        if (onMouseClick) onMouseClick(target.x, target.y);
      }
      steps++;
      recordStep();

      // Record movement in enhanced graph (if we actually moved)
      const currentYaw = extractYawFromUrl(currentUrl);
      if (previousLocation && currentLocation !== previousLocation && currentYaw !== null) {
        // We moved to a new location - record in enhanced graph
        if (algorithm.enhancedGraph) {
          algorithm.enhancedGraph.recordMovement(
            previousLocation,
            currentLocation,
            previousYaw || orientation,
            currentYaw,
            steps
          );
        }
      } else if (previousLocation && currentLocation === previousLocation) {
        // We tried to move but stayed - record failed attempt
        if (algorithm.enhancedGraph) {
          const yaw = wheel.getOrientation();
          algorithm.enhancedGraph.recordFailedAttempt(previousLocation, yaw, steps);
        }
      }

      // Update previous location/yaw for next tick
      previousLocation = currentLocation;
      previousYaw = currentYaw;
    }

    console.log(`url=${currentUrl}, currentYaw=${Math.round(wheel.getOrientation())}`);
  };

  const start = () => {
    if (status === 'WALKING') return;
    status = 'WALKING';
    if (steps === 0) {
      stuckCount = 0;
      lastUrl = typeof window !== 'undefined' ? window.location.href : '';
    }
    if (intervalId) clearInterval(intervalId);
    intervalId = setInterval(tick, cfg.pace);
    if (onStatusUpdate) onStatusUpdate('WALKING', steps, stuckCount);
  };

  const stop = () => {
    status = 'IDLE';
    if (intervalId) {
      clearInterval(intervalId);
      intervalId = null;
    }
    if (onWalkStop && isPathCollectionEnabled && walkPath.length > 0) {
      onWalkStop(getWalkPath());
    }
    if (onStatusUpdate) onStatusUpdate('IDLE', steps, 0);
  };

  const reset = () => {
    stop();
    steps = 0;
    stuckCount = 0;
    lastUrl = '';
    status = 'IDLE';
    wheel.reset();
    previousLocation = null;
    previousYaw = null;
    if (transitionGraph) transitionGraph.clear();
  };

  return {
    getStatus,
    getSteps,
    getStuckCount,
    isNavigating,
    setPace,
    setTurnDuration,
    setKeyboardMode,
    setExperimentalMode,
    setPolygon,
    setPathCollection,
    setWalkPath,
    setSteps,
    getWalkPath,
    clearWalkPath,
    setSelfAvoiding: (enabled) => { cfg.selfAvoiding = enabled; },
    getVisitedCount,
    clearVisitedUrls,
    isUrlVisited,
    getVisitedUrls: () => visitedUrls,  // Expose for map rendering
    getCurrentYaw,
    resetCurrentYaw,
    getCumulativeTurnAngle,
    resetCumulativeTurnAngle,
    restoreVisitedFromPath,
    setUserMouseDown,
    setIsDrawing,
    setActionHandlers,
    start,
    stop,
    reset,
    tick,
    getConfig: () => ({ ...cfg }),
    // Mode selection removed in v5.0.0 - now using unified algorithm
    // setMode: (mode) => { ... },  // No longer available
    // Stubs for backward compatibility
    getNavigation: () => null,
    getNavigationState: () => ({}),
    setAlgorithm: (newAlgorithm) => { algorithm = newAlgorithm; },

    // Transition Graph API (for learning actual connectivity)
    getTransitionGraph: () => transitionGraph,
    getTransitionStats: () => transitionGraph.getStats(),
    analyzeYawDeltas: () => transitionGraph.analyzeYawDeltas()
  };
}


  // === INPUT HANDLERS ===
  /**
 * Input Handlers - Keyboard and Mouse Event Simulation
 */
const KEY_CODES = {
  ArrowUp: { keyCode: 38, code: 'ArrowUp' },
  ArrowLeft: { keyCode: 37, code: 'ArrowLeft' },
  ArrowDown: { keyCode: 40, code: 'ArrowDown' },
  ArrowRight: { keyCode: 39, code: 'ArrowRight' }
};
/**
 * Find the best target element for Street View events
 */
function findStreetViewTarget() {
  // Priority order: canvas -> scene viewer -> streetview container -> document
  return document.querySelector('canvas[width][height]') ||
    document.querySelector('.scene-viewer') ||
    document.querySelector('[class*="streetview"]') ||
    document.documentElement;
}
/**
 * Simulate keyboard event (keydown -> keypress -> keyup)
 * @param {string} key - Key to simulate (e.g., 'ArrowUp')
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateKeyPress(key, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };
  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };
  const targetEl = target || findStreetViewTarget();
  // Full key event sequence for maximum compatibility
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  targetEl.dispatchEvent(new KeyboardEvent('keypress', eventOptions));
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
  }, 50);
}
/**
 * Simulate long-press keyboard event (keydown -> hold -> keyup)
 * Used for turning (e.g., hold ArrowLeft for 30° turn)
 * @param {string} key - Key to simulate (e.g., 'ArrowLeft')
 * @param {number} duration - How long to hold the key (ms)
 * @param {Function} callback - Called after key is released
 * @param {HTMLElement} target - Target element (optional)
 */
function simulateLongKeyPress(key, duration, callback, target = null) {
  const { keyCode, code } = KEY_CODES[key] || { keyCode: 0, code: key };
  const eventOptions = {
    key,
    code,
    keyCode,
    which: keyCode,
    bubbles: true,
    cancelable: true,
    location: 2,
    repeat: false,
    altKey: false,
    ctrlKey: false,
    metaKey: false,
    shiftKey: false
  };
  const targetEl = target || findStreetViewTarget();
  // Key down
  targetEl.dispatchEvent(new KeyboardEvent('keydown', eventOptions));
  // Hold for duration, then release
  setTimeout(() => {
    targetEl.dispatchEvent(new KeyboardEvent('keyup', eventOptions));
    if (callback) callback();
  }, duration);
}
/**
 * Simulate mouse click at coordinates
 * @param {number} x - X coordinate
 * @param {number} y - Y coordinate
 * @param {boolean} showMarker - Whether to show visual marker
 */
function simulateClick(x, y, showMarker = true) {
  const eventOptions = {
    bubbles: true,
    cancelable: true,
    clientX: x,
    clientY: y,
    screenX: x,
    screenY: y
  };
  const target = document.elementFromPoint(x, y) || document.body;
  target.dispatchEvent(new MouseEvent('mousedown', eventOptions));
  target.dispatchEvent(new MouseEvent('mouseup', eventOptions));
  target.dispatchEvent(new MouseEvent('click', eventOptions));
  // Visual feedback marker
  if (showMarker) {
    const marker = document.createElement('div');
    marker.style.cssText = `
      position:fixed;
      left:${x}px;
      top:${y}px;
      width:15px;
      height:15px;
      background:cyan;
      border-radius:50%;
      z-index:999999;
      pointer-events:none;
      transform:translate(-50%,-50%);
      opacity:0.8;
      transition:transform 0.3s, opacity 0.3s;
    `;
    document.body.appendChild(marker);
    setTimeout(() => {
      marker.style.transform = 'translate(-50%,-50%) scale(2)';
      marker.style.opacity = '0';
      setTimeout(() => marker.remove(), 300);
    }, 50);
  }
}
/**
 * Set up user interaction listeners
 * @returns {Object} Cleanup function
 */
function setupInteractionListeners(callbacks = {}) {
  const { onUserMouseDown, onUserMouseUp } = callbacks;
  const mouseDownHandler = (e) => {
    if (e.isTrusted && onUserMouseDown) {
      onUserMouseDown(true);
    }
  };
  const mouseUpHandler = (e) => {
    if (e.isTrusted && onUserMouseUp) {
      onUserMouseUp(false);
    }
  };
  document.addEventListener('mousedown', mouseDownHandler, true);
  document.addEventListener('mouseup', mouseUpHandler, true);
  return {
    cleanup: () => {
      document.removeEventListener('mousedown', mouseDownHandler, true);
      document.removeEventListener('mouseup', mouseUpHandler, true);
    }
  };
}

  // === EXPLORATION MAP ===
  // Real-time mini-map showing explored territory
  /**
 * Exploration Map Component
 * Renders a mini-map showing explored territory from walker's perspective
 */

function createExplorationMap() {
  let canvas = null;
  let ctx = null;
  let container = null;
  let isVisible = false;
  let isExpanded = false;

  // Map state
  let centerLat = 0;
  let centerLng = 0;
  let zoom = 1;
  const baseZoom = 0.0001; // meters per pixel

  // Create map container and canvas
  function init() {
    // Create container
    container = document.createElement('div');
    container.id = 'dw-map-container';
    container.style.cssText = `
      position: fixed;
      bottom: 10px;
      left: 50%;
      transform: translateX(-50%);
      background: rgba(0, 0, 0, 0.85);
      border: 2px solid #444;
      border-radius: 8px;
      padding: 8px;
      z-index: 999998;
      display: none;
      font-family: monospace;
      font-size: 11px;
      color: #fff;
      min-width: 320px;
    `;

    // Header with controls
    const header = document.createElement('div');
    header.style.cssText = `
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 6px;
      padding: 0 4px;
    `;

    const title = document.createElement('span');
    title.textContent = '🗺️ EXPLORATION MAP';
    title.style.cssText = 'font-weight: bold; color: #4fc3f7;';

    const controls = document.createElement('div');
    controls.style.cssText = 'display: flex; gap: 6px;';

    // Expand/collapse button
    const expandBtn = document.createElement('button');
    expandBtn.textContent = '⛶';
    expandBtn.title = 'Expand/Collapse';
    expandBtn.style.cssText = `
      background: #333;
      border: 1px solid #555;
      color: #fff;
      padding: 2px 6px;
      cursor: pointer;
      border-radius: 3px;
      font-size: 12px;
    `;
    expandBtn.onmouseover = () => expandBtn.style.background = '#444';
    expandBtn.onmouseout = () => expandBtn.style.background = '#333';
    expandBtn.onclick = () => toggleExpand();

    // Close button
    const closeBtn = document.createElement('button');
    closeBtn.textContent = '✕';
    closeBtn.title = 'Close (M)';
    closeBtn.style.cssText = `
      background: #333;
      border: 1px solid #555;
      color: #fff;
      padding: 2px 6px;
      cursor: pointer;
      border-radius: 3px;
      font-size: 12px;
    `;
    closeBtn.onmouseover = () => closeBtn.style.background = '#c62828';
    closeBtn.onmouseout = () => closeBtn.style.background = '#333';
    closeBtn.onclick = () => hide();

    controls.appendChild(expandBtn);
    controls.appendChild(closeBtn);
    header.appendChild(title);
    header.appendChild(controls);

    // Stats bar
    const statsBar = document.createElement('div');
    statsBar.id = 'dw-map-stats';
    statsBar.style.cssText = `
      display: flex;
      gap: 12px;
      padding: 4px 8px;
      background: rgba(50, 50, 50, 0.5);
      border-radius: 4px;
      margin-bottom: 6px;
      font-size: 10px;
    `;
    statsBar.innerHTML = `
      <span style="color: #81c784;">● Visited: <strong id="dw-stat-visited">0</strong></span>
      <span style="color: #ffb74d;">★ Crossroads: <strong id="dw-stat-crossroads">0</strong></span>
      <span style="color: #e57373;">⚑ Dead ends: <strong id="dw-stat-deadends">0</strong></span>
    `;

    // Canvas container
    const canvasContainer = document.createElement('div');
    canvasContainer.style.cssText = `
      position: relative;
      border: 1px solid #444;
      border-radius: 4px;
      overflow: hidden;
    `;

    // Create canvas
    canvas = document.createElement('canvas');
    canvas.width = 300;
    canvas.height = 200;
    canvas.style.cssText = 'display: block;';

    canvasContainer.appendChild(canvas);
    ctx = canvas.getContext('2d');

    container.appendChild(header);
    container.appendChild(statsBar);
    container.appendChild(canvasContainer);

    document.body.appendChild(container);

    // Keyboard shortcut
    document.addEventListener('keydown', (e) => {
      if (e.key === 'm' || e.key === 'M') {
        e.preventDefault();
        toggle();
      }
    });
  }

  // Toggle map visibility
  function toggle() {
    if (!container) init();
    isVisible = !isVisible;
    container.style.display = isVisible ? 'block' : 'none';
    if (isVisible) render();
  }

  // Show map
  function show() {
    if (!container) init();
    isVisible = true;
    container.style.display = 'block';
    render();
  }

  // Hide map
  function hide() {
    isVisible = false;
    if (container) container.style.display = 'none';
  }

  // Toggle expanded mode
  function toggleExpand() {
    isExpanded = !isExpanded;
    if (isExpanded) {
      canvas.width = 600;
      canvas.height = 400;
    } else {
      canvas.width = 300;
      canvas.height = 200;
    }
    render();
  }

  // Convert GPS to screen coordinates
  function gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom) {
    const scale = zoom * 10000000; // Scale factor
    const x = width / 2 + (lng - centerLng) * scale;
    const y = height / 2 - (lat - centerLat) * scale * 1.5; // Adjust for lat distortion
    return { x, y };
  }

  // Render the map
  function render(transitionGraph, currentLocation, visitedUrls) {
    if (!ctx || !canvas) return;

    const width = canvas.width;
    const height = canvas.height;

    // Clear canvas
    ctx.fillStyle = '#1a1a2e';
    ctx.fillRect(0, 0, width, height);

    if (!transitionGraph) {
      // Show "no data" message
      ctx.fillStyle = '#666';
      ctx.font = '14px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('Walk in progress...', width / 2, height / 2);
      return;
    }

    // Get all locations
    const stats = transitionGraph.getStats();
    const locations = Array.from(transitionGraph.connections.keys());

    if (locations.length === 0) {
      ctx.fillStyle = '#666';
      ctx.font = '14px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('No locations yet...', width / 2, height / 2);
      return;
    }

    // Calculate bounds
    let minLat = Infinity, maxLat = -Infinity;
    let minLng = Infinity, maxLng = -Infinity;

    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
      minLng = Math.min(minLng, lng);
      maxLng = Math.max(maxLng, lng);
    });

    // Set center
    centerLat = (minLat + maxLat) / 2;
    centerLng = (minLng + maxLng) / 2;

    // Calculate zoom to fit all points
    const latRange = maxLat - minLat || 0.0001;
    const lngRange = maxLng - minLng || 0.0001;
    zoom = Math.min(width / lngRange / 100000, height / latRange / 100000) * 0.8;

    // Draw connections first (edges)
    ctx.strokeStyle = '#444';
    ctx.lineWidth = 1;

    locations.forEach(loc => {
      const connections = transitionGraph.getConnections(loc);
      const [lat1, lng1] = loc.split(',').map(Number);
      const pos1 = gpsToScreen(lat1, lng1, centerLat, centerLng, width, height, zoom);

      connections.forEach(conn => {
        const [lat2, lng2] = conn.split(',').map(Number);
        const pos2 = gpsToScreen(lat2, lng2, centerLat, centerLng, width, height, zoom);

        ctx.beginPath();
        ctx.moveTo(pos1.x, pos1.y);
        ctx.lineTo(pos2.x, pos2.y);
        ctx.stroke();
      });
    });

    // Draw nodes
    locations.forEach(loc => {
      const [lat, lng] = loc.split(',').map(Number);
      const pos = gpsToScreen(lat, lng, centerLat, centerLng, width, height, zoom);

      const isCrossroad = transitionGraph.isCrossroad(loc);
      const isCurrent = loc === currentLocation;
      const isVisited = visitedUrls ? visitedUrls.has(loc) : false;

      // Node style
      if (isCurrent) {
        // Current position - pulsing circle
        ctx.fillStyle = '#4fc3f7';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 6, 0, Math.PI * 2);
        ctx.fill();

        // Outer ring
        ctx.strokeStyle = '#fff';
        ctx.lineWidth = 2;
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 8, 0, Math.PI * 2);
        ctx.stroke();
      } else if (isCrossroad) {
        // Crossroad - star/larger circle
        ctx.fillStyle = '#ffb74d';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 5, 0, Math.PI * 2);
        ctx.fill();
      } else if (isVisited) {
        // Visited - green circle
        ctx.fillStyle = '#81c784';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 3, 0, Math.PI * 2);
        ctx.fill();
      } else {
        // Unvisited - red dot
        ctx.fillStyle = '#e57373';
        ctx.beginPath();
        ctx.arc(pos.x, pos.y, 2, 0, Math.PI * 2);
        ctx.fill();
      }
    });

    // Update stats
    const deadEnds = locations.filter(loc => {
      const conns = transitionGraph.getConnections(loc);
      return conns.size === 1;
    }).length;

    document.getElementById('dw-stat-visited').textContent = locations.length;
    document.getElementById('dw-stat-crossroads').textContent = stats.crossroads || 0;
    document.getElementById('dw-stat-deadends').textContent = deadEnds;
  }

  return {
    init,
    toggle,
    show,
    hide,
    toggleExpand,
    render,
    isVisible: () => isVisible
  };
}


  // === UI CONTROLLER ===
  /**
 * UI Controller - Control Panel Management
 */

function createControlPanel(engine, options = {}) {
  const {
    version = '3.70.0-EXP',
    autoStart = true,
    onPathCollectionToggle = null  // Callback for path collection toggle
  } = options;

  let container = null;
  let btn = null;
  let statusEl = null;
  let stepsEl = null;
  let visitedEl = null;
  let paceValEl = null;
  let paceSlider = null;
  let downloadLogsBtn = null;
  let minimizeBtn = null;
  let mainContent = null;
  let isMinimized = false;

  // Session logs storage
  const sessionLogs = [];
  const originalConsoleLog = console.log;

  // Intercept console.log to capture logs
  console.log = function(...args) {
    const timestamp = new Date().toISOString();
    const message = args.map(arg => 
      typeof arg === 'object' ? JSON.stringify(arg) : String(arg)
    ).join(' ');
    sessionLogs.push(`[${timestamp}] ${message}`);
    originalConsoleLog.apply(console, args);
  };

  // Create UI elements
  const createUI = () => {
    container = document.createElement('div');
    container.id = 'dw-ctrl-panel';
    container.style.cssText = 'position:fixed;top:20px;right:20px;background:rgba(0,0,0,0.9);color:#0f0;padding:15px;font-family:monospace;z-index:999999;border:2px solid #0f0;border-radius:10px;box-shadow:0 0 15px #0f0;min-width:180px;user-select:none;';

    // Header with minimize button
    const header = document.createElement('div');
    header.style.cssText = 'display:flex;justify-content:space-between;align-items:center;margin-bottom:5px;';

    const title = document.createElement('div');
    title.innerText = `🤪 DRUNK WALKER v${version}`;
    title.style.fontSize = '12px';
    title.style.fontWeight = 'bold';

    minimizeBtn = document.createElement('button');
    minimizeBtn.innerText = '−';
    minimizeBtn.style.cssText = 'background:none;border:1px solid #0f0;color:#0f0;cursor:pointer;padding:0 5px;font-weight:bold;font-size:14px;';
    minimizeBtn.onclick = toggleMinimize;

    header.appendChild(title);
    header.appendChild(minimizeBtn);
    container.appendChild(header);

    const hr = document.createElement('hr');
    hr.id = 'dw-header-hr';
    hr.style.borderColor = '#0f0';
    container.appendChild(hr);

    // Visible Steps (Always visible or in steps section)
    const stepsLine = document.createElement('div');
    stepsLine.style.margin = '5px 0';
    stepsLine.innerHTML = 'STEPS: <span id="dw-steps">0</span>';
    container.appendChild(stepsLine);
    stepsEl = stepsLine.querySelector('#dw-steps');

    // Main Content wrapper (Toggleable)
    mainContent = document.createElement('div');
    mainContent.id = 'dw-main-content';

    // Remaining Stats
    const stats = document.createElement('div');
    stats.style.margin = '5px 0';
    stats.innerHTML = 'STATUS: <span id="dw-status">IDLE</span><br>VISITED: <span id="dw-visited">0</span>';
    mainContent.appendChild(stats);
    statusEl = stats.querySelector('#dw-status');
    visitedEl = stats.querySelector('#dw-visited');

    // Direction indicator (replaces mode toggle in v5.0.0)
    const directionLabel = document.createElement('div');
    directionLabel.style.fontSize = '10px';
    directionLabel.style.marginTop = '10px';
    directionLabel.innerHTML = 'ALGORITHM: <span style="color:#0f0;">UNIFIED v5.0.0</span>';
    mainContent.appendChild(directionLabel);

    const infoText = document.createElement('div');
    infoText.style.fontSize = '9px';
    infoText.style.color = '#888';
    infoText.style.marginTop = '5px';
    infoText.innerHTML = 'Direction + Heatmap + Crossroads';
    mainContent.appendChild(infoText);

    // Pace control
    const paceLabel = document.createElement('div');
    paceLabel.style.fontSize = '10px';
    paceLabel.style.marginTop = '10px';
    paceLabel.innerHTML = 'PACE: <span id="dw-pace-val">2.0</span>s';
    mainContent.appendChild(paceLabel);
    paceValEl = paceLabel.querySelector('#dw-pace-val');

    paceSlider = document.createElement('input');
    paceSlider.type = 'range';
    paceSlider.min = '500';
    paceSlider.max = '5000';
    paceSlider.step = '100';
    paceSlider.value = engine.getConfig().pace;
    paceSlider.style.width = '100%';
    paceSlider.oninput = () => {
      const newPace = parseInt(paceSlider.value);
      if (paceValEl) paceValEl.innerText = (newPace / 1000).toFixed(1);
      engine.setPace(newPace);
    };
    mainContent.appendChild(paceSlider);

    // Path export button (Download only)
    const exportDiv = document.createElement('div');
    exportDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';

    // Download path JSON button
    const downloadPathBtn = document.createElement('button');
    downloadPathBtn.innerText = '💾 Download Path';
    downloadPathBtn.style.cssText = 'flex:1;padding:6px;background:#28a745;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadPathBtn.onclick = () => {
      const walkPath = engine.getWalkPath();
      if (walkPath.length === 0) {
        alert('No path recorded. Start walking!');
        return;
      }
      const jsonStr = JSON.stringify(walkPath, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-${new Date().toISOString().replace(/[:.]/g, '-')}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      downloadPathBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadPathBtn.innerText = '💾 Download Path';
      }, 2000);
    };

    exportDiv.appendChild(downloadPathBtn);
    mainContent.appendChild(exportDiv);

    // Download logs button
    const logsDiv = document.createElement('div');
    logsDiv.style.cssText = 'display:flex;gap:5px;margin-top:8px;';

    downloadLogsBtn = document.createElement('button');
    downloadLogsBtn.innerText = '📄 Download Logs';
    downloadLogsBtn.style.cssText = 'width:100%;padding:6px;background:#ff6600;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    downloadLogsBtn.onclick = () => {
      if (sessionLogs.length === 0) {
        alert('No logs recorded yet. Start walking to generate logs!');
        return;
      }

      const logContent = sessionLogs.join('\n');
      const blob = new Blob([logContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `walk-logs-${new Date().toISOString().replace(/[:.]/g, '-')}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      downloadLogsBtn.innerText = '✓ Downloaded!';
      setTimeout(() => {
        downloadLogsBtn.innerText = '📄 Download Logs';
      }, 2000);
    };

    logsDiv.appendChild(downloadLogsBtn);
    mainContent.appendChild(logsDiv);

    // Restore Walk from JSON button
    const restoreBtn = document.createElement('button');
    restoreBtn.innerText = '📂 Restore Walk';
    restoreBtn.style.cssText = 'width:100%;margin-top:8px;padding:6px;background:#663399;color:#fff;border:none;font-weight:bold;cursor:pointer;border-radius:4px;font-size:10px;';
    restoreBtn.onclick = () => {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = '.json,application/json';
      input.onchange = (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
          try {
            const walkPath = JSON.parse(event.target.result);
            if (!Array.isArray(walkPath) || walkPath.length === 0) {
              throw new Error('Invalid walk path format');
            }

            // Validate path structure
            const firstStep = walkPath[0];
            if (!firstStep.url && !firstStep.location) {
              throw new Error('Invalid path entries');
            }

            // Restore walk path
            engine.setWalkPath(walkPath);

            // Restore visited URLs from path
            engine.restoreVisitedFromPath(walkPath);

            // Navigate to last URL in path
            const lastStep = walkPath[walkPath.length - 1];
            if (lastStep.url) {
              window.location.href = lastStep.url;
            }

            console.log(`🤪 DRUNK WALKER: Restored walk with ${walkPath.length} steps`);
            alert(`✓ Walk restored!\n\n${walkPath.length} steps loaded\nNavigating to last position...`);
          } catch (err) {
            console.error('Failed to restore walk:', err);
            alert('❌ Failed to restore walk\n\n' + err.message + '\n\nPlease ensure the file is a valid walk JSON export.');
          }
        };
        reader.readAsText(file);
      };
      input.click();
    };
    mainContent.appendChild(restoreBtn);

    // Start/Stop button
    btn = document.createElement('button');
    btn.innerText = '▶ START';
    btn.style.cssText = 'width:100%;margin-top:10px;padding:8px;background:#0f0;color:#000;border:none;font-weight:bold;cursor:pointer;border-radius:5px;';
    btn.onclick = () => {
      if (engine.isNavigating()) {
        engine.stop();
      } else {
        engine.start();
      }
      updateButton();
    };
    mainContent.appendChild(btn);

    container.appendChild(mainContent);
    document.body.appendChild(container);

    // Ensure features are enabled by default as requested
    if (onPathCollectionToggle) onPathCollectionToggle(true);
    engine.setSelfAvoiding(true);
  };

  const toggleMinimize = () => {
    isMinimized = !isMinimized;
    if (isMinimized) {
      mainContent.style.display = 'none';
      minimizeBtn.innerText = '+';
      container.style.minWidth = '100px';
    } else {
      mainContent.style.display = 'block';
      minimizeBtn.innerText = '−';
      container.style.minWidth = '180px';
    }
  };

  // Update button appearance based on state
  const updateButton = () => {
    if (!btn) return;
    if (engine.isNavigating()) {
      btn.innerText = '🔴 STOP';
      btn.style.background = '#f00';
    } else {
      btn.innerText = '▶ START';
      btn.style.background = '#0f0';
    }
  };

  // Status update handler
  const onStatusUpdate = (statusText, stepCount, stuckCount) => {
    if (statusEl) statusEl.innerText = statusText;
    if (stepsEl) stepsEl.innerText = stepCount;
    if (visitedEl) visitedEl.innerText = engine.getVisitedCount();
    updateButton();
  };

  // Initialize
  const init = () => {
    // Wait for DOM to be ready
    if (!document.body) {
      console.error('🤪 DRUNK WALKER: document.body not ready yet');
      return { destroy: () => {} };
    }

    try {
      createUI();
      updateButton();

      if (autoStart) {
        engine.start();
      }

      console.log('🤪 Control panel created successfully');
      return { destroy };
    } catch (error) {
      console.error('🤪 DRUNK WALKER: Failed to initialize UI:', error);
      return { destroy: () => {} };
    }
  };

  // Path collection state getter - always true now
  const getPathCollectionEnabled = () => true;

  // Cleanup
  const destroy = () => {
    engine.stop();
    if (container) {
      container.remove();
      container = null;
    }
  };

  return { init, destroy, onStatusUpdate, getPathCollectionEnabled };
}


  // === MAIN ENTRY ===
  /**
 * Drunk Walker - Main Entry Point
 * Combines core engine, input handlers, and UI
 */

// Allow restart by clearing previous instance
if (window.DRUNK_WALKER_ACTIVE) {
  console.log('🤪 Drunk Walker: Restarting...');
  if (window.DRUNK_WALKER) {
    try { window.DRUNK_WALKER.stop(); } catch(e) {}
  }
}

window.DRUNK_WALKER_ACTIVE = true;

console.log(`🤪 DRUNK WALKER v${VERSION} Loaded.`);

// Wait for DOM to be ready before initializing
const initialize = () => {
  try {
    // Check for screensaver mode restoration from localStorage
    let savedState = null;
    try {
      const saved = localStorage.getItem('drunkWalkerScreensaver');
      if (saved) {
        savedState = JSON.parse(saved);
        console.log('🤪 Restoring screensaver session...');
      }
    } catch (e) {
      console.log('🤪 No saved session found');
    }

    // Create engine with default config (keyboard mode ON, unstuck enabled)
    const engine = createEngine({
      pace: savedState?.pace || 2000,
      kbOn: true,      // Keyboard mode is DEFAULT
      expOn: true      // Unstuck algorithm enabled by default
    });

    // Restore state if coming from screensaver
    if (savedState) {
      // Restore walk path
      if (savedState.walkPath && Array.isArray(savedState.walkPath)) {
        engine.setWalkPath(savedState.walkPath);
        console.log('🤪 Restored', savedState.walkPath.length, 'path points');
      }

      // Restore steps count
      if (savedState.steps) {
        engine.setSteps(savedState.steps);
        console.log('🤪 Restored', savedState.steps, 'steps');
      }
    }

    // Set up interaction listeners (pause on user drag)
    const { cleanup: cleanupListeners } = setupInteractionListeners({
      onUserMouseDown: (down) => engine.setUserMouseDown(down),
      onUserMouseUp: (down) => engine.setUserMouseDown(down)
    });

    // Listen for screensaver initialization messages
    window.addEventListener('message', (event) => {
      if (event.data?.type === 'DRUNK_WALKER_INIT') {
        console.log('🤪 Screensaver window initialized');
      }
    });

    // Path collection submit handler
    const submitWalkPath = async (walkPath) => {
      try {
        const payload = {
          timestamp: new Date().toISOString(),
          steps: walkPath.length,
          walkPath: walkPath
        };

        // Send to backend (fail silently if unavailable)
        await fetch('/api/submit-walk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        }).catch(() => {
          console.log('🤪 Walk path submission failed (server unavailable)');
        });
      } catch (error) {
        console.log('🤪 Walk path submission error:', error.message);
      }
    };

    // Create exploration map
    const map = createExplorationMap();
    map.init();

    // Create UI - this will autoStart after action handlers are set
    const ui = createControlPanel(engine, {
      version: VERSION,
      autoStart: false,  // We'll start manually after handlers are set
      onPathCollectionToggle: (enabled) => {
        engine.setPathCollection(enabled);
      }
    });

    // Set up ALL action handlers BEFORE starting
    engine.setActionHandlers({
      keyPress: (key) => {
        const target = findStreetViewTarget();
        simulateKeyPress(key, target);
      },
      mouseClick: (x, y) => {
        simulateClick(x, y, true);
      },
      longKeyPress: (key, duration, callback) => {
        const target = findStreetViewTarget();
        simulateLongKeyPress(key, duration, callback, target);
      },
      statusUpdate: (status, steps, stuckCount) => {
        ui.onStatusUpdate(status, steps, stuckCount);
        // Update map periodically (every 10 ticks)
        if (steps % 10 === 0 && map.isVisible()) {
          const transitionGraph = engine.getTransitionGraph();
          const currentLocation = engine.getWalkPath().length > 0 
            ? engine.getWalkPath()[engine.getWalkPath().length - 1].location 
            : null;
          map.render(transitionGraph, currentLocation, engine.getVisitedUrls());
        }
      },
      walkStop: submitWalkPath
    });

    // Initialize UI
    ui.init();

    // Now start walking (after everything is set up)
    engine.start();

    // Resume screensaver session if needed (already started above)
    if (savedState?.isWalking) {
      console.log('🤪 Screensaver session restored');
    }

    // Expose for debugging/console access
    window.DRUNK_WALKER = {
      engine,
      ui,
      map,
      simulateKeyPress,
      simulateClick,
      stop: () => {
        ui.destroy();
        cleanupListeners();
        window.DRUNK_WALKER_ACTIVE = false;
        delete window.DRUNK_WALKER;
        console.log('🤪 Drunk Walker stopped');
      }
    };

    console.log('🎮 Type DRUNK_WALKER.stop() to stop manually');
  } catch (error) {
    console.error('🤪 DRUNK WALKER: Initialization failed:', error);
    window.DRUNK_WALKER_ACTIVE = false;
  }
};

// Initialize when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initialize);
} else {
  initialize();
}

})();