/**
 * Build Script - Creates the unified bookmarklet for browser console and extension
 *
 * ⚠️ GENERATED FILES WARNING:
 * bookmarklet.js is AUTO-GENERATED.
 * DO NOT edit this file directly - changes will be lost on next build.
 *
 * TO MAKE CHANGES:
 * 1. Edit source files in src/ directory
 * 2. Run: node build.js
 * 3. Generated files will be updated automatically
 */

import fs from 'fs';
import path from 'path';

const outfile = 'bookmarklet.js';
const extensionOutfile = 'extension/drunk-walker.js';

// Read version from version.js (single source of truth)
const versionSource = fs.readFileSync('src/version.js', 'utf8');
const versionMatch = versionSource.match(/export const VERSION = ['"]([^'"]+)['"]/);
const VERSION = versionMatch ? versionMatch[1] : '0.0.0-DEV';

console.log(`ℹ️  Building version: ${VERSION}`);

/**
 * Strip ES module syntax from source code
 * This is CRITICAL - any exports/imports left will cause browser errors
 * 
 * @param {string} code - Source code to strip
 * @returns {string} - Code with all ES module syntax removed
 */
function stripModuleSyntax(code) {
  // Remove JSDoc comments that reference imports/exports
  code = code.replace(/\/\*\*[\s\S]*?@param[\s\S]*?from\s+['"]\.\//g, '/**');
  code = code.replace(/\/\*\*[\s\S]*?@returns[\s\S]*?from\s+['"]\.\//g, '/**');
  
  return code
    // Remove all import statements (various formats, including multi-line)
    .replace(/import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];?/g, '')
    .replace(/import\s+['"][^'"]+['"];?/g, '')  // side-effect imports
    // Remove all export statements (various formats)
    .replace(/export\s+{/g, 'const __export_dummy = {')  // export { a, b }
    .replace(/export\s+default\s+/g, 'const __default_export = ')  // export default
    .replace(/export\s+const\s+/g, 'const ')
    .replace(/export\s+let\s+/g, 'let ')
    .replace(/export\s+var\s+/g, 'var ')
    .replace(/export\s+function\s+/g, 'function ')
    .replace(/export\s+class\s+/g, 'class ')
    .replace(/export\s+async\s+function/g, 'async function')
    // Remove standalone export/import statements (including in comments)
    .replace(/^\s*(import|export)\s.*;?/gm, '')
    // Remove empty lines created by stripping
    .replace(/^\s*$/gm, '');
}

// Read all source files (order matters)
const versionFile = fs.readFileSync('src/version.js', 'utf8');
const wheel = fs.readFileSync('src/core/wheel.js', 'utf8');
const traversal = fs.readFileSync('src/core/traversal.js', 'utf8');
const navigation = fs.readFileSync('src/core/navigation.js', 'utf8');
const engine = fs.readFileSync('src/core/engine.js', 'utf8');
const handlers = fs.readFileSync('src/input/handlers.js', 'utf8');
const explorationMap = fs.readFileSync('src/ui/exploration-map.js', 'utf8');
const controller = fs.readFileSync('src/ui/controller.js', 'utf8');
const main = fs.readFileSync('src/main.js', 'utf8');

// Console-friendly build (uses void operator to avoid IIFE issues in console)
let content = `
// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v${VERSION} - BUNDLED BOOKMARKLET
// Built: ${new Date().toISOString()}
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js from source files in src/
// ═══════════════════════════════════════════════════════════════════════════════

void function initDrunkWalker(){
  // Main entry point handles restart logic now
  
  // === VERSION ===
  ${stripModuleSyntax(versionFile)}

  // === WHEEL ===
  ${stripModuleSyntax(wheel)}

  // === TRAVERSAL ALGORITHMS ===
  ${stripModuleSyntax(traversal)}

  // === NAVIGATION COMPATIBILITY LAYER ===
  ${stripModuleSyntax(navigation)}

  // === CORE ENGINE ===
  ${stripModuleSyntax(engine)}

  // === INPUT HANDLERS ===
  ${stripModuleSyntax(handlers)}

  // === EXPLORATION MAP ===
  ${stripModuleSyntax(explorationMap)}

  // === UI CONTROLLER ===
  ${stripModuleSyntax(controller)}

  // === MAIN ENTRY ===
  ${stripModuleSyntax(main)}
}();
`.trim();

fs.writeFileSync(outfile, content);

console.log(`✓ Built ${outfile} (${(content.length / 1024).toFixed(1)} KB)`);
console.log(`\n📋 Copy-paste the content of ${outfile} into browser console.`);

// =============================================================================
// EXTENSION BUILD
// =============================================================================

// Create extension directory if it doesn't exist
if (!fs.existsSync('extension')) {
  fs.mkdirSync('extension', { recursive: true });
}
if (!fs.existsSync('extension/icons')) {
  fs.mkdirSync('extension/icons', { recursive: true });
}

// Build extension bundle (same code, different wrapper for content script)
const extensionContent = `
// ═══════════════════════════════════════════════════════════════════════════════
// Drunk Walker v${VERSION} - EXTENSION BUNDLE
// Built: ${new Date().toISOString()}
// ═══════════════════════════════════════════════════════════════════════════════
// ⚠️  AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY!
//
// This file is generated by build.js for the browser extension
// ═══════════════════════════════════════════════════════════════════════════════

(function() {
  'use strict';

  // Prevent multiple injections
  if (window.DRUNK_WALKER_EXTENSION_INJECTED) {
    console.log('Drunk Walker already injected');
    return;
  }
  window.DRUNK_WALKER_EXTENSION_INJECTED = true;

  // === VERSION ===
  ${stripModuleSyntax(versionFile)}

  // === WHEEL ===
  ${stripModuleSyntax(wheel)}

  // === TRAVERSAL ALGORITHMS ===
  ${stripModuleSyntax(traversal)}

  // === NAVIGATION COMPATIBILITY LAYER ===
  ${stripModuleSyntax(navigation)}

  // === CORE ENGINE ===
  ${stripModuleSyntax(engine)}

  // === INPUT HANDLERS ===
  ${stripModuleSyntax(handlers)}

  // === EXPLORATION MAP ===
  ${stripModuleSyntax(explorationMap)}

  // === UI CONTROLLER ===
  ${stripModuleSyntax(controller)}

  // === MAIN ENTRY ===
  ${stripModuleSyntax(main)}

  // Expose stats getter for extension popup
  if (!window.DRUNK_WALKER) {
    window.DRUNK_WALKER = {};
  }

  // Add getter for extension stats
  if (window.DRUNK_WALKER.engine) {
    window.DRUNK_WALKER.getExtensionStats = function() {
      const engine = window.DRUNK_WALKER.engine;
      return {
        isRunning: engine.isNavigating?.() || false,
        steps: engine.getSteps?.() || 0,
        visited: engine.getVisitedCount?.() || 0
      };
    };
  }

})();
`.trim();

fs.writeFileSync(extensionOutfile, extensionContent);

console.log(`✓ Built ${extensionOutfile} (${(extensionContent.length / 1024).toFixed(1)} KB)`);

// Update extension manifest with current version
const manifestPath = 'extension/manifest.json';
if (fs.existsSync(manifestPath)) {
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  manifest.version = VERSION;
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  console.log(`✓ Updated extension manifest to v${VERSION}`);
}

console.log(`\n📦 Extension ready in ./extension/`);
console.log(`   Load in Chrome: chrome://extensions → Developer mode → Load unpacked`);
console.log(`   Load in Firefox: about:debugging → This Firefox → Load Temporary Add-on`);
